package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Address implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long addressId;
   private java.lang.String address1;
   private java.lang.String address2;
   private java.lang.String city;
   private java.lang.String province;
   private java.lang.String zip;
   private java.lang.String zip4;
   private java.lang.String stateId;
   private java.lang.String stateCode;
   private gov.dhs.fema.ndgrants_rules.model.Country country;
   private gov.dhs.fema.ndgrants_rules.model.State state;

   public Address()
   {
   }

   public java.lang.Long getAddressId()
   {
      return this.addressId;
   }

   public void setAddressId(java.lang.Long addressId)
   {
      this.addressId = addressId;
   }

   public java.lang.String getAddress1()
   {
      return this.address1;
   }

   public void setAddress1(java.lang.String address1)
   {
      this.address1 = address1;
   }

   public java.lang.String getAddress2()
   {
      return this.address2;
   }

   public void setAddress2(java.lang.String address2)
   {
      this.address2 = address2;
   }

   public java.lang.String getCity()
   {
      return this.city;
   }

   public void setCity(java.lang.String city)
   {
      this.city = city;
   }

   public java.lang.String getProvince()
   {
      return this.province;
   }

   public void setProvince(java.lang.String province)
   {
      this.province = province;
   }

   public java.lang.String getZip()
   {
      return this.zip;
   }

   public void setZip(java.lang.String zip)
   {
      this.zip = zip;
   }

   public java.lang.String getZip4()
   {
      return this.zip4;
   }

   public void setZip4(java.lang.String zip4)
   {
      this.zip4 = zip4;
   }

   public java.lang.String getStateId()
   {
      return this.stateId;
   }

   public void setStateId(java.lang.String stateId)
   {
      this.stateId = stateId;
   }

   public java.lang.String getStateCode()
   {
      return this.stateCode;
   }

   public void setStateCode(java.lang.String stateCode)
   {
      this.stateCode = stateCode;
   }

   public gov.dhs.fema.ndgrants_rules.model.Country getCountry()
   {
      return this.country;
   }

   public void setCountry(gov.dhs.fema.ndgrants_rules.model.Country country)
   {
      this.country = country;
   }

   public gov.dhs.fema.ndgrants_rules.model.State getState()
   {
      return this.state;
   }

   public void setState(gov.dhs.fema.ndgrants_rules.model.State state)
   {
      this.state = state;
   }

   public Address(java.lang.Long addressId, java.lang.String address1,
         java.lang.String address2, java.lang.String city,
         java.lang.String province, java.lang.String zip,
         java.lang.String zip4, java.lang.String stateId,
         java.lang.String stateCode,
         gov.dhs.fema.ndgrants_rules.model.Country country,
         gov.dhs.fema.ndgrants_rules.model.State state)
   {
      this.addressId = addressId;
      this.address1 = address1;
      this.address2 = address2;
      this.city = city;
      this.province = province;
      this.zip = zip;
      this.zip4 = zip4;
      this.stateId = stateId;
      this.stateCode = stateCode;
      this.country = country;
      this.state = state;
   }

}