package gov.dhs.fema.ndgrants_rules.model;

import gov.dhs.fema.ndgrants_rules.model.EGPCodedTypeDef;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AdministeringOffice extends EGPCodedTypeDef implements java.io.Serializable
{

   static final long serialVersionUID = 1L;
   
    public static final AdministeringOffice REGION_1  = new AdministeringOffice(1, "B");
    public static final AdministeringOffice REGION_2  = new AdministeringOffice(2, "N");
    public static final AdministeringOffice REGION_3  = new AdministeringOffice(3, "P");
    public static final AdministeringOffice REGION_4  = new AdministeringOffice(4, "A");
    public static final AdministeringOffice REGION_5  = new AdministeringOffice(5, "C");
    public static final AdministeringOffice REGION_6  = new AdministeringOffice(6, "T");
    public static final AdministeringOffice REGION_7  = new AdministeringOffice(7, "K");
    public static final AdministeringOffice REGION_8  = new AdministeringOffice(8, "D");
    public static final AdministeringOffice REGION_9  = new AdministeringOffice(9, "F");
    public static final AdministeringOffice REGION_10 = new AdministeringOffice(10, "S");
    public static final AdministeringOffice NETC = new AdministeringOffice(11, "E");    
    public static final AdministeringOffice HEADQUARTERS = new AdministeringOffice(12, "W");
    
   public AdministeringOffice()
   {
   }
   
   AdministeringOffice(long id, String code){
       super(id, code);
   }

}