package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AmendmentRecommendation implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long amendmentRecommendationId;
   private gov.dhs.fema.ndgrants_rules.model.AmendmentRequest amendmentRequest;
   private java.lang.String amendmentRecommendationNumber;
   private gov.dhs.fema.ndgrants_rules.model.BudgetAndPop budgetAndPop;
   private java.util.Date lastUpdated;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424ABudget> sf424aBudgets;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424CBudget> sf424cBudgets;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> terms;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.CommitmentAmount> commitmentAmounts;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.Document> documents;

   private gov.dhs.fema.ndgrants_rules.model.AmendmentRecommendationStatus status;

   public AmendmentRecommendation()
   {
   }

   public java.lang.Long getAmendmentRecommendationId()
   {
      return this.amendmentRecommendationId;
   }

   public void setAmendmentRecommendationId(
         java.lang.Long amendmentRecommendationId)
   {
      this.amendmentRecommendationId = amendmentRecommendationId;
   }

   public gov.dhs.fema.ndgrants_rules.model.AmendmentRequest getAmendmentRequest()
   {
      return this.amendmentRequest;
   }

   public void setAmendmentRequest(
         gov.dhs.fema.ndgrants_rules.model.AmendmentRequest amendmentRequest)
   {
      this.amendmentRequest = amendmentRequest;
   }

   public java.lang.String getAmendmentRecommendationNumber()
   {
      return this.amendmentRecommendationNumber;
   }

   public void setAmendmentRecommendationNumber(
         java.lang.String amendmentRecommendationNumber)
   {
      this.amendmentRecommendationNumber = amendmentRecommendationNumber;
   }

   public gov.dhs.fema.ndgrants_rules.model.BudgetAndPop getBudgetAndPop()
   {
      return this.budgetAndPop;
   }

   public void setBudgetAndPop(
         gov.dhs.fema.ndgrants_rules.model.BudgetAndPop budgetAndPop)
   {
      this.budgetAndPop = budgetAndPop;
   }

   public java.util.Date getLastUpdated()
   {
      return this.lastUpdated;
   }

   public void setLastUpdated(java.util.Date lastUpdated)
   {
      this.lastUpdated = lastUpdated;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424ABudget> getSf424aBudgets()
   {
      return this.sf424aBudgets;
   }

   public void setSf424aBudgets(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424ABudget> sf424aBudgets)
   {
      this.sf424aBudgets = sf424aBudgets;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424CBudget> getSf424cBudgets()
   {
      return this.sf424cBudgets;
   }

   public void setSf424cBudgets(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424CBudget> sf424cBudgets)
   {
      this.sf424cBudgets = sf424cBudgets;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> getTerms()
   {
      return this.terms;
   }

   public void setTerms(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> terms)
   {
      this.terms = terms;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.CommitmentAmount> getCommitmentAmounts()
   {
      return this.commitmentAmounts;
   }

   public void setCommitmentAmounts(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.CommitmentAmount> commitmentAmounts)
   {
      this.commitmentAmounts = commitmentAmounts;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.Document> getDocuments()
   {
      return this.documents;
   }

   public void setDocuments(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Document> documents)
   {
      this.documents = documents;
   }

   public gov.dhs.fema.ndgrants_rules.model.AmendmentRecommendationStatus getStatus()
   {
      return this.status;
   }

   public void setStatus(
         gov.dhs.fema.ndgrants_rules.model.AmendmentRecommendationStatus status)
   {
      this.status = status;
   }

   public AmendmentRecommendation(
         java.lang.Long amendmentRecommendationId,
         gov.dhs.fema.ndgrants_rules.model.AmendmentRequest amendmentRequest,
         java.lang.String amendmentRecommendationNumber,
         gov.dhs.fema.ndgrants_rules.model.BudgetAndPop budgetAndPop,
         java.util.Date lastUpdated,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424ABudget> sf424aBudgets,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424CBudget> sf424cBudgets,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> terms,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.CommitmentAmount> commitmentAmounts,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Document> documents,
         gov.dhs.fema.ndgrants_rules.model.AmendmentRecommendationStatus status)
   {
      this.amendmentRecommendationId = amendmentRecommendationId;
      this.amendmentRequest = amendmentRequest;
      this.amendmentRecommendationNumber = amendmentRecommendationNumber;
      this.budgetAndPop = budgetAndPop;
      this.lastUpdated = lastUpdated;
      this.sf424aBudgets = sf424aBudgets;
      this.sf424cBudgets = sf424cBudgets;
      this.terms = terms;
      this.commitmentAmounts = commitmentAmounts;
      this.documents = documents;
      this.status = status;
   }

}