package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AmendmentRequest implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long amendmentRequestId;
   private gov.dhs.fema.ndgrants_rules.model.Grant grant;
   private java.lang.String amendmentRequestNumber;
   private gov.dhs.fema.ndgrants_rules.model.AmendmentRequestStatus status;
   private gov.dhs.fema.ndgrants_rules.model.BudgetAndPop budgetAndPop;
   private boolean notificationSent;
   private java.util.Date submissionDate;
   private java.util.Date lastUpdated;
   private java.lang.String narrative;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424ABudget> sf424aBudgets;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424CBudget> sf424cBudgets;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> terms;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.ExternalAdminContact> contacts;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.FormInstance> formInstances;
   private gov.dhs.fema.ndgrants_rules.model.Document documents;

   public AmendmentRequest()
   {
   }

   public java.lang.Long getAmendmentRequestId()
   {
      return this.amendmentRequestId;
   }

   public void setAmendmentRequestId(java.lang.Long amendmentRequestId)
   {
      this.amendmentRequestId = amendmentRequestId;
   }

   public gov.dhs.fema.ndgrants_rules.model.Grant getGrant()
   {
      return this.grant;
   }

   public void setGrant(gov.dhs.fema.ndgrants_rules.model.Grant grant)
   {
      this.grant = grant;
   }

   public java.lang.String getAmendmentRequestNumber()
   {
      return this.amendmentRequestNumber;
   }

   public void setAmendmentRequestNumber(
         java.lang.String amendmentRequestNumber)
   {
      this.amendmentRequestNumber = amendmentRequestNumber;
   }

   public gov.dhs.fema.ndgrants_rules.model.AmendmentRequestStatus getStatus()
   {
      return this.status;
   }

   public void setStatus(
         gov.dhs.fema.ndgrants_rules.model.AmendmentRequestStatus status)
   {
      this.status = status;
   }

   public gov.dhs.fema.ndgrants_rules.model.BudgetAndPop getBudgetAndPop()
   {
      return this.budgetAndPop;
   }

   public void setBudgetAndPop(
         gov.dhs.fema.ndgrants_rules.model.BudgetAndPop budgetAndPop)
   {
      this.budgetAndPop = budgetAndPop;
   }

   public boolean isNotificationSent()
   {
      return this.notificationSent;
   }

   public void setNotificationSent(boolean notificationSent)
   {
      this.notificationSent = notificationSent;
   }

   public java.util.Date getSubmissionDate()
   {
      return this.submissionDate;
   }

   public void setSubmissionDate(java.util.Date submissionDate)
   {
      this.submissionDate = submissionDate;
   }

   public java.util.Date getLastUpdated()
   {
      return this.lastUpdated;
   }

   public void setLastUpdated(java.util.Date lastUpdated)
   {
      this.lastUpdated = lastUpdated;
   }

   public java.lang.String getNarrative()
   {
      return this.narrative;
   }

   public void setNarrative(java.lang.String narrative)
   {
      this.narrative = narrative;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424ABudget> getSf424aBudgets()
   {
      return this.sf424aBudgets;
   }

   public void setSf424aBudgets(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424ABudget> sf424aBudgets)
   {
      this.sf424aBudgets = sf424aBudgets;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424CBudget> getSf424cBudgets()
   {
      return this.sf424cBudgets;
   }

   public void setSf424cBudgets(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424CBudget> sf424cBudgets)
   {
      this.sf424cBudgets = sf424cBudgets;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> getTerms()
   {
      return this.terms;
   }

   public void setTerms(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> terms)
   {
      this.terms = terms;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.ExternalAdminContact> getContacts()
   {
      return this.contacts;
   }

   public void setContacts(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.ExternalAdminContact> contacts)
   {
      this.contacts = contacts;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.FormInstance> getFormInstances()
   {
      return this.formInstances;
   }

   public void setFormInstances(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.FormInstance> formInstances)
   {
      this.formInstances = formInstances;
   }

   public gov.dhs.fema.ndgrants_rules.model.Document getDocuments()
   {
      return this.documents;
   }

   public void setDocuments(
         gov.dhs.fema.ndgrants_rules.model.Document documents)
   {
      this.documents = documents;
   }

   public AmendmentRequest(
         java.lang.Long amendmentRequestId,
         gov.dhs.fema.ndgrants_rules.model.Grant grant,
         java.lang.String amendmentRequestNumber,
         gov.dhs.fema.ndgrants_rules.model.AmendmentRequestStatus status,
         gov.dhs.fema.ndgrants_rules.model.BudgetAndPop budgetAndPop,
         boolean notificationSent,
         java.util.Date submissionDate,
         java.util.Date lastUpdated,
         java.lang.String narrative,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424ABudget> sf424aBudgets,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424CBudget> sf424cBudgets,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> terms,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.ExternalAdminContact> contacts,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.FormInstance> formInstances,
         gov.dhs.fema.ndgrants_rules.model.Document documents)
   {
      this.amendmentRequestId = amendmentRequestId;
      this.grant = grant;
      this.amendmentRequestNumber = amendmentRequestNumber;
      this.status = status;
      this.budgetAndPop = budgetAndPop;
      this.notificationSent = notificationSent;
      this.submissionDate = submissionDate;
      this.lastUpdated = lastUpdated;
      this.narrative = narrative;
      this.sf424aBudgets = sf424aBudgets;
      this.sf424cBudgets = sf424cBudgets;
      this.terms = terms;
      this.contacts = contacts;
      this.formInstances = formInstances;
      this.documents = documents;
   }

}