package gov.dhs.fema.ndgrants_rules.model;

import gov.dhs.fema.ndgrants_rules.model.EGPTypeDef;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AmendmentRequestStatus extends EGPTypeDef implements java.io.Serializable
{

   static final long serialVersionUID = 1L;
   
   public static final AmendmentRequestStatus PENDING_SUBMISSION = new AmendmentRequestStatus(1);
   public static final AmendmentRequestStatus PENDING_REVIEW = new AmendmentRequestStatus(2);
   public static final AmendmentRequestStatus RECOMMENDED = new AmendmentRequestStatus(3);
   public static final AmendmentRequestStatus WITHDRAWN = new AmendmentRequestStatus(4);
   public static final AmendmentRequestStatus DENIED = new AmendmentRequestStatus(5);
   public static final AmendmentRequestStatus APPROVED = new AmendmentRequestStatus(6);
    

   public AmendmentRequestStatus()
   {
       super();
   }
   
   AmendmentRequestStatus(long id)
   {
       super(id);
   }

}