package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Amendment implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long amendmentId;
   private gov.dhs.fema.ndgrants_rules.model.Grant grant;
   private java.lang.String amendmentNumber;
   private gov.dhs.fema.ndgrants_rules.model.BudgetAndPop budgetAndPop;
   private java.util.Date resubmissionDeadline;
   private java.lang.String amendmentJustification;
   private gov.dhs.fema.ndgrants_rules.model.Vendor vendor;
   private java.lang.Boolean signatureRequired;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424ABudget> sf424aBudgets;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424CBudget> sf424cBudgets;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> terms;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.ExternalAdminContact> contacts;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.CommitmentAmount> commitmentAmounts;
   private java.util.Date effectiveDate;
   private java.math.BigDecimal totalCommitments;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.FormInstance> formInstances;
   private java.util.Date submissionDate;
   private gov.dhs.fema.ndgrants_rules.model.UserRole createdByRole;
   private java.math.BigDecimal conditionalFederal;
   private java.math.BigDecimal conditionalNonFederal;
   private java.util.Date approvalDate;
   private gov.dhs.fema.ndgrants_rules.model.Address granteeOrgPhysicalAddress;
   private gov.dhs.fema.ndgrants_rules.model.Address granteeOrgMailingAddress;
   private gov.dhs.fema.ndgrants_rules.model.CongressionalDistrict granteeOrgCongressionalDistrict;
   private gov.dhs.fema.ndgrants_rules.model.Organization organization;

   private gov.dhs.fema.ndgrants_rules.model.AmendmentRequest amendmentRequest;

   public Amendment()
   {
   }

   public java.lang.Long getAmendmentId()
   {
      return this.amendmentId;
   }

   public void setAmendmentId(java.lang.Long amendmentId)
   {
      this.amendmentId = amendmentId;
   }

   public gov.dhs.fema.ndgrants_rules.model.Grant getGrant()
   {
      return this.grant;
   }

   public void setGrant(gov.dhs.fema.ndgrants_rules.model.Grant grant)
   {
      this.grant = grant;
   }

   public java.lang.String getAmendmentNumber()
   {
      return this.amendmentNumber;
   }

   public void setAmendmentNumber(java.lang.String amendmentNumber)
   {
      this.amendmentNumber = amendmentNumber;
   }

   public gov.dhs.fema.ndgrants_rules.model.BudgetAndPop getBudgetAndPop()
   {
      return this.budgetAndPop;
   }

   public void setBudgetAndPop(
         gov.dhs.fema.ndgrants_rules.model.BudgetAndPop budgetAndPop)
   {
      this.budgetAndPop = budgetAndPop;
   }

   public java.util.Date getResubmissionDeadline()
   {
      return this.resubmissionDeadline;
   }

   public void setResubmissionDeadline(java.util.Date resubmissionDeadline)
   {
      this.resubmissionDeadline = resubmissionDeadline;
   }

   public java.lang.String getAmendmentJustification()
   {
      return this.amendmentJustification;
   }

   public void setAmendmentJustification(
         java.lang.String amendmentJustification)
   {
      this.amendmentJustification = amendmentJustification;
   }

   public gov.dhs.fema.ndgrants_rules.model.Vendor getVendor()
   {
      return this.vendor;
   }

   public void setVendor(gov.dhs.fema.ndgrants_rules.model.Vendor vendor)
   {
      this.vendor = vendor;
   }

   public java.lang.Boolean getSignatureRequired()
   {
      return this.signatureRequired;
   }

   public void setSignatureRequired(java.lang.Boolean signatureRequired)
   {
      this.signatureRequired = signatureRequired;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424ABudget> getSf424aBudgets()
   {
      return this.sf424aBudgets;
   }

   public void setSf424aBudgets(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424ABudget> sf424aBudgets)
   {
      this.sf424aBudgets = sf424aBudgets;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424CBudget> getSf424cBudgets()
   {
      return this.sf424cBudgets;
   }

   public void setSf424cBudgets(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424CBudget> sf424cBudgets)
   {
      this.sf424cBudgets = sf424cBudgets;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> getTerms()
   {
      return this.terms;
   }

   public void setTerms(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> terms)
   {
      this.terms = terms;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.ExternalAdminContact> getContacts()
   {
      return this.contacts;
   }

   public void setContacts(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.ExternalAdminContact> contacts)
   {
      this.contacts = contacts;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.CommitmentAmount> getCommitmentAmounts()
   {
      return this.commitmentAmounts;
   }

   public void setCommitmentAmounts(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.CommitmentAmount> commitmentAmounts)
   {
      this.commitmentAmounts = commitmentAmounts;
   }

   public java.util.Date getEffectiveDate()
   {
      return this.effectiveDate;
   }

   public void setEffectiveDate(java.util.Date effectiveDate)
   {
      this.effectiveDate = effectiveDate;
   }

   public java.math.BigDecimal getTotalCommitments()
   {
      return this.totalCommitments;
   }

   public void setTotalCommitments(java.math.BigDecimal totalCommitments)
   {
      this.totalCommitments = totalCommitments;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.FormInstance> getFormInstances()
   {
      return this.formInstances;
   }

   public void setFormInstances(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.FormInstance> formInstances)
   {
      this.formInstances = formInstances;
   }

   public java.util.Date getSubmissionDate()
   {
      return this.submissionDate;
   }

   public void setSubmissionDate(java.util.Date submissionDate)
   {
      this.submissionDate = submissionDate;
   }

   public gov.dhs.fema.ndgrants_rules.model.UserRole getCreatedByRole()
   {
      return this.createdByRole;
   }

   public void setCreatedByRole(
         gov.dhs.fema.ndgrants_rules.model.UserRole createdByRole)
   {
      this.createdByRole = createdByRole;
   }

   public java.math.BigDecimal getConditionalFederal()
   {
      return this.conditionalFederal;
   }

   public void setConditionalFederal(java.math.BigDecimal conditionalFederal)
   {
      this.conditionalFederal = conditionalFederal;
   }

   public java.math.BigDecimal getConditionalNonFederal()
   {
      return this.conditionalNonFederal;
   }

   public void setConditionalNonFederal(
         java.math.BigDecimal conditionalNonFederal)
   {
      this.conditionalNonFederal = conditionalNonFederal;
   }

   public java.util.Date getApprovalDate()
   {
      return this.approvalDate;
   }

   public void setApprovalDate(java.util.Date approvalDate)
   {
      this.approvalDate = approvalDate;
   }

   public gov.dhs.fema.ndgrants_rules.model.Address getGranteeOrgPhysicalAddress()
   {
      return this.granteeOrgPhysicalAddress;
   }

   public void setGranteeOrgPhysicalAddress(
         gov.dhs.fema.ndgrants_rules.model.Address granteeOrgPhysicalAddress)
   {
      this.granteeOrgPhysicalAddress = granteeOrgPhysicalAddress;
   }

   public gov.dhs.fema.ndgrants_rules.model.Address getGranteeOrgMailingAddress()
   {
      return this.granteeOrgMailingAddress;
   }

   public void setGranteeOrgMailingAddress(
         gov.dhs.fema.ndgrants_rules.model.Address granteeOrgMailingAddress)
   {
      this.granteeOrgMailingAddress = granteeOrgMailingAddress;
   }

   public gov.dhs.fema.ndgrants_rules.model.CongressionalDistrict getGranteeOrgCongressionalDistrict()
   {
      return this.granteeOrgCongressionalDistrict;
   }

   public void setGranteeOrgCongressionalDistrict(
         gov.dhs.fema.ndgrants_rules.model.CongressionalDistrict granteeOrgCongressionalDistrict)
   {
      this.granteeOrgCongressionalDistrict = granteeOrgCongressionalDistrict;
   }

   public gov.dhs.fema.ndgrants_rules.model.Organization getOrganization()
   {
      return this.organization;
   }

   public void setOrganization(
         gov.dhs.fema.ndgrants_rules.model.Organization organization)
   {
      this.organization = organization;
   }

   public gov.dhs.fema.ndgrants_rules.model.AmendmentRequest getAmendmentRequest()
   {
      return this.amendmentRequest;
   }

   public void setAmendmentRequest(
         gov.dhs.fema.ndgrants_rules.model.AmendmentRequest amendmentRequest)
   {
      this.amendmentRequest = amendmentRequest;
   }

   public Amendment(
         java.lang.Long amendmentId,
         gov.dhs.fema.ndgrants_rules.model.Grant grant,
         java.lang.String amendmentNumber,
         gov.dhs.fema.ndgrants_rules.model.BudgetAndPop budgetAndPop,
         java.util.Date resubmissionDeadline,
         java.lang.String amendmentJustification,
         gov.dhs.fema.ndgrants_rules.model.Vendor vendor,
         java.lang.Boolean signatureRequired,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424ABudget> sf424aBudgets,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424CBudget> sf424cBudgets,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> terms,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.ExternalAdminContact> contacts,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.CommitmentAmount> commitmentAmounts,
         java.util.Date effectiveDate,
         java.math.BigDecimal totalCommitments,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.FormInstance> formInstances,
         java.util.Date submissionDate,
         gov.dhs.fema.ndgrants_rules.model.UserRole createdByRole,
         java.math.BigDecimal conditionalFederal,
         java.math.BigDecimal conditionalNonFederal,
         java.util.Date approvalDate,
         gov.dhs.fema.ndgrants_rules.model.Address granteeOrgPhysicalAddress,
         gov.dhs.fema.ndgrants_rules.model.Address granteeOrgMailingAddress,
         gov.dhs.fema.ndgrants_rules.model.CongressionalDistrict granteeOrgCongressionalDistrict,
         gov.dhs.fema.ndgrants_rules.model.Organization organization,
         gov.dhs.fema.ndgrants_rules.model.AmendmentRequest amendmentRequest)
   {
      this.amendmentId = amendmentId;
      this.grant = grant;
      this.amendmentNumber = amendmentNumber;
      this.budgetAndPop = budgetAndPop;
      this.resubmissionDeadline = resubmissionDeadline;
      this.amendmentJustification = amendmentJustification;
      this.vendor = vendor;
      this.signatureRequired = signatureRequired;
      this.sf424aBudgets = sf424aBudgets;
      this.sf424cBudgets = sf424cBudgets;
      this.terms = terms;
      this.contacts = contacts;
      this.commitmentAmounts = commitmentAmounts;
      this.effectiveDate = effectiveDate;
      this.totalCommitments = totalCommitments;
      this.formInstances = formInstances;
      this.submissionDate = submissionDate;
      this.createdByRole = createdByRole;
      this.conditionalFederal = conditionalFederal;
      this.conditionalNonFederal = conditionalNonFederal;
      this.approvalDate = approvalDate;
      this.granteeOrgPhysicalAddress = granteeOrgPhysicalAddress;
      this.granteeOrgMailingAddress = granteeOrgMailingAddress;
      this.granteeOrgCongressionalDistrict = granteeOrgCongressionalDistrict;
      this.organization = organization;
      this.amendmentRequest = amendmentRequest;
   }

}