package gov.dhs.fema.ndgrants_rules.model;

import gov.dhs.fema.ndgrants_rules.model.AssuranceType;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AmendmentAssurance extends AssuranceType implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long amendmentRequestId;
   private java.util.Date signedDate;
   private java.lang.Long userId;
   private java.lang.String loginName;
   private java.lang.String userTitle;
   private java.lang.String firstName;
   private java.lang.String middleName;
   private java.lang.String lastName;
   private java.lang.String primaryPhoneNo;
   private gov.dhs.fema.ndgrants_rules.model.Prefix prefix;
   private gov.dhs.fema.ndgrants_rules.model.Suffix suffix;
   private boolean verifiedSignature;
   private boolean formNotApplicable;

   public AmendmentAssurance()
   {
   }

   public java.lang.Long getAmendmentRequestId()
   {
      return this.amendmentRequestId;
   }

   public void setAmendmentRequestId(java.lang.Long amendmentRequestId)
   {
      this.amendmentRequestId = amendmentRequestId;
   }

   public java.util.Date getSignedDate()
   {
      return this.signedDate;
   }

   public void setSignedDate(java.util.Date signedDate)
   {
      this.signedDate = signedDate;
   }

   public java.lang.Long getUserId()
   {
      return this.userId;
   }

   public void setUserId(java.lang.Long userId)
   {
      this.userId = userId;
   }

   public java.lang.String getLoginName()
   {
      return this.loginName;
   }

   public void setLoginName(java.lang.String loginName)
   {
      this.loginName = loginName;
   }

   public java.lang.String getUserTitle()
   {
      return this.userTitle;
   }

   public void setUserTitle(java.lang.String userTitle)
   {
      this.userTitle = userTitle;
   }

   public java.lang.String getFirstName()
   {
      return this.firstName;
   }

   public void setFirstName(java.lang.String firstName)
   {
      this.firstName = firstName;
   }

   public java.lang.String getMiddleName()
   {
      return this.middleName;
   }

   public void setMiddleName(java.lang.String middleName)
   {
      this.middleName = middleName;
   }

   public java.lang.String getLastName()
   {
      return this.lastName;
   }

   public void setLastName(java.lang.String lastName)
   {
      this.lastName = lastName;
   }

   public java.lang.String getPrimaryPhoneNo()
   {
      return this.primaryPhoneNo;
   }

   public void setPrimaryPhoneNo(java.lang.String primaryPhoneNo)
   {
      this.primaryPhoneNo = primaryPhoneNo;
   }

   public gov.dhs.fema.ndgrants_rules.model.Prefix getPrefix()
   {
      return this.prefix;
   }

   public void setPrefix(gov.dhs.fema.ndgrants_rules.model.Prefix prefix)
   {
      this.prefix = prefix;
   }

   public gov.dhs.fema.ndgrants_rules.model.Suffix getSuffix()
   {
      return this.suffix;
   }

   public void setSuffix(gov.dhs.fema.ndgrants_rules.model.Suffix suffix)
   {
      this.suffix = suffix;
   }

   public boolean isVerifiedSignature()
   {
      return this.verifiedSignature;
   }

   public void setVerifiedSignature(boolean verifiedSignature)
   {
      this.verifiedSignature = verifiedSignature;
   }

   public boolean isFormNotApplicable()
   {
      return this.formNotApplicable;
   }

   public void setFormNotApplicable(boolean formNotApplicable)
   {
      this.formNotApplicable = formNotApplicable;
   }

   public AmendmentAssurance(java.lang.Long amendmentRequestId,
         java.util.Date signedDate, java.lang.Long userId,
         java.lang.String loginName, java.lang.String userTitle,
         java.lang.String firstName, java.lang.String middleName,
         java.lang.String lastName, java.lang.String primaryPhoneNo,
         gov.dhs.fema.ndgrants_rules.model.Prefix prefix,
         gov.dhs.fema.ndgrants_rules.model.Suffix suffix,
         boolean verifiedSignature, boolean formNotApplicable)
   {
      this.amendmentRequestId = amendmentRequestId;
      this.signedDate = signedDate;
      this.userId = userId;
      this.loginName = loginName;
      this.userTitle = userTitle;
      this.firstName = firstName;
      this.middleName = middleName;
      this.lastName = lastName;
      this.primaryPhoneNo = primaryPhoneNo;
      this.prefix = prefix;
      this.suffix = suffix;
      this.verifiedSignature = verifiedSignature;
      this.formNotApplicable = formNotApplicable;
   }

}