package gov.dhs.fema.ndgrants_rules.model;

import gov.dhs.fema.ndgrants_rules.model.EGPTypeDef;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ApplicationContactType extends EGPTypeDef implements java.io.Serializable
{

   static final long serialVersionUID = 1L;
   public static final ApplicationContactType AUTHORIZED_OFFICIAL = new ApplicationContactType(1);
   public static final ApplicationContactType SIGNATORY_AUTHORITY = new ApplicationContactType(2);
   public static final ApplicationContactType PRIMARY_CONTACT = new ApplicationContactType(3);
   public static final ApplicationContactType SECONDARY_CONTACT = new ApplicationContactType(4);    

   public ApplicationContactType()
   {
       super();
   }
   
   ApplicationContactType(long id)
   {
       super(id);
   }

}