package gov.dhs.fema.ndgrants_rules.model;

import gov.dhs.fema.ndgrants_rules.model.FormInstance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ApplicationFormInstance extends FormInstance implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long applicationId;
   private gov.dhs.fema.ndgrants_rules.model.ApplicableFormType applicableFormType;

   public ApplicationFormInstance()
   {
   }

   public java.lang.Long getApplicationId()
   {
      return this.applicationId;
   }

   public void setApplicationId(java.lang.Long applicationId)
   {
      this.applicationId = applicationId;
   }

   public gov.dhs.fema.ndgrants_rules.model.ApplicableFormType getApplicableFormType()
   {
      return this.applicableFormType;
   }

   public void setApplicableFormType(
         gov.dhs.fema.ndgrants_rules.model.ApplicableFormType applicableFormType)
   {
      this.applicableFormType = applicableFormType;
   }

   public ApplicationFormInstance(
         java.lang.Long applicationId,
         gov.dhs.fema.ndgrants_rules.model.ApplicableFormType applicableFormType)
   {
      this.applicationId = applicationId;
      this.applicableFormType = applicableFormType;
   }

}