package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Application implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long applicationId;
   private java.lang.String applicationNo;
   private gov.dhs.fema.ndgrants_rules.model.AppStatus appStatus;
   private gov.dhs.fema.ndgrants_rules.model.FundingOpportunity fundingOpportunity;
   private gov.dhs.fema.ndgrants_rules.model.Organization organization;
   private gov.dhs.fema.ndgrants_rules.model.ApplicationType applicationType;
   private gov.dhs.fema.ndgrants_rules.model.AppSubmissionType appSubmissionType;
   private gov.dhs.fema.ndgrants_rules.model.ApplicantType applicantType;
   private java.lang.String applicantTypeOther;
   private java.util.Date submissionDate;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.ExternalAdminContact> contacts;
   private gov.dhs.fema.ndgrants_rules.model.Contact authorizedOfficialChangeRequestContact;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.Assurance> assurances;
   private gov.dhs.fema.ndgrants_rules.model.SflllInstance sflllInstance;
   private boolean statusNotificationSent;
   private java.util.Date dateTimeLastUpdated;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.ApplicationFormInstance> appFormInstances;
   private gov.dhs.fema.ndgrants_rules.model.SF424Information sf424Information;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424ABudget> sf424ABudgets;
   private gov.dhs.fema.ndgrants_rules.model.SF424CBudget sf424CBudgets;
   private gov.dhs.fema.ndgrants_rules.model.ForecastedCashNeeds forecastedCashNeeds;
   private java.lang.Boolean ndgrantsassoc;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.SubApplicant> subApplicants;
   private java.math.BigDecimal grantWritingFee;
   private java.math.BigDecimal applicationPercentageComplete;

   public Application()
   {
   }

   public java.lang.Long getApplicationId()
   {
      return this.applicationId;
   }

   public void setApplicationId(java.lang.Long applicationId)
   {
      this.applicationId = applicationId;
   }

   public java.lang.String getApplicationNo()
   {
      return this.applicationNo;
   }

   public void setApplicationNo(java.lang.String applicationNo)
   {
      this.applicationNo = applicationNo;
   }

   public gov.dhs.fema.ndgrants_rules.model.AppStatus getAppStatus()
   {
      return this.appStatus;
   }

   public void setAppStatus(
         gov.dhs.fema.ndgrants_rules.model.AppStatus appStatus)
   {
      this.appStatus = appStatus;
   }

   public gov.dhs.fema.ndgrants_rules.model.FundingOpportunity getFundingOpportunity()
   {
      return this.fundingOpportunity;
   }

   public void setFundingOpportunity(
         gov.dhs.fema.ndgrants_rules.model.FundingOpportunity fundingOpportunity)
   {
      this.fundingOpportunity = fundingOpportunity;
   }

   public gov.dhs.fema.ndgrants_rules.model.Organization getOrganization()
   {
      return this.organization;
   }

   public void setOrganization(
         gov.dhs.fema.ndgrants_rules.model.Organization organization)
   {
      this.organization = organization;
   }

   public gov.dhs.fema.ndgrants_rules.model.ApplicationType getApplicationType()
   {
      return this.applicationType;
   }

   public void setApplicationType(
         gov.dhs.fema.ndgrants_rules.model.ApplicationType applicationType)
   {
      this.applicationType = applicationType;
   }

   public gov.dhs.fema.ndgrants_rules.model.AppSubmissionType getAppSubmissionType()
   {
      return this.appSubmissionType;
   }

   public void setAppSubmissionType(
         gov.dhs.fema.ndgrants_rules.model.AppSubmissionType appSubmissionType)
   {
      this.appSubmissionType = appSubmissionType;
   }

   public gov.dhs.fema.ndgrants_rules.model.ApplicantType getApplicantType()
   {
      return this.applicantType;
   }

   public void setApplicantType(
         gov.dhs.fema.ndgrants_rules.model.ApplicantType applicantType)
   {
      this.applicantType = applicantType;
   }

   public java.lang.String getApplicantTypeOther()
   {
      return this.applicantTypeOther;
   }

   public void setApplicantTypeOther(java.lang.String applicantTypeOther)
   {
      this.applicantTypeOther = applicantTypeOther;
   }

   public java.util.Date getSubmissionDate()
   {
      return this.submissionDate;
   }

   public void setSubmissionDate(java.util.Date submissionDate)
   {
      this.submissionDate = submissionDate;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.ExternalAdminContact> getContacts()
   {
      return this.contacts;
   }

   public void setContacts(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.ExternalAdminContact> contacts)
   {
      this.contacts = contacts;
   }

   public gov.dhs.fema.ndgrants_rules.model.Contact getAuthorizedOfficialChangeRequestContact()
   {
      return this.authorizedOfficialChangeRequestContact;
   }

   public void setAuthorizedOfficialChangeRequestContact(
         gov.dhs.fema.ndgrants_rules.model.Contact authorizedOfficialChangeRequestContact)
   {
      this.authorizedOfficialChangeRequestContact = authorizedOfficialChangeRequestContact;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.Assurance> getAssurances()
   {
      return this.assurances;
   }

   public void setAssurances(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Assurance> assurances)
   {
      this.assurances = assurances;
   }

   public gov.dhs.fema.ndgrants_rules.model.SflllInstance getSflllInstance()
   {
      return this.sflllInstance;
   }

   public void setSflllInstance(
         gov.dhs.fema.ndgrants_rules.model.SflllInstance sflllInstance)
   {
      this.sflllInstance = sflllInstance;
   }

   public boolean isStatusNotificationSent()
   {
      return this.statusNotificationSent;
   }

   public void setStatusNotificationSent(boolean statusNotificationSent)
   {
      this.statusNotificationSent = statusNotificationSent;
   }

   public java.util.Date getDateTimeLastUpdated()
   {
      return this.dateTimeLastUpdated;
   }

   public void setDateTimeLastUpdated(java.util.Date dateTimeLastUpdated)
   {
      this.dateTimeLastUpdated = dateTimeLastUpdated;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.ApplicationFormInstance> getAppFormInstances()
   {
      return this.appFormInstances;
   }

   public void setAppFormInstances(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.ApplicationFormInstance> appFormInstances)
   {
      this.appFormInstances = appFormInstances;
   }

   public gov.dhs.fema.ndgrants_rules.model.SF424Information getSf424Information()
   {
      return this.sf424Information;
   }

   public void setSf424Information(
         gov.dhs.fema.ndgrants_rules.model.SF424Information sf424Information)
   {
      this.sf424Information = sf424Information;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424ABudget> getSf424ABudgets()
   {
      return this.sf424ABudgets;
   }

   public void setSf424ABudgets(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424ABudget> sf424ABudgets)
   {
      this.sf424ABudgets = sf424ABudgets;
   }

   public gov.dhs.fema.ndgrants_rules.model.SF424CBudget getSf424CBudgets()
   {
      return this.sf424CBudgets;
   }

   public void setSf424CBudgets(
         gov.dhs.fema.ndgrants_rules.model.SF424CBudget sf424CBudgets)
   {
      this.sf424CBudgets = sf424CBudgets;
   }

   public gov.dhs.fema.ndgrants_rules.model.ForecastedCashNeeds getForecastedCashNeeds()
   {
      return this.forecastedCashNeeds;
   }

   public void setForecastedCashNeeds(
         gov.dhs.fema.ndgrants_rules.model.ForecastedCashNeeds forecastedCashNeeds)
   {
      this.forecastedCashNeeds = forecastedCashNeeds;
   }

   public java.lang.Boolean getNdgrantsassoc()
   {
      return this.ndgrantsassoc;
   }

   public void setNdgrantsassoc(java.lang.Boolean ndgrantsassoc)
   {
      this.ndgrantsassoc = ndgrantsassoc;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.SubApplicant> getSubApplicants()
   {
      return this.subApplicants;
   }

   public void setSubApplicants(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.SubApplicant> subApplicants)
   {
      this.subApplicants = subApplicants;
   }

   public java.math.BigDecimal getGrantWritingFee()
   {
      return this.grantWritingFee;
   }

   public void setGrantWritingFee(java.math.BigDecimal grantWritingFee)
   {
      this.grantWritingFee = grantWritingFee;
   }

   public java.math.BigDecimal getApplicationPercentageComplete()
   {
      return this.applicationPercentageComplete;
   }

   public void setApplicationPercentageComplete(
         java.math.BigDecimal applicationPercentageComplete)
   {
      this.applicationPercentageComplete = applicationPercentageComplete;
   }

   public Application(
         java.lang.Long applicationId,
         java.lang.String applicationNo,
         gov.dhs.fema.ndgrants_rules.model.AppStatus appStatus,
         gov.dhs.fema.ndgrants_rules.model.FundingOpportunity fundingOpportunity,
         gov.dhs.fema.ndgrants_rules.model.Organization organization,
         gov.dhs.fema.ndgrants_rules.model.ApplicationType applicationType,
         gov.dhs.fema.ndgrants_rules.model.AppSubmissionType appSubmissionType,
         gov.dhs.fema.ndgrants_rules.model.ApplicantType applicantType,
         java.lang.String applicantTypeOther,
         java.util.Date submissionDate,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.ExternalAdminContact> contacts,
         gov.dhs.fema.ndgrants_rules.model.Contact authorizedOfficialChangeRequestContact,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Assurance> assurances,
         gov.dhs.fema.ndgrants_rules.model.SflllInstance sflllInstance,
         boolean statusNotificationSent,
         java.util.Date dateTimeLastUpdated,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.ApplicationFormInstance> appFormInstances,
         gov.dhs.fema.ndgrants_rules.model.SF424Information sf424Information,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424ABudget> sf424ABudgets,
         gov.dhs.fema.ndgrants_rules.model.SF424CBudget sf424CBudgets,
         gov.dhs.fema.ndgrants_rules.model.ForecastedCashNeeds forecastedCashNeeds,
         java.lang.Boolean ndgrantsassoc,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.SubApplicant> subApplicants,
         java.math.BigDecimal grantWritingFee,
         java.math.BigDecimal applicationPercentageComplete)
   {
      this.applicationId = applicationId;
      this.applicationNo = applicationNo;
      this.appStatus = appStatus;
      this.fundingOpportunity = fundingOpportunity;
      this.organization = organization;
      this.applicationType = applicationType;
      this.appSubmissionType = appSubmissionType;
      this.applicantType = applicantType;
      this.applicantTypeOther = applicantTypeOther;
      this.submissionDate = submissionDate;
      this.contacts = contacts;
      this.authorizedOfficialChangeRequestContact = authorizedOfficialChangeRequestContact;
      this.assurances = assurances;
      this.sflllInstance = sflllInstance;
      this.statusNotificationSent = statusNotificationSent;
      this.dateTimeLastUpdated = dateTimeLastUpdated;
      this.appFormInstances = appFormInstances;
      this.sf424Information = sf424Information;
      this.sf424ABudgets = sf424ABudgets;
      this.sf424CBudgets = sf424CBudgets;
      this.forecastedCashNeeds = forecastedCashNeeds;
      this.ndgrantsassoc = ndgrantsassoc;
      this.subApplicants = subApplicants;
      this.grantWritingFee = grantWritingFee;
      this.applicationPercentageComplete = applicationPercentageComplete;
   }

}