package gov.dhs.fema.ndgrants_rules.model;

import gov.dhs.fema.ndgrants_rules.model.EGPTypeDef;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ApplicantType extends EGPTypeDef implements java.io.Serializable
{

   static final long serialVersionUID = 1L;
   
   public static final ApplicantType NUM_00 = new ApplicantType(1);
   public static final ApplicantType NUM_01 = new ApplicantType(2);
   public static final ApplicantType NUM_02 = new ApplicantType(3);
   public static final ApplicantType NUM_04 = new ApplicantType(4);
   public static final ApplicantType NUM_05 = new ApplicantType(5);
   public static final ApplicantType NUM_06 = new ApplicantType(6);
   public static final ApplicantType NUM_07 = new ApplicantType(7);
   public static final ApplicantType NUM_08 = new ApplicantType(8);
   public static final ApplicantType NUM_11 = new ApplicantType(9);
   public static final ApplicantType NUM_12 = new ApplicantType(10);
   public static final ApplicantType NUM_13 = new ApplicantType(11);
   public static final ApplicantType NUM_20 = new ApplicantType(12);
   public static final ApplicantType NUM_21 = new ApplicantType(13);
   public static final ApplicantType NUM_22 = new ApplicantType(14);
   public static final ApplicantType NUM_23 = new ApplicantType(15);
   public static final ApplicantType NUM_25 = new ApplicantType(16);
   public static final ApplicantType NUM_99 = new ApplicantType(17);
   public static final ApplicantType OPH = new ApplicantType(18);

   public ApplicantType()
   {
   }
   
   ApplicantType(long id){
       super(id);
   }

}