package gov.dhs.fema.ndgrants_rules.model;

import gov.dhs.fema.ndgrants_rules.model.EGPTypeDef;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ApplicableFormType extends EGPTypeDef implements java.io.Serializable
{

   static final long serialVersionUID = 1L;
   
   public static final ApplicableFormType DIRECT_APPLICANT = new ApplicableFormType(1);
   public static final ApplicableFormType SUB_APPLICANT = new ApplicableFormType(2);
   public static final ApplicableFormType BOTH = new ApplicableFormType(3);

   public ApplicableFormType()
   {
   }
   
   ApplicableFormType(long id){
       super(id);
   }

}