package gov.dhs.fema.ndgrants_rules.model;

import gov.dhs.fema.ndgrants_rules.model.EGPTypeDef;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ApplicationType extends EGPTypeDef implements java.io.Serializable
{

   static final long serialVersionUID = 1L;
   
   public static final ApplicationType NEW = new ApplicationType(1);
   public static final ApplicationType CONTINUATION = new ApplicationType(2);

   public ApplicationType()
   {
   }
   
   ApplicationType(long id){
       super(id);
   }

}