package gov.dhs.fema.ndgrants_rules.model;

import gov.dhs.fema.ndgrants_rules.model.EGPTypeDef;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AwardStatus extends EGPTypeDef implements java.io.Serializable
{

   static final long serialVersionUID = 1L;
   
   public static final AwardStatus PENDING_SUBMISSION = new AwardStatus(1);
   public static final AwardStatus PENDING_REVIEW = new AwardStatus(2);
   public static final AwardStatus DECLINED = new AwardStatus(3);
   public static final AwardStatus APPROVED = new AwardStatus(4);
   public static final AwardStatus ACCEPTED = new AwardStatus(5);
   public static final AwardStatus PENDING_CONGRESSIONAL_REVIEW = new AwardStatus(6);

   public AwardStatus()
   {
       super();
   }
   
   AwardStatus(long id)
   {
       super(id);
   }

}