package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AwardRecommendation implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long awardRecommendationId;
   private gov.dhs.fema.ndgrants_rules.model.Application application;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> terms;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424ABudget> sf424ABudgets;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424CBudget> sf424CBudgets;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.CommitmentAmount> commitmentAmounts;
   private java.math.BigDecimal totalCommitments;
   private java.lang.String strtotalCommitments;

   public AwardRecommendation()
   {
   }

   public java.lang.Long getAwardRecommendationId()
   {
      return this.awardRecommendationId;
   }

   public void setAwardRecommendationId(java.lang.Long awardRecommendationId)
   {
      this.awardRecommendationId = awardRecommendationId;
   }

   public gov.dhs.fema.ndgrants_rules.model.Application getApplication()
   {
      return this.application;
   }

   public void setApplication(
         gov.dhs.fema.ndgrants_rules.model.Application application)
   {
      this.application = application;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> getTerms()
   {
      return this.terms;
   }

   public void setTerms(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> terms)
   {
      this.terms = terms;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424ABudget> getSf424ABudgets()
   {
      return this.sf424ABudgets;
   }

   public void setSf424ABudgets(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424ABudget> sf424ABudgets)
   {
      this.sf424ABudgets = sf424ABudgets;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424CBudget> getSf424CBudgets()
   {
      return this.sf424CBudgets;
   }

   public void setSf424CBudgets(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424CBudget> sf424CBudgets)
   {
      this.sf424CBudgets = sf424CBudgets;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.CommitmentAmount> getCommitmentAmounts()
   {
      return this.commitmentAmounts;
   }

   public void setCommitmentAmounts(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.CommitmentAmount> commitmentAmounts)
   {
      this.commitmentAmounts = commitmentAmounts;
   }

   public java.math.BigDecimal getTotalCommitments()
   {
      return this.totalCommitments;
   }

   public void setTotalCommitments(java.math.BigDecimal totalCommitments)
   {
      this.totalCommitments = totalCommitments;
   }

   public java.lang.String getStrtotalCommitments()
   {
      return this.strtotalCommitments;
   }

   public void setStrtotalCommitments(java.lang.String strtotalCommitments)
   {
      this.strtotalCommitments = strtotalCommitments;
   }

   public AwardRecommendation(
         java.lang.Long awardRecommendationId,
         gov.dhs.fema.ndgrants_rules.model.Application application,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> terms,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424ABudget> sf424ABudgets,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424CBudget> sf424CBudgets,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.CommitmentAmount> commitmentAmounts,
         java.math.BigDecimal totalCommitments,
         java.lang.String strtotalCommitments)
   {
      this.awardRecommendationId = awardRecommendationId;
      this.application = application;
      this.terms = terms;
      this.sf424ABudgets = sf424ABudgets;
      this.sf424CBudgets = sf424CBudgets;
      this.commitmentAmounts = commitmentAmounts;
      this.totalCommitments = totalCommitments;
      this.strtotalCommitments = strtotalCommitments;
   }

}