package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Award implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long awardId;
   private gov.dhs.fema.ndgrants_rules.model.Grant grant;
   private gov.dhs.fema.ndgrants_rules.model.Application application;
   private java.lang.String awardNumber;
   private gov.dhs.fema.ndgrants_rules.model.AwardStatus awardStatus;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> terms;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424ABudget> sf424ABudgets;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424CBudget> sf424CBudgets;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.PackageComponent> packageComponents;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.CommitmentAmount> awardCommitments;
   private gov.dhs.fema.ndgrants_rules.model.Vendor vendor;
   private java.lang.Boolean vendorDunsToChangeOrgDunsFlag;
   private gov.dhs.fema.ndgrants_rules.model.BudgetAndPop budgetAndPop;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.Signature> signatures;
   private java.util.Date effectiveDate;
   private java.math.BigDecimal conditionalFederal;
   private java.math.BigDecimal conditionalNonFederal;
   private java.math.BigDecimal totalCommitments;
   private gov.dhs.fema.ndgrants_rules.model.Obligation obligation;
   private java.math.BigDecimal totalConditionalProjectCost;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.FormOutcome> formOutcomes;
   private java.lang.Boolean threeDayRequired;
   private java.lang.Boolean threeDayCert;
   private java.util.Date threeDayCertDate;
   private java.lang.Boolean fiveDayRequired;
   private java.lang.Boolean fiveDayCert;
   private java.util.Date fiveDayCertDate;
   private java.lang.Long awardOfferReviewTaskId;
   private java.lang.String currentAoUserName;

   public Award()
   {
   }

   public java.lang.Long getAwardId()
   {
      return this.awardId;
   }

   public void setAwardId(java.lang.Long awardId)
   {
      this.awardId = awardId;
   }

   public gov.dhs.fema.ndgrants_rules.model.Grant getGrant()
   {
      return this.grant;
   }

   public void setGrant(gov.dhs.fema.ndgrants_rules.model.Grant grant)
   {
      this.grant = grant;
   }

   public gov.dhs.fema.ndgrants_rules.model.Application getApplication()
   {
      return this.application;
   }

   public void setApplication(
         gov.dhs.fema.ndgrants_rules.model.Application application)
   {
      this.application = application;
   }

   public java.lang.String getAwardNumber()
   {
      return this.awardNumber;
   }

   public void setAwardNumber(java.lang.String awardNumber)
   {
      this.awardNumber = awardNumber;
   }

   public gov.dhs.fema.ndgrants_rules.model.AwardStatus getAwardStatus()
   {
      return this.awardStatus;
   }

   public void setAwardStatus(
         gov.dhs.fema.ndgrants_rules.model.AwardStatus awardStatus)
   {
      this.awardStatus = awardStatus;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> getTerms()
   {
      return this.terms;
   }

   public void setTerms(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> terms)
   {
      this.terms = terms;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424ABudget> getSf424ABudgets()
   {
      return this.sf424ABudgets;
   }

   public void setSf424ABudgets(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424ABudget> sf424ABudgets)
   {
      this.sf424ABudgets = sf424ABudgets;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424CBudget> getSf424CBudgets()
   {
      return this.sf424CBudgets;
   }

   public void setSf424CBudgets(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424CBudget> sf424CBudgets)
   {
      this.sf424CBudgets = sf424CBudgets;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.PackageComponent> getPackageComponents()
   {
      return this.packageComponents;
   }

   public void setPackageComponents(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.PackageComponent> packageComponents)
   {
      this.packageComponents = packageComponents;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.CommitmentAmount> getAwardCommitments()
   {
      return this.awardCommitments;
   }

   public void setAwardCommitments(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.CommitmentAmount> awardCommitments)
   {
      this.awardCommitments = awardCommitments;
   }

   public gov.dhs.fema.ndgrants_rules.model.Vendor getVendor()
   {
      return this.vendor;
   }

   public void setVendor(gov.dhs.fema.ndgrants_rules.model.Vendor vendor)
   {
      this.vendor = vendor;
   }

   public java.lang.Boolean getVendorDunsToChangeOrgDunsFlag()
   {
      return this.vendorDunsToChangeOrgDunsFlag;
   }

   public void setVendorDunsToChangeOrgDunsFlag(
         java.lang.Boolean vendorDunsToChangeOrgDunsFlag)
   {
      this.vendorDunsToChangeOrgDunsFlag = vendorDunsToChangeOrgDunsFlag;
   }

   public gov.dhs.fema.ndgrants_rules.model.BudgetAndPop getBudgetAndPop()
   {
      return this.budgetAndPop;
   }

   public void setBudgetAndPop(
         gov.dhs.fema.ndgrants_rules.model.BudgetAndPop budgetAndPop)
   {
      this.budgetAndPop = budgetAndPop;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.Signature> getSignatures()
   {
      return this.signatures;
   }

   public void setSignatures(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Signature> signatures)
   {
      this.signatures = signatures;
   }

   public java.util.Date getEffectiveDate()
   {
      return this.effectiveDate;
   }

   public void setEffectiveDate(java.util.Date effectiveDate)
   {
      this.effectiveDate = effectiveDate;
   }

   public java.math.BigDecimal getConditionalFederal()
   {
      return this.conditionalFederal;
   }

   public void setConditionalFederal(java.math.BigDecimal conditionalFederal)
   {
      this.conditionalFederal = conditionalFederal;
   }

   public java.math.BigDecimal getConditionalNonFederal()
   {
      return this.conditionalNonFederal;
   }

   public void setConditionalNonFederal(
         java.math.BigDecimal conditionalNonFederal)
   {
      this.conditionalNonFederal = conditionalNonFederal;
   }

   public java.math.BigDecimal getTotalCommitments()
   {
      return this.totalCommitments;
   }

   public void setTotalCommitments(java.math.BigDecimal totalCommitments)
   {
      this.totalCommitments = totalCommitments;
   }

   public gov.dhs.fema.ndgrants_rules.model.Obligation getObligation()
   {
      return this.obligation;
   }

   public void setObligation(
         gov.dhs.fema.ndgrants_rules.model.Obligation obligation)
   {
      this.obligation = obligation;
   }

   public java.math.BigDecimal getTotalConditionalProjectCost()
   {
      return this.totalConditionalProjectCost;
   }

   public void setTotalConditionalProjectCost(
         java.math.BigDecimal totalConditionalProjectCost)
   {
      this.totalConditionalProjectCost = totalConditionalProjectCost;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.FormOutcome> getFormOutcomes()
   {
      return this.formOutcomes;
   }

   public void setFormOutcomes(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.FormOutcome> formOutcomes)
   {
      this.formOutcomes = formOutcomes;
   }

   public java.lang.Boolean getThreeDayRequired()
   {
      return this.threeDayRequired;
   }

   public void setThreeDayRequired(java.lang.Boolean threeDayRequired)
   {
      this.threeDayRequired = threeDayRequired;
   }

   public java.lang.Boolean getThreeDayCert()
   {
      return this.threeDayCert;
   }

   public void setThreeDayCert(java.lang.Boolean threeDayCert)
   {
      this.threeDayCert = threeDayCert;
   }

   public java.util.Date getThreeDayCertDate()
   {
      return this.threeDayCertDate;
   }

   public void setThreeDayCertDate(java.util.Date threeDayCertDate)
   {
      this.threeDayCertDate = threeDayCertDate;
   }

   public java.lang.Boolean getFiveDayRequired()
   {
      return this.fiveDayRequired;
   }

   public void setFiveDayRequired(java.lang.Boolean fiveDayRequired)
   {
      this.fiveDayRequired = fiveDayRequired;
   }

   public java.lang.Boolean getFiveDayCert()
   {
      return this.fiveDayCert;
   }

   public void setFiveDayCert(java.lang.Boolean fiveDayCert)
   {
      this.fiveDayCert = fiveDayCert;
   }

   public java.util.Date getFiveDayCertDate()
   {
      return this.fiveDayCertDate;
   }

   public void setFiveDayCertDate(java.util.Date fiveDayCertDate)
   {
      this.fiveDayCertDate = fiveDayCertDate;
   }

   public java.lang.Long getAwardOfferReviewTaskId()
   {
      return this.awardOfferReviewTaskId;
   }

   public void setAwardOfferReviewTaskId(java.lang.Long awardOfferReviewTaskId)
   {
      this.awardOfferReviewTaskId = awardOfferReviewTaskId;
   }

   public java.lang.String getCurrentAoUserName()
   {
      return this.currentAoUserName;
   }

   public void setCurrentAoUserName(java.lang.String currentAoUserName)
   {
      this.currentAoUserName = currentAoUserName;
   }

   public Award(
         java.lang.Long awardId,
         gov.dhs.fema.ndgrants_rules.model.Grant grant,
         gov.dhs.fema.ndgrants_rules.model.Application application,
         java.lang.String awardNumber,
         gov.dhs.fema.ndgrants_rules.model.AwardStatus awardStatus,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> terms,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424ABudget> sf424ABudgets,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424CBudget> sf424CBudgets,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.PackageComponent> packageComponents,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.CommitmentAmount> awardCommitments,
         gov.dhs.fema.ndgrants_rules.model.Vendor vendor,
         java.lang.Boolean vendorDunsToChangeOrgDunsFlag,
         gov.dhs.fema.ndgrants_rules.model.BudgetAndPop budgetAndPop,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Signature> signatures,
         java.util.Date effectiveDate,
         java.math.BigDecimal conditionalFederal,
         java.math.BigDecimal conditionalNonFederal,
         java.math.BigDecimal totalCommitments,
         gov.dhs.fema.ndgrants_rules.model.Obligation obligation,
         java.math.BigDecimal totalConditionalProjectCost,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.FormOutcome> formOutcomes,
         java.lang.Boolean threeDayRequired, java.lang.Boolean threeDayCert,
         java.util.Date threeDayCertDate, java.lang.Boolean fiveDayRequired,
         java.lang.Boolean fiveDayCert, java.util.Date fiveDayCertDate,
         java.lang.Long awardOfferReviewTaskId,
         java.lang.String currentAoUserName)
   {
      this.awardId = awardId;
      this.grant = grant;
      this.application = application;
      this.awardNumber = awardNumber;
      this.awardStatus = awardStatus;
      this.terms = terms;
      this.sf424ABudgets = sf424ABudgets;
      this.sf424CBudgets = sf424CBudgets;
      this.packageComponents = packageComponents;
      this.awardCommitments = awardCommitments;
      this.vendor = vendor;
      this.vendorDunsToChangeOrgDunsFlag = vendorDunsToChangeOrgDunsFlag;
      this.budgetAndPop = budgetAndPop;
      this.signatures = signatures;
      this.effectiveDate = effectiveDate;
      this.conditionalFederal = conditionalFederal;
      this.conditionalNonFederal = conditionalNonFederal;
      this.totalCommitments = totalCommitments;
      this.obligation = obligation;
      this.totalConditionalProjectCost = totalConditionalProjectCost;
      this.formOutcomes = formOutcomes;
      this.threeDayRequired = threeDayRequired;
      this.threeDayCert = threeDayCert;
      this.threeDayCertDate = threeDayCertDate;
      this.fiveDayRequired = fiveDayRequired;
      this.fiveDayCert = fiveDayCert;
      this.fiveDayCertDate = fiveDayCertDate;
      this.awardOfferReviewTaskId = awardOfferReviewTaskId;
      this.currentAoUserName = currentAoUserName;
   }

}