package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BpmProcess implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long processId;
   private java.lang.String displayName;
   private java.lang.String bpmApplicationId;
   private java.lang.String bpmApplicationName;
   private java.lang.String bpmBpdId;
   private java.lang.String bpmSnapshotId;
   private java.lang.String bpmSnapshotName;
   private java.lang.Integer numActive;
   private boolean current;
   private gov.dhs.fema.ndgrants_rules.model.Module module;

   public BpmProcess()
   {
   }

   public java.lang.Long getProcessId()
   {
      return this.processId;
   }

   public void setProcessId(java.lang.Long processId)
   {
      this.processId = processId;
   }

   public java.lang.String getDisplayName()
   {
      return this.displayName;
   }

   public void setDisplayName(java.lang.String displayName)
   {
      this.displayName = displayName;
   }

   public java.lang.String getBpmApplicationId()
   {
      return this.bpmApplicationId;
   }

   public void setBpmApplicationId(java.lang.String bpmApplicationId)
   {
      this.bpmApplicationId = bpmApplicationId;
   }

   public java.lang.String getBpmApplicationName()
   {
      return this.bpmApplicationName;
   }

   public void setBpmApplicationName(java.lang.String bpmApplicationName)
   {
      this.bpmApplicationName = bpmApplicationName;
   }

   public java.lang.String getBpmBpdId()
   {
      return this.bpmBpdId;
   }

   public void setBpmBpdId(java.lang.String bpmBpdId)
   {
      this.bpmBpdId = bpmBpdId;
   }

   public java.lang.String getBpmSnapshotId()
   {
      return this.bpmSnapshotId;
   }

   public void setBpmSnapshotId(java.lang.String bpmSnapshotId)
   {
      this.bpmSnapshotId = bpmSnapshotId;
   }

   public java.lang.String getBpmSnapshotName()
   {
      return this.bpmSnapshotName;
   }

   public void setBpmSnapshotName(java.lang.String bpmSnapshotName)
   {
      this.bpmSnapshotName = bpmSnapshotName;
   }

   public java.lang.Integer getNumActive()
   {
      return this.numActive;
   }

   public void setNumActive(java.lang.Integer numActive)
   {
      this.numActive = numActive;
   }

   public boolean isCurrent()
   {
      return this.current;
   }

   public void setCurrent(boolean current)
   {
      this.current = current;
   }

   public gov.dhs.fema.ndgrants_rules.model.Module getModule()
   {
      return this.module;
   }

   public void setModule(gov.dhs.fema.ndgrants_rules.model.Module module)
   {
      this.module = module;
   }

   public BpmProcess(java.lang.Long processId, java.lang.String displayName,
         java.lang.String bpmApplicationId,
         java.lang.String bpmApplicationName, java.lang.String bpmBpdId,
         java.lang.String bpmSnapshotId, java.lang.String bpmSnapshotName,
         java.lang.Integer numActive, boolean current,
         gov.dhs.fema.ndgrants_rules.model.Module module)
   {
      this.processId = processId;
      this.displayName = displayName;
      this.bpmApplicationId = bpmApplicationId;
      this.bpmApplicationName = bpmApplicationName;
      this.bpmBpdId = bpmBpdId;
      this.bpmSnapshotId = bpmSnapshotId;
      this.bpmSnapshotName = bpmSnapshotName;
      this.numActive = numActive;
      this.current = current;
      this.module = module;
   }

}