package gov.dhs.fema.ndgrants_rules.model;

import gov.dhs.fema.ndgrants_rules.model.EGPTypeDef;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BudgetClass extends EGPTypeDef implements java.io.Serializable
{

   static final long serialVersionUID = 1L;
   
    public static final BudgetClass PERSONNEL = new BudgetClass(1,"1", "Personnel");
	public static final BudgetClass FRINGE_BENEFITS = new BudgetClass(2,"2", "Fringe Benefits");
	public static final BudgetClass TRAVEL = new BudgetClass(3,"3", "Travel");
	public static final BudgetClass EQUIPMENT = new BudgetClass(4,"4", "Equipment");
	public static final BudgetClass SUPPLIES = new BudgetClass(5,"5", "Supplies");
	public static final BudgetClass CONTRACTUAL = new BudgetClass(6,"6", "Contractual");
	public static final BudgetClass CONSTRUCTION = new BudgetClass(7,"7", "Construction");
	public static final BudgetClass INDIRECT_CHARGES = new BudgetClass(8,"8", "Indirect Charges");
	public static final BudgetClass OTHER = new BudgetClass(9,"9", "Other");
	public static final BudgetClass UNALLOCATED_CHARGES = new BudgetClass(10,"10", "Unallocated Charges");
	public static final BudgetClass PROGRAM_INCOME = new BudgetClass(11,"11", "Program Income");

   private java.lang.String name;
   private java.lang.String code;

   public BudgetClass()
   {
   }

   public BudgetClass(long id)
   {
      super(id);
   }

   public BudgetClass(long id, String code, String name)
   {
      super(id);
      this.code = code;
      this.name = name;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getCode()
   {
      return this.code;
   }

   public void setCode(java.lang.String code)
   {
      this.code = code;
   }

   public BudgetClass(java.lang.String name, java.lang.String code)
   {
      this.name = name;
      this.code = code;
   }

}