package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BudgetAndPop implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long budgetAndPopId;
   private java.util.Date budgetStartDate;
   private java.util.Date budgetEndDate;
   private java.util.Date popStartDate;
   private java.util.Date popEndDate;

   public BudgetAndPop()
   {
   }

   public java.lang.Long getBudgetAndPopId()
   {
      return this.budgetAndPopId;
   }

   public void setBudgetAndPopId(java.lang.Long budgetAndPopId)
   {
      this.budgetAndPopId = budgetAndPopId;
   }

   public java.util.Date getBudgetStartDate()
   {
      return this.budgetStartDate;
   }

   public void setBudgetStartDate(java.util.Date budgetStartDate)
   {
      this.budgetStartDate = budgetStartDate;
   }

   public java.util.Date getBudgetEndDate()
   {
      return this.budgetEndDate;
   }

   public void setBudgetEndDate(java.util.Date budgetEndDate)
   {
      this.budgetEndDate = budgetEndDate;
   }

   public java.util.Date getPopStartDate()
   {
      return this.popStartDate;
   }

   public void setPopStartDate(java.util.Date popStartDate)
   {
      this.popStartDate = popStartDate;
   }

   public java.util.Date getPopEndDate()
   {
      return this.popEndDate;
   }

   public void setPopEndDate(java.util.Date popEndDate)
   {
      this.popEndDate = popEndDate;
   }

   public BudgetAndPop(java.lang.Long budgetAndPopId,
         java.util.Date budgetStartDate, java.util.Date budgetEndDate,
         java.util.Date popStartDate, java.util.Date popEndDate)
   {
      this.budgetAndPopId = budgetAndPopId;
      this.budgetStartDate = budgetStartDate;
      this.budgetEndDate = budgetEndDate;
      this.popStartDate = popStartDate;
      this.popEndDate = popEndDate;
   }

}