package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CommitmentAmount implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private gov.dhs.fema.ndgrants_rules.model.Commitment commitment;
   private java.math.BigDecimal amount;
   private java.math.BigDecimal previousAmount;
   private java.math.BigDecimal changedAmount;

   public CommitmentAmount()
   {
   }

   public gov.dhs.fema.ndgrants_rules.model.Commitment getCommitment()
   {
      return this.commitment;
   }

   public void setCommitment(
         gov.dhs.fema.ndgrants_rules.model.Commitment commitment)
   {
      this.commitment = commitment;
   }

   public java.math.BigDecimal getAmount()
   {
      return this.amount;
   }

   public void setAmount(java.math.BigDecimal amount)
   {
      this.amount = amount;
   }

   public java.math.BigDecimal getPreviousAmount()
   {
      return this.previousAmount;
   }

   public void setPreviousAmount(java.math.BigDecimal previousAmount)
   {
      this.previousAmount = previousAmount;
   }

   public java.math.BigDecimal getChangedAmount()
   {
      return this.changedAmount;
   }

   public void setChangedAmount(java.math.BigDecimal changedAmount)
   {
      this.changedAmount = changedAmount;
   }

   public CommitmentAmount(
         gov.dhs.fema.ndgrants_rules.model.Commitment commitment,
         java.math.BigDecimal amount, java.math.BigDecimal previousAmount,
         java.math.BigDecimal changedAmount)
   {
      this.commitment = commitment;
      this.amount = amount;
      this.previousAmount = previousAmount;
      this.changedAmount = changedAmount;
   }

}