package gov.dhs.fema.ndgrants_rules.model;

import gov.dhs.fema.ndgrants_rules.model.EGPTypeDef;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CommitmentDocumentType extends EGPTypeDef implements java.io.Serializable
{

   static final long serialVersionUID = 1L;
   
   public static final CommitmentDocumentType COMMIT = new CommitmentDocumentType(1);
   public static final CommitmentDocumentType FF40_1 = new CommitmentDocumentType(2);
   public static final CommitmentDocumentType FF40_27 = new CommitmentDocumentType(3);
   public static final CommitmentDocumentType FF60_1 = new CommitmentDocumentType(4);
   public static final CommitmentDocumentType FF60_3 = new CommitmentDocumentType(5);
   public static final CommitmentDocumentType FF60_1A = new CommitmentDocumentType(6);
   public static final CommitmentDocumentType PR = new CommitmentDocumentType(7);

   public CommitmentDocumentType()
   {
   }
   
   CommitmentDocumentType(long id){
       super(id);
   }

}