package gov.dhs.fema.ndgrants_rules.model;

import gov.dhs.fema.ndgrants_rules.model.EGPCodedTypeDef;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CommitmentDocumentClass extends EGPCodedTypeDef implements java.io.Serializable
{

   static final long serialVersionUID = 1L;
   
   public static final CommitmentDocumentClass GRANT = new CommitmentDocumentClass(1, "G");
   public static final CommitmentDocumentClass VENDOR = new CommitmentDocumentClass(2, "V");
   public static final CommitmentDocumentClass TRAVEL_AUTH = new CommitmentDocumentClass(3, "T");


   public CommitmentDocumentClass()
   {
   }
   
   CommitmentDocumentClass(long id, String code){
       super(id, code);
   }

}