package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CongressionalDistrict implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long congressionalDistrictId;
   private java.lang.String districtCode;
   private java.lang.String description;
   private gov.dhs.fema.ndgrants_rules.model.State state;

   public CongressionalDistrict()
   {
   }

   public java.lang.Long getCongressionalDistrictId()
   {
      return this.congressionalDistrictId;
   }

   public void setCongressionalDistrictId(
         java.lang.Long congressionalDistrictId)
   {
      this.congressionalDistrictId = congressionalDistrictId;
   }

   public java.lang.String getDistrictCode()
   {
      return this.districtCode;
   }

   public void setDistrictCode(java.lang.String districtCode)
   {
      this.districtCode = districtCode;
   }

   public java.lang.String getDescription()
   {
      return this.description;
   }

   public void setDescription(java.lang.String description)
   {
      this.description = description;
   }

   public gov.dhs.fema.ndgrants_rules.model.State getState()
   {
      return this.state;
   }

   public void setState(gov.dhs.fema.ndgrants_rules.model.State state)
   {
      this.state = state;
   }

   public CongressionalDistrict(java.lang.Long congressionalDistrictId,
         java.lang.String districtCode, java.lang.String description,
         gov.dhs.fema.ndgrants_rules.model.State state)
   {
      this.congressionalDistrictId = congressionalDistrictId;
      this.districtCode = districtCode;
      this.description = description;
      this.state = state;
   }

}