package gov.dhs.fema.ndgrants_rules.model;

import gov.dhs.fema.ndgrants_rules.model.EGPTypeDef;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DocumentType extends EGPTypeDef implements java.io.Serializable
{

   static final long serialVersionUID = 1L;
   
   public static final DocumentType GENERAL = new DocumentType(1);
   public static final DocumentType ADMIN = new DocumentType(2);
   public static final DocumentType GENERATED_NOTIFICATION = new DocumentType(3);

   public DocumentType()
   {
   }
   
   DocumentType(long id){
       super(id);
   }

}