package gov.dhs.fema.ndgrants_rules.model;

import gov.dhs.fema.ndgrants_rules.model.EGPTypeDef;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DocumentStatus extends EGPTypeDef implements java.io.Serializable
{

   static final long serialVersionUID = 1L;
   
   public static final DocumentStatus ACTIVE = new DocumentStatus(1);
   public static final DocumentStatus ARCHIVED = new DocumentStatus(2);
   public static final DocumentStatus DELETED = new DocumentStatus(3);

   public DocumentStatus()
   {
   }
   
   DocumentStatus(long id){
       super(id);
   }

}