package gov.dhs.fema.ndgrants_rules.model;

import gov.dhs.fema.ndgrants_rules.model.EGPTypeDef;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class EGPCodedTypeDef extends EGPTypeDef implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String code;

   public EGPCodedTypeDef()
   {
   }

   public java.lang.String getCode()
   {
      return this.code;
   }

   public void setCode(java.lang.String code)
   {
      this.code = code;
   }

   public EGPCodedTypeDef(java.lang.String code)
   {
      this.code = code;
   }

}