package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class EGPTypeDef implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private long id;
   private java.lang.String displayName;
   private boolean active;
   private long order;

   public EGPTypeDef()
   {
   }

   public long getId()
   {
      return this.id;
   }

   public void setId(long id)
   {
      this.id = id;
   }

   public java.lang.String getDisplayName()
   {
      return this.displayName;
   }

   public void setDisplayName(java.lang.String displayName)
   {
      this.displayName = displayName;
   }

   public boolean isActive()
   {
      return this.active;
   }

   public void setActive(boolean active)
   {
      this.active = active;
   }

   public long getOrder()
   {
      return this.order;
   }

   public void setOrder(long order)
   {
      this.order = order;
   }

   public EGPTypeDef(long id, java.lang.String displayName, boolean active,
         long order)
   {
      this.id = id;
      this.displayName = displayName;
      this.active = active;
      this.order = order;
   }

}