package gov.dhs.fema.ndgrants_rules.model;

import gov.dhs.fema.ndgrants_rules.model.EGPCodedTypeDef;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class EligibleApplicantType extends EGPCodedTypeDef implements java.io.Serializable
{

   static final long serialVersionUID = 1L;
   
   	public static final EligibleApplicantType STATE_GOVERNMENT = new EligibleApplicantType(1, "00");
    public static final EligibleApplicantType COUNTY_GOVERNMENT = new EligibleApplicantType(2, "01");
    public static final EligibleApplicantType CITYOR_TOWNSHIP_GOVERNMENT = new EligibleApplicantType(3, "02");
    public static final EligibleApplicantType SPECIAL_DISTRICT_GOVERNMENT = new EligibleApplicantType(4, "04");
    public static final EligibleApplicantType INDEPENDENT_SCHOOL_DISTRICT = new EligibleApplicantType(5, "05");
    public static final EligibleApplicantType PUBLIC_STATE_CONTROLLED_INSTITUTIONOF_HIGHER_EDUCATION = new EligibleApplicantType(6, "06");
    public static final EligibleApplicantType INDIAN_NATIVE_AMERICAN_TRIBAL_GOVERNMENT_FEDERALLY_RECOGNIZED_ = new EligibleApplicantType(7, "07");
    public static final EligibleApplicantType PUBLIC_INDIAN_HOUSING_AUTHORITY = new EligibleApplicantType(8, "08");
    public static final EligibleApplicantType INDIAN_NATIVE_AMERICAN_TRIBAL_GOVERNMENT_OTHERTHAN_FEDERALLY_RECOGNIZED_ = new EligibleApplicantType(9, "11");
    public static final EligibleApplicantType NONPROFITWITH_501_C_3_IRS_STATUS_OTHERTHAN_INSTITUTIONOF_HIGHER_EDUCATION_ = new EligibleApplicantType(10, "12");
    public static final EligibleApplicantType NONPROFITWITHOUT_501_C_3_IRS_STATUS_OTHERTHAN_INSTITUTIONOF_HIGHER_EDUCATION_ = new EligibleApplicantType(11, "13");
    public static final EligibleApplicantType PRIVATE_INSTITUTIONOF_HIGHER_EDUCATION = new EligibleApplicantType(12, "20");
    public static final EligibleApplicantType INDIVIDUAL = new EligibleApplicantType(13, "21");
    public static final EligibleApplicantType FOR_PROFIT_ORGANIZATION_OTHERTHAN_SMALL_BUSINESS_ = new EligibleApplicantType(14, "22");
    public static final EligibleApplicantType SMALL_BUSINESS = new EligibleApplicantType(15, "23");
    public static final EligibleApplicantType OTHER_SPECIFY = new EligibleApplicantType(16, "25");
    public static final EligibleApplicantType UNRESTRICTED = new EligibleApplicantType(17, "99");
    public static final EligibleApplicantType PLACE_HOLDERFOR_OTHER_APPLICANT_NAME = new EligibleApplicantType(18, "OPH");


   public EligibleApplicantType()
   {
   }
   
   EligibleApplicantType(long id, String code){
       super(id, code);
   }

}