package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class EligibilityConfigItem implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long eligibilityConfigId;
   private java.lang.Long fundingOpportunityId;
   private java.lang.Long fundingStreamId;
   private java.lang.Integer appEligibleType;
   private boolean subApplicationConfig;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.ConsortiumType> consortiumTypes;

   public EligibilityConfigItem()
   {
   }

   public java.lang.Long getEligibilityConfigId()
   {
      return this.eligibilityConfigId;
   }

   public void setEligibilityConfigId(java.lang.Long eligibilityConfigId)
   {
      this.eligibilityConfigId = eligibilityConfigId;
   }

   public java.lang.Long getFundingOpportunityId()
   {
      return this.fundingOpportunityId;
   }

   public void setFundingOpportunityId(java.lang.Long fundingOpportunityId)
   {
      this.fundingOpportunityId = fundingOpportunityId;
   }

   public java.lang.Long getFundingStreamId()
   {
      return this.fundingStreamId;
   }

   public void setFundingStreamId(java.lang.Long fundingStreamId)
   {
      this.fundingStreamId = fundingStreamId;
   }

   public java.lang.Integer getAppEligibleType()
   {
      return this.appEligibleType;
   }

   public void setAppEligibleType(java.lang.Integer appEligibleType)
   {
      this.appEligibleType = appEligibleType;
   }

   public boolean isSubApplicationConfig()
   {
      return this.subApplicationConfig;
   }

   public void setSubApplicationConfig(boolean subApplicationConfig)
   {
      this.subApplicationConfig = subApplicationConfig;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.ConsortiumType> getConsortiumTypes()
   {
      return this.consortiumTypes;
   }

   public void setConsortiumTypes(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.ConsortiumType> consortiumTypes)
   {
      this.consortiumTypes = consortiumTypes;
   }

   public EligibilityConfigItem(
         java.lang.Long eligibilityConfigId,
         java.lang.Long fundingOpportunityId,
         java.lang.Long fundingStreamId,
         java.lang.Integer appEligibleType,
         boolean subApplicationConfig,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.ConsortiumType> consortiumTypes)
   {
      this.eligibilityConfigId = eligibilityConfigId;
      this.fundingOpportunityId = fundingOpportunityId;
      this.fundingStreamId = fundingStreamId;
      this.appEligibleType = appEligibleType;
      this.subApplicationConfig = subApplicationConfig;
      this.consortiumTypes = consortiumTypes;
   }

}