package gov.dhs.fema.ndgrants_rules.model;

import gov.dhs.fema.ndgrants_rules.model.EGPTypeDef;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Eo12372Review extends EGPTypeDef implements java.io.Serializable
{

   static final long serialVersionUID = 1L;
   
   public static final Eo12372Review A__THISAPPLICATIONWASMADEAVAILABLETOTHE_STATEUNDERTHE_EXECUTIVE_ORDER_12372_PROCESSFORREVIEWON = new Eo12372Review(1);
   public static final Eo12372Review B__PROGRAMISSUBJECTTO_E__O_12372BUTHASNOTBEENSELECTEDBYTHE_STATEFORREVIEW_ = new Eo12372Review(2);
   public static final Eo12372Review C__PROGRAMISNOTCOVEREDBY_E__O_12372_ = new Eo12372Review(3);

   public Eo12372Review()
   {
       super();
   }
   
   Eo12372Review(long id){
       super(id);
   }

}