package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Eo12372Review implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Eo12372Review() {
    }

}