package gov.dhs.fema.ndgrants_rules.model;

import gov.dhs.fema.ndgrants_rules.model.Contact;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ExternalAdminContact extends Contact implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   public ExternalAdminContact()
   {
   }

}