package gov.dhs.fema.ndgrants_rules.model;

import gov.dhs.fema.ndgrants_rules.model.EGPTypeDef;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FinancialTransactionType extends EGPTypeDef implements java.io.Serializable
{

   static final long serialVersionUID = 1L;
   
   public static final FinancialTransactionType ADD = new FinancialTransactionType(1);
   public static final FinancialTransactionType MOD = new FinancialTransactionType(2);
   public static final FinancialTransactionType AMEND = new FinancialTransactionType(3);

   public FinancialTransactionType()
   {
       super();
   }
   
   FinancialTransactionType(long id)
   {
       super(id);
   }

}