package gov.dhs.fema.ndgrants_rules.model;

import gov.dhs.fema.ndgrants_rules.model.Form;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FOForm extends Form implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private gov.dhs.fema.ndgrants_rules.model.ApplicableFormType applicableFormType = gov.dhs.fema.ndgrants_rules.model.ApplicableFormType.DIRECT_APPLICANT;

   public FOForm()
   {
   }

   public gov.dhs.fema.ndgrants_rules.model.ApplicableFormType getApplicableFormType()
   {
      return this.applicableFormType;
   }

   public void setApplicableFormType(
         gov.dhs.fema.ndgrants_rules.model.ApplicableFormType applicableFormType)
   {
      this.applicableFormType = applicableFormType;
   }

   public FOForm(
         gov.dhs.fema.ndgrants_rules.model.ApplicableFormType applicableFormType)
   {
      this.applicableFormType = applicableFormType;
   }

}