package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ForecastedCashNeeds implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long forecastedCashNeedsId;
   private java.lang.Long applicationId;
   private java.lang.String directChargesExplanation;
   private java.lang.String indirectChargesExplanation;
   private java.lang.String remarks;
   private java.math.BigDecimal federalQ1;
   private java.math.BigDecimal federalQ2;
   private java.math.BigDecimal federalQ3;
   private java.math.BigDecimal federalQ4;
   private java.math.BigDecimal nonFederalQ1;
   private java.math.BigDecimal nonFederalQ2;
   private java.math.BigDecimal nonFederalQ3;
   private java.math.BigDecimal nonFederalQ4;
   private java.math.BigDecimal balanceFirstYear;
   private java.math.BigDecimal balanceSecondYear;
   private java.math.BigDecimal balanceThirdYear;
   private java.math.BigDecimal balanceFourthYear;

   public ForecastedCashNeeds()
   {
   }

   public java.lang.Long getForecastedCashNeedsId()
   {
      return this.forecastedCashNeedsId;
   }

   public void setForecastedCashNeedsId(java.lang.Long forecastedCashNeedsId)
   {
      this.forecastedCashNeedsId = forecastedCashNeedsId;
   }

   public java.lang.Long getApplicationId()
   {
      return this.applicationId;
   }

   public void setApplicationId(java.lang.Long applicationId)
   {
      this.applicationId = applicationId;
   }

   public java.lang.String getDirectChargesExplanation()
   {
      return this.directChargesExplanation;
   }

   public void setDirectChargesExplanation(
         java.lang.String directChargesExplanation)
   {
      this.directChargesExplanation = directChargesExplanation;
   }

   public java.lang.String getIndirectChargesExplanation()
   {
      return this.indirectChargesExplanation;
   }

   public void setIndirectChargesExplanation(
         java.lang.String indirectChargesExplanation)
   {
      this.indirectChargesExplanation = indirectChargesExplanation;
   }

   public java.lang.String getRemarks()
   {
      return this.remarks;
   }

   public void setRemarks(java.lang.String remarks)
   {
      this.remarks = remarks;
   }

   public java.math.BigDecimal getFederalQ1()
   {
      return this.federalQ1;
   }

   public void setFederalQ1(java.math.BigDecimal federalQ1)
   {
      this.federalQ1 = federalQ1;
   }

   public java.math.BigDecimal getFederalQ2()
   {
      return this.federalQ2;
   }

   public void setFederalQ2(java.math.BigDecimal federalQ2)
   {
      this.federalQ2 = federalQ2;
   }

   public java.math.BigDecimal getFederalQ3()
   {
      return this.federalQ3;
   }

   public void setFederalQ3(java.math.BigDecimal federalQ3)
   {
      this.federalQ3 = federalQ3;
   }

   public java.math.BigDecimal getFederalQ4()
   {
      return this.federalQ4;
   }

   public void setFederalQ4(java.math.BigDecimal federalQ4)
   {
      this.federalQ4 = federalQ4;
   }

   public java.math.BigDecimal getNonFederalQ1()
   {
      return this.nonFederalQ1;
   }

   public void setNonFederalQ1(java.math.BigDecimal nonFederalQ1)
   {
      this.nonFederalQ1 = nonFederalQ1;
   }

   public java.math.BigDecimal getNonFederalQ2()
   {
      return this.nonFederalQ2;
   }

   public void setNonFederalQ2(java.math.BigDecimal nonFederalQ2)
   {
      this.nonFederalQ2 = nonFederalQ2;
   }

   public java.math.BigDecimal getNonFederalQ3()
   {
      return this.nonFederalQ3;
   }

   public void setNonFederalQ3(java.math.BigDecimal nonFederalQ3)
   {
      this.nonFederalQ3 = nonFederalQ3;
   }

   public java.math.BigDecimal getNonFederalQ4()
   {
      return this.nonFederalQ4;
   }

   public void setNonFederalQ4(java.math.BigDecimal nonFederalQ4)
   {
      this.nonFederalQ4 = nonFederalQ4;
   }

   public java.math.BigDecimal getBalanceFirstYear()
   {
      return this.balanceFirstYear;
   }

   public void setBalanceFirstYear(java.math.BigDecimal balanceFirstYear)
   {
      this.balanceFirstYear = balanceFirstYear;
   }

   public java.math.BigDecimal getBalanceSecondYear()
   {
      return this.balanceSecondYear;
   }

   public void setBalanceSecondYear(java.math.BigDecimal balanceSecondYear)
   {
      this.balanceSecondYear = balanceSecondYear;
   }

   public java.math.BigDecimal getBalanceThirdYear()
   {
      return this.balanceThirdYear;
   }

   public void setBalanceThirdYear(java.math.BigDecimal balanceThirdYear)
   {
      this.balanceThirdYear = balanceThirdYear;
   }

   public java.math.BigDecimal getBalanceFourthYear()
   {
      return this.balanceFourthYear;
   }

   public void setBalanceFourthYear(java.math.BigDecimal balanceFourthYear)
   {
      this.balanceFourthYear = balanceFourthYear;
   }

   public ForecastedCashNeeds(java.lang.Long forecastedCashNeedsId,
         java.lang.Long applicationId,
         java.lang.String directChargesExplanation,
         java.lang.String indirectChargesExplanation,
         java.lang.String remarks, java.math.BigDecimal federalQ1,
         java.math.BigDecimal federalQ2, java.math.BigDecimal federalQ3,
         java.math.BigDecimal federalQ4, java.math.BigDecimal nonFederalQ1,
         java.math.BigDecimal nonFederalQ2,
         java.math.BigDecimal nonFederalQ3,
         java.math.BigDecimal nonFederalQ4,
         java.math.BigDecimal balanceFirstYear,
         java.math.BigDecimal balanceSecondYear,
         java.math.BigDecimal balanceThirdYear,
         java.math.BigDecimal balanceFourthYear)
   {
      this.forecastedCashNeedsId = forecastedCashNeedsId;
      this.applicationId = applicationId;
      this.directChargesExplanation = directChargesExplanation;
      this.indirectChargesExplanation = indirectChargesExplanation;
      this.remarks = remarks;
      this.federalQ1 = federalQ1;
      this.federalQ2 = federalQ2;
      this.federalQ3 = federalQ3;
      this.federalQ4 = federalQ4;
      this.nonFederalQ1 = nonFederalQ1;
      this.nonFederalQ2 = nonFederalQ2;
      this.nonFederalQ3 = nonFederalQ3;
      this.nonFederalQ4 = nonFederalQ4;
      this.balanceFirstYear = balanceFirstYear;
      this.balanceSecondYear = balanceSecondYear;
      this.balanceThirdYear = balanceThirdYear;
      this.balanceFourthYear = balanceFourthYear;
   }

}