package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Form implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer order;
   private java.lang.String displayName;
   private java.lang.Long formId;
   private java.lang.String json;
   private java.lang.String alias;
   private java.lang.String helpText;
   private java.lang.String validateRuleset;
   private boolean userDefined;
   private java.util.Date lastUpdated;
   private java.lang.String displayCondition;

   public Form()
   {
   }

   public java.lang.Integer getOrder()
   {
      return this.order;
   }

   public void setOrder(java.lang.Integer order)
   {
      this.order = order;
   }

   public java.lang.String getDisplayName()
   {
      return this.displayName;
   }

   public void setDisplayName(java.lang.String displayName)
   {
      this.displayName = displayName;
   }

   public java.lang.Long getFormId()
   {
      return this.formId;
   }

   public void setFormId(java.lang.Long formId)
   {
      this.formId = formId;
   }

   public java.lang.String getJson()
   {
      return this.json;
   }

   public void setJson(java.lang.String json)
   {
      this.json = json;
   }

   public java.lang.String getAlias()
   {
      return this.alias;
   }

   public void setAlias(java.lang.String alias)
   {
      this.alias = alias;
   }

   public java.lang.String getHelpText()
   {
      return this.helpText;
   }

   public void setHelpText(java.lang.String helpText)
   {
      this.helpText = helpText;
   }

   public java.lang.String getValidateRuleset()
   {
      return this.validateRuleset;
   }

   public void setValidateRuleset(java.lang.String validateRuleset)
   {
      this.validateRuleset = validateRuleset;
   }

   public boolean isUserDefined()
   {
      return this.userDefined;
   }

   public void setUserDefined(boolean userDefined)
   {
      this.userDefined = userDefined;
   }

   public java.util.Date getLastUpdated()
   {
      return this.lastUpdated;
   }

   public void setLastUpdated(java.util.Date lastUpdated)
   {
      this.lastUpdated = lastUpdated;
   }

   public java.lang.String getDisplayCondition()
   {
      return this.displayCondition;
   }

   public void setDisplayCondition(java.lang.String displayCondition)
   {
      this.displayCondition = displayCondition;
   }

   public Form(java.lang.Integer order, java.lang.String displayName,
         java.lang.Long formId, java.lang.String json,
         java.lang.String alias, java.lang.String helpText,
         java.lang.String validateRuleset, boolean userDefined,
         java.util.Date lastUpdated, java.lang.String displayCondition)
   {
      this.order = order;
      this.displayName = displayName;
      this.formId = formId;
      this.json = json;
      this.alias = alias;
      this.helpText = helpText;
      this.validateRuleset = validateRuleset;
      this.userDefined = userDefined;
      this.lastUpdated = lastUpdated;
      this.displayCondition = displayCondition;
   }

}