package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FormInstance implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long formInstanceId;
   private java.lang.Long taskInstanceId;
   private gov.dhs.fema.ndgrants_rules.model.ObjectType objectType;
   private java.lang.Long objectId;
   private boolean formDisplayed;
   private boolean formHidden;
   private gov.dhs.fema.ndgrants_rules.model.FPTFormElement fptFormElement;

   public FormInstance()
   {
   }

   public java.lang.Long getFormInstanceId()
   {
      return this.formInstanceId;
   }

   public void setFormInstanceId(java.lang.Long formInstanceId)
   {
      this.formInstanceId = formInstanceId;
   }

   public java.lang.Long getTaskInstanceId()
   {
      return this.taskInstanceId;
   }

   public void setTaskInstanceId(java.lang.Long taskInstanceId)
   {
      this.taskInstanceId = taskInstanceId;
   }

   public gov.dhs.fema.ndgrants_rules.model.ObjectType getObjectType()
   {
      return this.objectType;
   }

   public void setObjectType(
         gov.dhs.fema.ndgrants_rules.model.ObjectType objectType)
   {
      this.objectType = objectType;
   }

   public java.lang.Long getObjectId()
   {
      return this.objectId;
   }

   public void setObjectId(java.lang.Long objectId)
   {
      this.objectId = objectId;
   }

   public boolean isFormDisplayed()
   {
      return this.formDisplayed;
   }

   public void setFormDisplayed(boolean formDisplayed)
   {
      this.formDisplayed = formDisplayed;
   }

   public boolean isFormHidden()
   {
      return this.formHidden;
   }

   public void setFormHidden(boolean formHidden)
   {
      this.formHidden = formHidden;
   }

   public gov.dhs.fema.ndgrants_rules.model.FPTFormElement getFptFormElement()
   {
      return this.fptFormElement;
   }

   public void setFptFormElement(
         gov.dhs.fema.ndgrants_rules.model.FPTFormElement fptFormElement)
   {
      this.fptFormElement = fptFormElement;
   }

   public FormInstance(java.lang.Long formInstanceId,
         java.lang.Long taskInstanceId,
         gov.dhs.fema.ndgrants_rules.model.ObjectType objectType,
         java.lang.Long objectId, boolean formDisplayed, boolean formHidden,
         gov.dhs.fema.ndgrants_rules.model.FPTFormElement fptFormElement)
   {
      this.formInstanceId = formInstanceId;
      this.taskInstanceId = taskInstanceId;
      this.objectType = objectType;
      this.objectId = objectId;
      this.formDisplayed = formDisplayed;
      this.formHidden = formHidden;
      this.fptFormElement = fptFormElement;
   }

}