package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FormOutcome implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long formOutcomeId;
   private java.lang.String outcomeDecision;
   private java.lang.String comments;
   private gov.dhs.fema.ndgrants_rules.model.Form form;
   private gov.dhs.fema.ndgrants_rules.model.ObjectType objectType;
   private java.lang.Long objectId;
   private gov.dhs.fema.ndgrants_rules.model.User user;
   private java.util.Date decisionDate;

   public FormOutcome()
   {
   }

   public java.lang.Long getFormOutcomeId()
   {
      return this.formOutcomeId;
   }

   public void setFormOutcomeId(java.lang.Long formOutcomeId)
   {
      this.formOutcomeId = formOutcomeId;
   }

   public java.lang.String getOutcomeDecision()
   {
      return this.outcomeDecision;
   }

   public void setOutcomeDecision(java.lang.String outcomeDecision)
   {
      this.outcomeDecision = outcomeDecision;
   }

   public java.lang.String getComments()
   {
      return this.comments;
   }

   public void setComments(java.lang.String comments)
   {
      this.comments = comments;
   }

   public gov.dhs.fema.ndgrants_rules.model.Form getForm()
   {
      return this.form;
   }

   public void setForm(gov.dhs.fema.ndgrants_rules.model.Form form)
   {
      this.form = form;
   }

   public gov.dhs.fema.ndgrants_rules.model.ObjectType getObjectType()
   {
      return this.objectType;
   }

   public void setObjectType(
         gov.dhs.fema.ndgrants_rules.model.ObjectType objectType)
   {
      this.objectType = objectType;
   }

   public java.lang.Long getObjectId()
   {
      return this.objectId;
   }

   public void setObjectId(java.lang.Long objectId)
   {
      this.objectId = objectId;
   }

   public gov.dhs.fema.ndgrants_rules.model.User getUser()
   {
      return this.user;
   }

   public void setUser(gov.dhs.fema.ndgrants_rules.model.User user)
   {
      this.user = user;
   }

   public java.util.Date getDecisionDate()
   {
      return this.decisionDate;
   }

   public void setDecisionDate(java.util.Date decisionDate)
   {
      this.decisionDate = decisionDate;
   }

   public FormOutcome(java.lang.Long formOutcomeId,
         java.lang.String outcomeDecision, java.lang.String comments,
         gov.dhs.fema.ndgrants_rules.model.Form form,
         gov.dhs.fema.ndgrants_rules.model.ObjectType objectType,
         java.lang.Long objectId,
         gov.dhs.fema.ndgrants_rules.model.User user,
         java.util.Date decisionDate)
   {
      this.formOutcomeId = formOutcomeId;
      this.outcomeDecision = outcomeDecision;
      this.comments = comments;
      this.form = form;
      this.objectType = objectType;
      this.objectId = objectId;
      this.user = user;
      this.decisionDate = decisionDate;
   }

}