package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FPTElement implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long elementId;
   private java.lang.String name;
   private java.lang.String alias;
   private java.lang.Long fundingPlanTemplateId;
   private java.lang.Long parentElementId;
   private int sortOrder;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.FPTElement> elements;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.FPTFormElement> ftpFormElements;

   public FPTElement()
   {
   }

   public java.lang.Long getElementId()
   {
      return this.elementId;
   }

   public void setElementId(java.lang.Long elementId)
   {
      this.elementId = elementId;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getAlias()
   {
      return this.alias;
   }

   public void setAlias(java.lang.String alias)
   {
      this.alias = alias;
   }

   public java.lang.Long getFundingPlanTemplateId()
   {
      return this.fundingPlanTemplateId;
   }

   public void setFundingPlanTemplateId(java.lang.Long fundingPlanTemplateId)
   {
      this.fundingPlanTemplateId = fundingPlanTemplateId;
   }

   public java.lang.Long getParentElementId()
   {
      return this.parentElementId;
   }

   public void setParentElementId(java.lang.Long parentElementId)
   {
      this.parentElementId = parentElementId;
   }

   public int getSortOrder()
   {
      return this.sortOrder;
   }

   public void setSortOrder(int sortOrder)
   {
      this.sortOrder = sortOrder;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.FPTElement> getElements()
   {
      return this.elements;
   }

   public void setElements(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.FPTElement> elements)
   {
      this.elements = elements;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.FPTFormElement> getFtpFormElements()
   {
      return this.ftpFormElements;
   }

   public void setFtpFormElements(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.FPTFormElement> ftpFormElements)
   {
      this.ftpFormElements = ftpFormElements;
   }

   public FPTElement(
         java.lang.Long elementId,
         java.lang.String name,
         java.lang.String alias,
         java.lang.Long fundingPlanTemplateId,
         java.lang.Long parentElementId,
         int sortOrder,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.FPTElement> elements,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.FPTFormElement> ftpFormElements)
   {
      this.elementId = elementId;
      this.name = name;
      this.alias = alias;
      this.fundingPlanTemplateId = fundingPlanTemplateId;
      this.parentElementId = parentElementId;
      this.sortOrder = sortOrder;
      this.elements = elements;
      this.ftpFormElements = ftpFormElements;
   }

}