package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FPTFormElementOption implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long fptFormElementOptionId;
   private java.lang.String optionName;
   private java.lang.String optionAlias;
   private java.lang.Long fptFormElementId;
   private int sortOrder;
   private java.lang.String optionCategory;
   private gov.dhs.fema.ndgrants_rules.model.BudgetClass budgetClass;

   public FPTFormElementOption()
   {
   }

   public java.lang.Long getFptFormElementOptionId()
   {
      return this.fptFormElementOptionId;
   }

   public void setFptFormElementOptionId(java.lang.Long fptFormElementOptionId)
   {
      this.fptFormElementOptionId = fptFormElementOptionId;
   }

   public java.lang.String getOptionName()
   {
      return this.optionName;
   }

   public void setOptionName(java.lang.String optionName)
   {
      this.optionName = optionName;
   }

   public java.lang.String getOptionAlias()
   {
      return this.optionAlias;
   }

   public void setOptionAlias(java.lang.String optionAlias)
   {
      this.optionAlias = optionAlias;
   }

   public java.lang.Long getFptFormElementId()
   {
      return this.fptFormElementId;
   }

   public void setFptFormElementId(java.lang.Long fptFormElementId)
   {
      this.fptFormElementId = fptFormElementId;
   }

   public int getSortOrder()
   {
      return this.sortOrder;
   }

   public void setSortOrder(int sortOrder)
   {
      this.sortOrder = sortOrder;
   }

   public java.lang.String getOptionCategory()
   {
      return this.optionCategory;
   }

   public void setOptionCategory(java.lang.String optionCategory)
   {
      this.optionCategory = optionCategory;
   }

   public gov.dhs.fema.ndgrants_rules.model.BudgetClass getBudgetClass()
   {
      return this.budgetClass;
   }

   public void setBudgetClass(
         gov.dhs.fema.ndgrants_rules.model.BudgetClass budgetClass)
   {
      this.budgetClass = budgetClass;
   }

   public FPTFormElementOption(java.lang.Long fptFormElementOptionId,
         java.lang.String optionName, java.lang.String optionAlias,
         java.lang.Long fptFormElementId, int sortOrder,
         java.lang.String optionCategory,
         gov.dhs.fema.ndgrants_rules.model.BudgetClass budgetClass)
   {
      this.fptFormElementOptionId = fptFormElementOptionId;
      this.optionName = optionName;
      this.optionAlias = optionAlias;
      this.fptFormElementId = fptFormElementId;
      this.sortOrder = sortOrder;
      this.optionCategory = optionCategory;
      this.budgetClass = budgetClass;
   }

}