package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FundingOpportunityPublishActionHistory implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long fundingOpportunityPublishActionId;
   private java.lang.Long fundingOpportunityId;
   private java.util.Date publishDate;
   private java.lang.Boolean successfulPublish;
   private gov.dhs.fema.ndgrants_rules.model.User publishedByUser;
   private gov.dhs.fema.ndgrants_rules.model.GrantsGovPublishType grantsGovPublishType;
   private java.util.List<java.lang.String> publishResult;

   public FundingOpportunityPublishActionHistory()
   {
   }

   public java.lang.Long getFundingOpportunityPublishActionId()
   {
      return this.fundingOpportunityPublishActionId;
   }

   public void setFundingOpportunityPublishActionId(
         java.lang.Long fundingOpportunityPublishActionId)
   {
      this.fundingOpportunityPublishActionId = fundingOpportunityPublishActionId;
   }

   public java.lang.Long getFundingOpportunityId()
   {
      return this.fundingOpportunityId;
   }

   public void setFundingOpportunityId(java.lang.Long fundingOpportunityId)
   {
      this.fundingOpportunityId = fundingOpportunityId;
   }

   public java.util.Date getPublishDate()
   {
      return this.publishDate;
   }

   public void setPublishDate(java.util.Date publishDate)
   {
      this.publishDate = publishDate;
   }

   public java.lang.Boolean getSuccessfulPublish()
   {
      return this.successfulPublish;
   }

   public void setSuccessfulPublish(java.lang.Boolean successfulPublish)
   {
      this.successfulPublish = successfulPublish;
   }

   public gov.dhs.fema.ndgrants_rules.model.User getPublishedByUser()
   {
      return this.publishedByUser;
   }

   public void setPublishedByUser(
         gov.dhs.fema.ndgrants_rules.model.User publishedByUser)
   {
      this.publishedByUser = publishedByUser;
   }

   public gov.dhs.fema.ndgrants_rules.model.GrantsGovPublishType getGrantsGovPublishType()
   {
      return this.grantsGovPublishType;
   }

   public void setGrantsGovPublishType(
         gov.dhs.fema.ndgrants_rules.model.GrantsGovPublishType grantsGovPublishType)
   {
      this.grantsGovPublishType = grantsGovPublishType;
   }

   public java.util.List<java.lang.String> getPublishResult()
   {
      return this.publishResult;
   }

   public void setPublishResult(java.util.List<java.lang.String> publishResult)
   {
      this.publishResult = publishResult;
   }

   public FundingOpportunityPublishActionHistory(
         java.lang.Long fundingOpportunityPublishActionId,
         java.lang.Long fundingOpportunityId,
         java.util.Date publishDate,
         java.lang.Boolean successfulPublish,
         gov.dhs.fema.ndgrants_rules.model.User publishedByUser,
         gov.dhs.fema.ndgrants_rules.model.GrantsGovPublishType grantsGovPublishType,
         java.util.List<java.lang.String> publishResult)
   {
      this.fundingOpportunityPublishActionId = fundingOpportunityPublishActionId;
      this.fundingOpportunityId = fundingOpportunityId;
      this.publishDate = publishDate;
      this.successfulPublish = successfulPublish;
      this.publishedByUser = publishedByUser;
      this.grantsGovPublishType = grantsGovPublishType;
      this.publishResult = publishResult;
   }

}