package gov.dhs.fema.ndgrants_rules.model;

import gov.dhs.fema.ndgrants_rules.model.EGPCodedTypeDef;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FundingCategory extends EGPCodedTypeDef implements java.io.Serializable
{

   static final long serialVersionUID = 1L;
   
    public static final FundingCategory AGRICULTURE = new FundingCategory(1, "AG");
    public static final FundingCategory ARTS = new FundingCategory(2, "AR");
    public static final FundingCategory BUSINESSAND_COMMERCE = new FundingCategory(3, "BC");
    public static final FundingCategory COMMUNITY_DEVELOPMENT = new FundingCategory(4, "CD");
    public static final FundingCategory CONSUMER_PROTECTION = new FundingCategory(5, "CP");
    public static final FundingCategory DISASTER_PREVENTIONAND_RELIEF = new FundingCategory(6, "DPR");
    public static final FundingCategory EDUCATION = new FundingCategory(7, "ED");
    public static final FundingCategory EMPLOYMENT_LABORAND_TRAINING = new FundingCategory(8, "ELT");
    public static final FundingCategory ENERGY = new FundingCategory(9, "EN");
    public static final FundingCategory ENVIROMENT = new FundingCategory(10, "ENV");
    public static final FundingCategory FOODAND_NUTRITION = new FundingCategory(11, "FN");
    public static final FundingCategory HEALTH = new FundingCategory(12, "HL");
    public static final FundingCategory HOUSING = new FundingCategory(13, "HO");
    public static final FundingCategory HUMANITIES = new FundingCategory(14, "HU");
    public static final FundingCategory INCOME_SECURITYAND_SOCIAL_SERVICES = new FundingCategory(15, "ISS");
    public static final FundingCategory INFORMATIONAND_STATISTICS = new FundingCategory(16, "IS");
    public static final FundingCategory LAW_JUSTICESAND_LEGAL_SERVICES = new FundingCategory(17, "LJL");
    public static final FundingCategory NATURAL_RESOURCES = new FundingCategory(18, "NR");
    public static final FundingCategory RECOVERY_ACTN = new FundingCategory(19, "RA");
    public static final FundingCategory REGIONAL_DEVELOPMENT = new FundingCategory(20, "RD");
    public static final FundingCategory SCIENCEAND_TECHNOLOGYANDOTHER_RESEARCHAND_DEVELOPMENT = new FundingCategory(21, "ST");
    public static final FundingCategory TRANSPORTATION = new FundingCategory(22, "T");
    public static final FundingCategory OTHER = new FundingCategory(23, "O");

   public FundingCategory()
   {
   }
   
   FundingCategory(long id, String code){
       super(id, code);
   }

}