package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FundingOpportunity implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long fundingOpportunityId;
   private java.lang.Long originalFundingOpportunityId;
   private gov.dhs.fema.ndgrants_rules.model.Program program;
   private java.lang.Integer fiscalYear;
   private java.lang.String name;
   private java.lang.String description;
   private java.lang.String opportunityNo;
   private gov.dhs.fema.ndgrants_rules.model.AdminConfigStatus status;
   private boolean costSharing;
   private java.lang.Integer federalShareRatePct;
   private boolean overMatchAllowed;
   private boolean allowingApplications;
   private gov.dhs.fema.ndgrants_rules.model.User openForApplicationsByUser;
   private boolean allowingSubApplicants;
   private java.lang.Integer subAppEligibilityTypeId;
   private boolean published;
   private gov.dhs.fema.ndgrants_rules.model.User publishedByUser;
   private java.util.Date publishedOnDate;
   private java.lang.String fundingPlanAppSectionTitle;
   private java.lang.Long applicationLevel;
   private java.lang.Long postAwardLevel;
   private java.lang.Long closeoutLevel;
   private java.lang.Boolean threeDayCert;
   private java.util.Date threeDayCertDate;
   private java.lang.Boolean fiveDayRequired;
   private java.lang.Boolean fiveDayCert;
   private java.util.Date fiveDayCertDate;
   private java.lang.String fiveDayRequiredComment;
   private java.lang.Long expectedNoOfAwards;
   private java.lang.Long grantsGovAwardCeiling;
   private java.lang.Long grantsGovAwardFloor;
   private java.lang.Long grantsGovEstimatedFunding;
   private java.util.Date grantsGovAppStartDate;
   private java.util.Date grantsGovAppEndDate;
   private java.lang.String grantsGovAppEndDateExplanation;
   private java.util.Date grantsGovArchiveDate;
   private java.util.Date grantsGovAppPackageStartDate;
   private java.util.Date grantsGovAppPackageEndDate;
   private java.lang.Integer grantsGovAppPackageGraceDays;
   private java.lang.Integer maxApplicationsPerOrganization;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.EligibleApplicantType> eligibleApplicantTypes;
   private java.lang.String eligibleApplicantOtherExplanation;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.FundingInstrumentType> fundingInstrumentTypes;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.FundingCategory> fundingCategoryTypes;
   private java.lang.String fundingCategoryOtherExplanation;
   private java.util.Date applicationSubmissionStartTimestamp;
   private java.util.Date applicationSubmissionEndTimestamp;
   private java.util.Date applicationSubmissionGraceEndTimestamp;
   private gov.dhs.fema.ndgrants_rules.model.PerformanceReportTemplate performanceReportTemplate;
   private java.lang.String fundingOpportunityUrl;
   private gov.dhs.fema.ndgrants_rules.model.AdministeringOffice administeringOffice;
   private gov.dhs.fema.ndgrants_rules.model.FinancialSystem financialSystem;
   private gov.dhs.fema.ndgrants_rules.model.PaymentMethod paymentMethod;
   private gov.dhs.fema.ndgrants_rules.model.ProjectType projectType;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> fundingOpportunityContacts;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.BpmProcess> bpmProcessAssignments;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.Operation> fundingOpportunityOperations;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.StatutoryAuthority> statutoryAuthorities;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> terms;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.FOForm> forms;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.Template> templates;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.Template> allTemplates;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.Commitment> commitments;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.FundingOpportunityAlternateOperation> alternateOperations;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> financeObligationContacts;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> granteeNotificationContacts;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> systemBranchChiefContacts;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> grantsGovContacts;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> financeVendorContacts;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> signingAuthorityContacts;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> alternateSigningAuthorityContacts;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> otherContacts;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> grantsManagementBranchContacts;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> grantsCounselContacts;
   private boolean investmentBased;
   private java.lang.Integer maxInvestmentsPerApplicant;
   private java.lang.Integer maxInvestmentsPerSubApplicant;
   private java.lang.String investmentOverviewTitle;
   private gov.dhs.fema.ndgrants_rules.model.Form investmentOverviewForm;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.Form> investmentForms;
   private java.lang.Integer applicationsInUse;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> availableTerms;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.FundingDetailPathFundingStream> fundingDetailPathFundingStreams;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.FundingOpportunityPublishActionHistory> fundingOpportunityPublishActionResults;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.EligibilityConfigItem> eligibilityConfigItems;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.EligibilityConfigItem> subAppEligibilityConfigItems;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.ModuleRuleSet> moduleRuleSets;
   private boolean applicationSubmissionTimerDisplayed;
   private boolean applicationPercentageCompletionDisplayed;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.FOForm> allForms;

   public FundingOpportunity()
   {
   }

   public java.lang.Long getFundingOpportunityId()
   {
      return this.fundingOpportunityId;
   }

   public void setFundingOpportunityId(java.lang.Long fundingOpportunityId)
   {
      this.fundingOpportunityId = fundingOpportunityId;
   }

   public java.lang.Long getOriginalFundingOpportunityId()
   {
      return this.originalFundingOpportunityId;
   }

   public void setOriginalFundingOpportunityId(
         java.lang.Long originalFundingOpportunityId)
   {
      this.originalFundingOpportunityId = originalFundingOpportunityId;
   }

   public gov.dhs.fema.ndgrants_rules.model.Program getProgram()
   {
      return this.program;
   }

   public void setProgram(gov.dhs.fema.ndgrants_rules.model.Program program)
   {
      this.program = program;
   }

   public java.lang.Integer getFiscalYear()
   {
      return this.fiscalYear;
   }

   public void setFiscalYear(java.lang.Integer fiscalYear)
   {
      this.fiscalYear = fiscalYear;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getDescription()
   {
      return this.description;
   }

   public void setDescription(java.lang.String description)
   {
      this.description = description;
   }

   public java.lang.String getOpportunityNo()
   {
      return this.opportunityNo;
   }

   public void setOpportunityNo(java.lang.String opportunityNo)
   {
      this.opportunityNo = opportunityNo;
   }

   public gov.dhs.fema.ndgrants_rules.model.AdminConfigStatus getStatus()
   {
      return this.status;
   }

   public void setStatus(
         gov.dhs.fema.ndgrants_rules.model.AdminConfigStatus status)
   {
      this.status = status;
   }

   public boolean isCostSharing()
   {
      return this.costSharing;
   }

   public void setCostSharing(boolean costSharing)
   {
      this.costSharing = costSharing;
   }

   public java.lang.Integer getFederalShareRatePct()
   {
      return this.federalShareRatePct;
   }

   public void setFederalShareRatePct(java.lang.Integer federalShareRatePct)
   {
      this.federalShareRatePct = federalShareRatePct;
   }

   public boolean isOverMatchAllowed()
   {
      return this.overMatchAllowed;
   }

   public void setOverMatchAllowed(boolean overMatchAllowed)
   {
      this.overMatchAllowed = overMatchAllowed;
   }

   public boolean isAllowingApplications()
   {
      return this.allowingApplications;
   }

   public void setAllowingApplications(boolean allowingApplications)
   {
      this.allowingApplications = allowingApplications;
   }

   public gov.dhs.fema.ndgrants_rules.model.User getOpenForApplicationsByUser()
   {
      return this.openForApplicationsByUser;
   }

   public void setOpenForApplicationsByUser(
         gov.dhs.fema.ndgrants_rules.model.User openForApplicationsByUser)
   {
      this.openForApplicationsByUser = openForApplicationsByUser;
   }

   public boolean isAllowingSubApplicants()
   {
      return this.allowingSubApplicants;
   }

   public void setAllowingSubApplicants(boolean allowingSubApplicants)
   {
      this.allowingSubApplicants = allowingSubApplicants;
   }

   public java.lang.Integer getSubAppEligibilityTypeId()
   {
      return this.subAppEligibilityTypeId;
   }

   public void setSubAppEligibilityTypeId(
         java.lang.Integer subAppEligibilityTypeId)
   {
      this.subAppEligibilityTypeId = subAppEligibilityTypeId;
   }

   public boolean isPublished()
   {
      return this.published;
   }

   public void setPublished(boolean published)
   {
      this.published = published;
   }

   public gov.dhs.fema.ndgrants_rules.model.User getPublishedByUser()
   {
      return this.publishedByUser;
   }

   public void setPublishedByUser(
         gov.dhs.fema.ndgrants_rules.model.User publishedByUser)
   {
      this.publishedByUser = publishedByUser;
   }

   public java.util.Date getPublishedOnDate()
   {
      return this.publishedOnDate;
   }

   public void setPublishedOnDate(java.util.Date publishedOnDate)
   {
      this.publishedOnDate = publishedOnDate;
   }

   public java.lang.String getFundingPlanAppSectionTitle()
   {
      return this.fundingPlanAppSectionTitle;
   }

   public void setFundingPlanAppSectionTitle(
         java.lang.String fundingPlanAppSectionTitle)
   {
      this.fundingPlanAppSectionTitle = fundingPlanAppSectionTitle;
   }

   public java.lang.Long getApplicationLevel()
   {
      return this.applicationLevel;
   }

   public void setApplicationLevel(java.lang.Long applicationLevel)
   {
      this.applicationLevel = applicationLevel;
   }

   public java.lang.Long getPostAwardLevel()
   {
      return this.postAwardLevel;
   }

   public void setPostAwardLevel(java.lang.Long postAwardLevel)
   {
      this.postAwardLevel = postAwardLevel;
   }

   public java.lang.Long getCloseoutLevel()
   {
      return this.closeoutLevel;
   }

   public void setCloseoutLevel(java.lang.Long closeoutLevel)
   {
      this.closeoutLevel = closeoutLevel;
   }

   public java.lang.Boolean getThreeDayCert()
   {
      return this.threeDayCert;
   }

   public void setThreeDayCert(java.lang.Boolean threeDayCert)
   {
      this.threeDayCert = threeDayCert;
   }

   public java.util.Date getThreeDayCertDate()
   {
      return this.threeDayCertDate;
   }

   public void setThreeDayCertDate(java.util.Date threeDayCertDate)
   {
      this.threeDayCertDate = threeDayCertDate;
   }

   public java.lang.Boolean getFiveDayRequired()
   {
      return this.fiveDayRequired;
   }

   public void setFiveDayRequired(java.lang.Boolean fiveDayRequired)
   {
      this.fiveDayRequired = fiveDayRequired;
   }

   public java.lang.Boolean getFiveDayCert()
   {
      return this.fiveDayCert;
   }

   public void setFiveDayCert(java.lang.Boolean fiveDayCert)
   {
      this.fiveDayCert = fiveDayCert;
   }

   public java.util.Date getFiveDayCertDate()
   {
      return this.fiveDayCertDate;
   }

   public void setFiveDayCertDate(java.util.Date fiveDayCertDate)
   {
      this.fiveDayCertDate = fiveDayCertDate;
   }

   public java.lang.String getFiveDayRequiredComment()
   {
      return this.fiveDayRequiredComment;
   }

   public void setFiveDayRequiredComment(
         java.lang.String fiveDayRequiredComment)
   {
      this.fiveDayRequiredComment = fiveDayRequiredComment;
   }

   public java.lang.Long getExpectedNoOfAwards()
   {
      return this.expectedNoOfAwards;
   }

   public void setExpectedNoOfAwards(java.lang.Long expectedNoOfAwards)
   {
      this.expectedNoOfAwards = expectedNoOfAwards;
   }

   public java.lang.Long getGrantsGovAwardCeiling()
   {
      return this.grantsGovAwardCeiling;
   }

   public void setGrantsGovAwardCeiling(java.lang.Long grantsGovAwardCeiling)
   {
      this.grantsGovAwardCeiling = grantsGovAwardCeiling;
   }

   public java.lang.Long getGrantsGovAwardFloor()
   {
      return this.grantsGovAwardFloor;
   }

   public void setGrantsGovAwardFloor(java.lang.Long grantsGovAwardFloor)
   {
      this.grantsGovAwardFloor = grantsGovAwardFloor;
   }

   public java.lang.Long getGrantsGovEstimatedFunding()
   {
      return this.grantsGovEstimatedFunding;
   }

   public void setGrantsGovEstimatedFunding(
         java.lang.Long grantsGovEstimatedFunding)
   {
      this.grantsGovEstimatedFunding = grantsGovEstimatedFunding;
   }

   public java.util.Date getGrantsGovAppStartDate()
   {
      return this.grantsGovAppStartDate;
   }

   public void setGrantsGovAppStartDate(java.util.Date grantsGovAppStartDate)
   {
      this.grantsGovAppStartDate = grantsGovAppStartDate;
   }

   public java.util.Date getGrantsGovAppEndDate()
   {
      return this.grantsGovAppEndDate;
   }

   public void setGrantsGovAppEndDate(java.util.Date grantsGovAppEndDate)
   {
      this.grantsGovAppEndDate = grantsGovAppEndDate;
   }

   public java.lang.String getGrantsGovAppEndDateExplanation()
   {
      return this.grantsGovAppEndDateExplanation;
   }

   public void setGrantsGovAppEndDateExplanation(
         java.lang.String grantsGovAppEndDateExplanation)
   {
      this.grantsGovAppEndDateExplanation = grantsGovAppEndDateExplanation;
   }

   public java.util.Date getGrantsGovArchiveDate()
   {
      return this.grantsGovArchiveDate;
   }

   public void setGrantsGovArchiveDate(java.util.Date grantsGovArchiveDate)
   {
      this.grantsGovArchiveDate = grantsGovArchiveDate;
   }

   public java.util.Date getGrantsGovAppPackageStartDate()
   {
      return this.grantsGovAppPackageStartDate;
   }

   public void setGrantsGovAppPackageStartDate(
         java.util.Date grantsGovAppPackageStartDate)
   {
      this.grantsGovAppPackageStartDate = grantsGovAppPackageStartDate;
   }

   public java.util.Date getGrantsGovAppPackageEndDate()
   {
      return this.grantsGovAppPackageEndDate;
   }

   public void setGrantsGovAppPackageEndDate(
         java.util.Date grantsGovAppPackageEndDate)
   {
      this.grantsGovAppPackageEndDate = grantsGovAppPackageEndDate;
   }

   public java.lang.Integer getGrantsGovAppPackageGraceDays()
   {
      return this.grantsGovAppPackageGraceDays;
   }

   public void setGrantsGovAppPackageGraceDays(
         java.lang.Integer grantsGovAppPackageGraceDays)
   {
      this.grantsGovAppPackageGraceDays = grantsGovAppPackageGraceDays;
   }

   public java.lang.Integer getMaxApplicationsPerOrganization()
   {
      return this.maxApplicationsPerOrganization;
   }

   public void setMaxApplicationsPerOrganization(
         java.lang.Integer maxApplicationsPerOrganization)
   {
      this.maxApplicationsPerOrganization = maxApplicationsPerOrganization;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.EligibleApplicantType> getEligibleApplicantTypes()
   {
      return this.eligibleApplicantTypes;
   }

   public void setEligibleApplicantTypes(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.EligibleApplicantType> eligibleApplicantTypes)
   {
      this.eligibleApplicantTypes = eligibleApplicantTypes;
   }

   public java.lang.String getEligibleApplicantOtherExplanation()
   {
      return this.eligibleApplicantOtherExplanation;
   }

   public void setEligibleApplicantOtherExplanation(
         java.lang.String eligibleApplicantOtherExplanation)
   {
      this.eligibleApplicantOtherExplanation = eligibleApplicantOtherExplanation;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.FundingInstrumentType> getFundingInstrumentTypes()
   {
      return this.fundingInstrumentTypes;
   }

   public void setFundingInstrumentTypes(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.FundingInstrumentType> fundingInstrumentTypes)
   {
      this.fundingInstrumentTypes = fundingInstrumentTypes;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.FundingCategory> getFundingCategoryTypes()
   {
      return this.fundingCategoryTypes;
   }

   public void setFundingCategoryTypes(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.FundingCategory> fundingCategoryTypes)
   {
      this.fundingCategoryTypes = fundingCategoryTypes;
   }

   public java.lang.String getFundingCategoryOtherExplanation()
   {
      return this.fundingCategoryOtherExplanation;
   }

   public void setFundingCategoryOtherExplanation(
         java.lang.String fundingCategoryOtherExplanation)
   {
      this.fundingCategoryOtherExplanation = fundingCategoryOtherExplanation;
   }

   public java.util.Date getApplicationSubmissionStartTimestamp()
   {
      return this.applicationSubmissionStartTimestamp;
   }

   public void setApplicationSubmissionStartTimestamp(
         java.util.Date applicationSubmissionStartTimestamp)
   {
      this.applicationSubmissionStartTimestamp = applicationSubmissionStartTimestamp;
   }

   public java.util.Date getApplicationSubmissionEndTimestamp()
   {
      return this.applicationSubmissionEndTimestamp;
   }

   public void setApplicationSubmissionEndTimestamp(
         java.util.Date applicationSubmissionEndTimestamp)
   {
      this.applicationSubmissionEndTimestamp = applicationSubmissionEndTimestamp;
   }

   public java.util.Date getApplicationSubmissionGraceEndTimestamp()
   {
      return this.applicationSubmissionGraceEndTimestamp;
   }

   public void setApplicationSubmissionGraceEndTimestamp(
         java.util.Date applicationSubmissionGraceEndTimestamp)
   {
      this.applicationSubmissionGraceEndTimestamp = applicationSubmissionGraceEndTimestamp;
   }

   public gov.dhs.fema.ndgrants_rules.model.PerformanceReportTemplate getPerformanceReportTemplate()
   {
      return this.performanceReportTemplate;
   }

   public void setPerformanceReportTemplate(
         gov.dhs.fema.ndgrants_rules.model.PerformanceReportTemplate performanceReportTemplate)
   {
      this.performanceReportTemplate = performanceReportTemplate;
   }

   public java.lang.String getFundingOpportunityUrl()
   {
      return this.fundingOpportunityUrl;
   }

   public void setFundingOpportunityUrl(java.lang.String fundingOpportunityUrl)
   {
      this.fundingOpportunityUrl = fundingOpportunityUrl;
   }

   public gov.dhs.fema.ndgrants_rules.model.AdministeringOffice getAdministeringOffice()
   {
      return this.administeringOffice;
   }

   public void setAdministeringOffice(
         gov.dhs.fema.ndgrants_rules.model.AdministeringOffice administeringOffice)
   {
      this.administeringOffice = administeringOffice;
   }

   public gov.dhs.fema.ndgrants_rules.model.FinancialSystem getFinancialSystem()
   {
      return this.financialSystem;
   }

   public void setFinancialSystem(
         gov.dhs.fema.ndgrants_rules.model.FinancialSystem financialSystem)
   {
      this.financialSystem = financialSystem;
   }

   public gov.dhs.fema.ndgrants_rules.model.PaymentMethod getPaymentMethod()
   {
      return this.paymentMethod;
   }

   public void setPaymentMethod(
         gov.dhs.fema.ndgrants_rules.model.PaymentMethod paymentMethod)
   {
      this.paymentMethod = paymentMethod;
   }

   public gov.dhs.fema.ndgrants_rules.model.ProjectType getProjectType()
   {
      return this.projectType;
   }

   public void setProjectType(
         gov.dhs.fema.ndgrants_rules.model.ProjectType projectType)
   {
      this.projectType = projectType;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> getFundingOpportunityContacts()
   {
      return this.fundingOpportunityContacts;
   }

   public void setFundingOpportunityContacts(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> fundingOpportunityContacts)
   {
      this.fundingOpportunityContacts = fundingOpportunityContacts;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.BpmProcess> getBpmProcessAssignments()
   {
      return this.bpmProcessAssignments;
   }

   public void setBpmProcessAssignments(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.BpmProcess> bpmProcessAssignments)
   {
      this.bpmProcessAssignments = bpmProcessAssignments;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.Operation> getFundingOpportunityOperations()
   {
      return this.fundingOpportunityOperations;
   }

   public void setFundingOpportunityOperations(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Operation> fundingOpportunityOperations)
   {
      this.fundingOpportunityOperations = fundingOpportunityOperations;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.StatutoryAuthority> getStatutoryAuthorities()
   {
      return this.statutoryAuthorities;
   }

   public void setStatutoryAuthorities(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.StatutoryAuthority> statutoryAuthorities)
   {
      this.statutoryAuthorities = statutoryAuthorities;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> getTerms()
   {
      return this.terms;
   }

   public void setTerms(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> terms)
   {
      this.terms = terms;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.FOForm> getForms()
   {
      return this.forms;
   }

   public void setForms(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.FOForm> forms)
   {
      this.forms = forms;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.Template> getTemplates()
   {
      return this.templates;
   }

   public void setTemplates(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Template> templates)
   {
      this.templates = templates;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.Template> getAllTemplates()
   {
      return this.allTemplates;
   }

   public void setAllTemplates(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Template> allTemplates)
   {
      this.allTemplates = allTemplates;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.Commitment> getCommitments()
   {
      return this.commitments;
   }

   public void setCommitments(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Commitment> commitments)
   {
      this.commitments = commitments;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.FundingOpportunityAlternateOperation> getAlternateOperations()
   {
      return this.alternateOperations;
   }

   public void setAlternateOperations(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.FundingOpportunityAlternateOperation> alternateOperations)
   {
      this.alternateOperations = alternateOperations;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> getFinanceObligationContacts()
   {
      return this.financeObligationContacts;
   }

   public void setFinanceObligationContacts(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> financeObligationContacts)
   {
      this.financeObligationContacts = financeObligationContacts;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> getGranteeNotificationContacts()
   {
      return this.granteeNotificationContacts;
   }

   public void setGranteeNotificationContacts(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> granteeNotificationContacts)
   {
      this.granteeNotificationContacts = granteeNotificationContacts;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> getSystemBranchChiefContacts()
   {
      return this.systemBranchChiefContacts;
   }

   public void setSystemBranchChiefContacts(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> systemBranchChiefContacts)
   {
      this.systemBranchChiefContacts = systemBranchChiefContacts;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> getGrantsGovContacts()
   {
      return this.grantsGovContacts;
   }

   public void setGrantsGovContacts(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> grantsGovContacts)
   {
      this.grantsGovContacts = grantsGovContacts;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> getFinanceVendorContacts()
   {
      return this.financeVendorContacts;
   }

   public void setFinanceVendorContacts(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> financeVendorContacts)
   {
      this.financeVendorContacts = financeVendorContacts;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> getSigningAuthorityContacts()
   {
      return this.signingAuthorityContacts;
   }

   public void setSigningAuthorityContacts(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> signingAuthorityContacts)
   {
      this.signingAuthorityContacts = signingAuthorityContacts;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> getAlternateSigningAuthorityContacts()
   {
      return this.alternateSigningAuthorityContacts;
   }

   public void setAlternateSigningAuthorityContacts(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> alternateSigningAuthorityContacts)
   {
      this.alternateSigningAuthorityContacts = alternateSigningAuthorityContacts;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> getOtherContacts()
   {
      return this.otherContacts;
   }

   public void setOtherContacts(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> otherContacts)
   {
      this.otherContacts = otherContacts;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> getGrantsManagementBranchContacts()
   {
      return this.grantsManagementBranchContacts;
   }

   public void setGrantsManagementBranchContacts(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> grantsManagementBranchContacts)
   {
      this.grantsManagementBranchContacts = grantsManagementBranchContacts;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> getGrantsCounselContacts()
   {
      return this.grantsCounselContacts;
   }

   public void setGrantsCounselContacts(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> grantsCounselContacts)
   {
      this.grantsCounselContacts = grantsCounselContacts;
   }

   public boolean isInvestmentBased()
   {
      return this.investmentBased;
   }

   public void setInvestmentBased(boolean investmentBased)
   {
      this.investmentBased = investmentBased;
   }

   public java.lang.Integer getMaxInvestmentsPerApplicant()
   {
      return this.maxInvestmentsPerApplicant;
   }

   public void setMaxInvestmentsPerApplicant(
         java.lang.Integer maxInvestmentsPerApplicant)
   {
      this.maxInvestmentsPerApplicant = maxInvestmentsPerApplicant;
   }

   public java.lang.Integer getMaxInvestmentsPerSubApplicant()
   {
      return this.maxInvestmentsPerSubApplicant;
   }

   public void setMaxInvestmentsPerSubApplicant(
         java.lang.Integer maxInvestmentsPerSubApplicant)
   {
      this.maxInvestmentsPerSubApplicant = maxInvestmentsPerSubApplicant;
   }

   public java.lang.String getInvestmentOverviewTitle()
   {
      return this.investmentOverviewTitle;
   }

   public void setInvestmentOverviewTitle(
         java.lang.String investmentOverviewTitle)
   {
      this.investmentOverviewTitle = investmentOverviewTitle;
   }

   public gov.dhs.fema.ndgrants_rules.model.Form getInvestmentOverviewForm()
   {
      return this.investmentOverviewForm;
   }

   public void setInvestmentOverviewForm(
         gov.dhs.fema.ndgrants_rules.model.Form investmentOverviewForm)
   {
      this.investmentOverviewForm = investmentOverviewForm;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.Form> getInvestmentForms()
   {
      return this.investmentForms;
   }

   public void setInvestmentForms(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Form> investmentForms)
   {
      this.investmentForms = investmentForms;
   }

   public java.lang.Integer getApplicationsInUse()
   {
      return this.applicationsInUse;
   }

   public void setApplicationsInUse(java.lang.Integer applicationsInUse)
   {
      this.applicationsInUse = applicationsInUse;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> getAvailableTerms()
   {
      return this.availableTerms;
   }

   public void setAvailableTerms(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> availableTerms)
   {
      this.availableTerms = availableTerms;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.FundingDetailPathFundingStream> getFundingDetailPathFundingStreams()
   {
      return this.fundingDetailPathFundingStreams;
   }

   public void setFundingDetailPathFundingStreams(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.FundingDetailPathFundingStream> fundingDetailPathFundingStreams)
   {
      this.fundingDetailPathFundingStreams = fundingDetailPathFundingStreams;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.FundingOpportunityPublishActionHistory> getFundingOpportunityPublishActionResults()
   {
      return this.fundingOpportunityPublishActionResults;
   }

   public void setFundingOpportunityPublishActionResults(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.FundingOpportunityPublishActionHistory> fundingOpportunityPublishActionResults)
   {
      this.fundingOpportunityPublishActionResults = fundingOpportunityPublishActionResults;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.EligibilityConfigItem> getEligibilityConfigItems()
   {
      return this.eligibilityConfigItems;
   }

   public void setEligibilityConfigItems(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.EligibilityConfigItem> eligibilityConfigItems)
   {
      this.eligibilityConfigItems = eligibilityConfigItems;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.EligibilityConfigItem> getSubAppEligibilityConfigItems()
   {
      return this.subAppEligibilityConfigItems;
   }

   public void setSubAppEligibilityConfigItems(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.EligibilityConfigItem> subAppEligibilityConfigItems)
   {
      this.subAppEligibilityConfigItems = subAppEligibilityConfigItems;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.ModuleRuleSet> getModuleRuleSets()
   {
      return this.moduleRuleSets;
   }

   public void setModuleRuleSets(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.ModuleRuleSet> moduleRuleSets)
   {
      this.moduleRuleSets = moduleRuleSets;
   }

   public boolean isApplicationSubmissionTimerDisplayed()
   {
      return this.applicationSubmissionTimerDisplayed;
   }

   public void setApplicationSubmissionTimerDisplayed(
         boolean applicationSubmissionTimerDisplayed)
   {
      this.applicationSubmissionTimerDisplayed = applicationSubmissionTimerDisplayed;
   }

   public boolean isApplicationPercentageCompletionDisplayed()
   {
      return this.applicationPercentageCompletionDisplayed;
   }

   public void setApplicationPercentageCompletionDisplayed(
         boolean applicationPercentageCompletionDisplayed)
   {
      this.applicationPercentageCompletionDisplayed = applicationPercentageCompletionDisplayed;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.FOForm> getAllForms()
   {
      return this.allForms;
   }

   public void setAllForms(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.FOForm> allForms)
   {
      this.allForms = allForms;
   }

   public FundingOpportunity(
         java.lang.Long fundingOpportunityId,
         java.lang.Long originalFundingOpportunityId,
         gov.dhs.fema.ndgrants_rules.model.Program program,
         java.lang.Integer fiscalYear,
         java.lang.String name,
         java.lang.String description,
         java.lang.String opportunityNo,
         gov.dhs.fema.ndgrants_rules.model.AdminConfigStatus status,
         boolean costSharing,
         java.lang.Integer federalShareRatePct,
         boolean overMatchAllowed,
         boolean allowingApplications,
         gov.dhs.fema.ndgrants_rules.model.User openForApplicationsByUser,
         boolean allowingSubApplicants,
         java.lang.Integer subAppEligibilityTypeId,
         boolean published,
         gov.dhs.fema.ndgrants_rules.model.User publishedByUser,
         java.util.Date publishedOnDate,
         java.lang.String fundingPlanAppSectionTitle,
         java.lang.Long applicationLevel,
         java.lang.Long postAwardLevel,
         java.lang.Long closeoutLevel,
         java.lang.Boolean threeDayCert,
         java.util.Date threeDayCertDate,
         java.lang.Boolean fiveDayRequired,
         java.lang.Boolean fiveDayCert,
         java.util.Date fiveDayCertDate,
         java.lang.String fiveDayRequiredComment,
         java.lang.Long expectedNoOfAwards,
         java.lang.Long grantsGovAwardCeiling,
         java.lang.Long grantsGovAwardFloor,
         java.lang.Long grantsGovEstimatedFunding,
         java.util.Date grantsGovAppStartDate,
         java.util.Date grantsGovAppEndDate,
         java.lang.String grantsGovAppEndDateExplanation,
         java.util.Date grantsGovArchiveDate,
         java.util.Date grantsGovAppPackageStartDate,
         java.util.Date grantsGovAppPackageEndDate,
         java.lang.Integer grantsGovAppPackageGraceDays,
         java.lang.Integer maxApplicationsPerOrganization,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.EligibleApplicantType> eligibleApplicantTypes,
         java.lang.String eligibleApplicantOtherExplanation,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.FundingInstrumentType> fundingInstrumentTypes,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.FundingCategory> fundingCategoryTypes,
         java.lang.String fundingCategoryOtherExplanation,
         java.util.Date applicationSubmissionStartTimestamp,
         java.util.Date applicationSubmissionEndTimestamp,
         java.util.Date applicationSubmissionGraceEndTimestamp,
         gov.dhs.fema.ndgrants_rules.model.PerformanceReportTemplate performanceReportTemplate,
         java.lang.String fundingOpportunityUrl,
         gov.dhs.fema.ndgrants_rules.model.AdministeringOffice administeringOffice,
         gov.dhs.fema.ndgrants_rules.model.FinancialSystem financialSystem,
         gov.dhs.fema.ndgrants_rules.model.PaymentMethod paymentMethod,
         gov.dhs.fema.ndgrants_rules.model.ProjectType projectType,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> fundingOpportunityContacts,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.BpmProcess> bpmProcessAssignments,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Operation> fundingOpportunityOperations,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.StatutoryAuthority> statutoryAuthorities,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> terms,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.FOForm> forms,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Template> templates,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Template> allTemplates,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Commitment> commitments,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.FundingOpportunityAlternateOperation> alternateOperations,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> financeObligationContacts,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> granteeNotificationContacts,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> systemBranchChiefContacts,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> grantsGovContacts,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> financeVendorContacts,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> signingAuthorityContacts,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> alternateSigningAuthorityContacts,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> otherContacts,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> grantsManagementBranchContacts,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> grantsCounselContacts,
         boolean investmentBased,
         java.lang.Integer maxInvestmentsPerApplicant,
         java.lang.Integer maxInvestmentsPerSubApplicant,
         java.lang.String investmentOverviewTitle,
         gov.dhs.fema.ndgrants_rules.model.Form investmentOverviewForm,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Form> investmentForms,
         java.lang.Integer applicationsInUse,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> availableTerms,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.FundingDetailPathFundingStream> fundingDetailPathFundingStreams,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.FundingOpportunityPublishActionHistory> fundingOpportunityPublishActionResults,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.EligibilityConfigItem> eligibilityConfigItems,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.EligibilityConfigItem> subAppEligibilityConfigItems,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.ModuleRuleSet> moduleRuleSets,
         boolean applicationSubmissionTimerDisplayed,
         boolean applicationPercentageCompletionDisplayed,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.FOForm> allForms)
   {
      this.fundingOpportunityId = fundingOpportunityId;
      this.originalFundingOpportunityId = originalFundingOpportunityId;
      this.program = program;
      this.fiscalYear = fiscalYear;
      this.name = name;
      this.description = description;
      this.opportunityNo = opportunityNo;
      this.status = status;
      this.costSharing = costSharing;
      this.federalShareRatePct = federalShareRatePct;
      this.overMatchAllowed = overMatchAllowed;
      this.allowingApplications = allowingApplications;
      this.openForApplicationsByUser = openForApplicationsByUser;
      this.allowingSubApplicants = allowingSubApplicants;
      this.subAppEligibilityTypeId = subAppEligibilityTypeId;
      this.published = published;
      this.publishedByUser = publishedByUser;
      this.publishedOnDate = publishedOnDate;
      this.fundingPlanAppSectionTitle = fundingPlanAppSectionTitle;
      this.applicationLevel = applicationLevel;
      this.postAwardLevel = postAwardLevel;
      this.closeoutLevel = closeoutLevel;
      this.threeDayCert = threeDayCert;
      this.threeDayCertDate = threeDayCertDate;
      this.fiveDayRequired = fiveDayRequired;
      this.fiveDayCert = fiveDayCert;
      this.fiveDayCertDate = fiveDayCertDate;
      this.fiveDayRequiredComment = fiveDayRequiredComment;
      this.expectedNoOfAwards = expectedNoOfAwards;
      this.grantsGovAwardCeiling = grantsGovAwardCeiling;
      this.grantsGovAwardFloor = grantsGovAwardFloor;
      this.grantsGovEstimatedFunding = grantsGovEstimatedFunding;
      this.grantsGovAppStartDate = grantsGovAppStartDate;
      this.grantsGovAppEndDate = grantsGovAppEndDate;
      this.grantsGovAppEndDateExplanation = grantsGovAppEndDateExplanation;
      this.grantsGovArchiveDate = grantsGovArchiveDate;
      this.grantsGovAppPackageStartDate = grantsGovAppPackageStartDate;
      this.grantsGovAppPackageEndDate = grantsGovAppPackageEndDate;
      this.grantsGovAppPackageGraceDays = grantsGovAppPackageGraceDays;
      this.maxApplicationsPerOrganization = maxApplicationsPerOrganization;
      this.eligibleApplicantTypes = eligibleApplicantTypes;
      this.eligibleApplicantOtherExplanation = eligibleApplicantOtherExplanation;
      this.fundingInstrumentTypes = fundingInstrumentTypes;
      this.fundingCategoryTypes = fundingCategoryTypes;
      this.fundingCategoryOtherExplanation = fundingCategoryOtherExplanation;
      this.applicationSubmissionStartTimestamp = applicationSubmissionStartTimestamp;
      this.applicationSubmissionEndTimestamp = applicationSubmissionEndTimestamp;
      this.applicationSubmissionGraceEndTimestamp = applicationSubmissionGraceEndTimestamp;
      this.performanceReportTemplate = performanceReportTemplate;
      this.fundingOpportunityUrl = fundingOpportunityUrl;
      this.administeringOffice = administeringOffice;
      this.financialSystem = financialSystem;
      this.paymentMethod = paymentMethod;
      this.projectType = projectType;
      this.fundingOpportunityContacts = fundingOpportunityContacts;
      this.bpmProcessAssignments = bpmProcessAssignments;
      this.fundingOpportunityOperations = fundingOpportunityOperations;
      this.statutoryAuthorities = statutoryAuthorities;
      this.terms = terms;
      this.forms = forms;
      this.templates = templates;
      this.allTemplates = allTemplates;
      this.commitments = commitments;
      this.alternateOperations = alternateOperations;
      this.financeObligationContacts = financeObligationContacts;
      this.granteeNotificationContacts = granteeNotificationContacts;
      this.systemBranchChiefContacts = systemBranchChiefContacts;
      this.grantsGovContacts = grantsGovContacts;
      this.financeVendorContacts = financeVendorContacts;
      this.signingAuthorityContacts = signingAuthorityContacts;
      this.alternateSigningAuthorityContacts = alternateSigningAuthorityContacts;
      this.otherContacts = otherContacts;
      this.grantsManagementBranchContacts = grantsManagementBranchContacts;
      this.grantsCounselContacts = grantsCounselContacts;
      this.investmentBased = investmentBased;
      this.maxInvestmentsPerApplicant = maxInvestmentsPerApplicant;
      this.maxInvestmentsPerSubApplicant = maxInvestmentsPerSubApplicant;
      this.investmentOverviewTitle = investmentOverviewTitle;
      this.investmentOverviewForm = investmentOverviewForm;
      this.investmentForms = investmentForms;
      this.applicationsInUse = applicationsInUse;
      this.availableTerms = availableTerms;
      this.fundingDetailPathFundingStreams = fundingDetailPathFundingStreams;
      this.fundingOpportunityPublishActionResults = fundingOpportunityPublishActionResults;
      this.eligibilityConfigItems = eligibilityConfigItems;
      this.subAppEligibilityConfigItems = subAppEligibilityConfigItems;
      this.moduleRuleSets = moduleRuleSets;
      this.applicationSubmissionTimerDisplayed = applicationSubmissionTimerDisplayed;
      this.applicationPercentageCompletionDisplayed = applicationPercentageCompletionDisplayed;
      this.allForms = allForms;
   }

}