package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FundingPlanTemplate implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long fundingPlanTemplateId;
   private java.lang.Long origFundingPlanTemplateId;
   private java.lang.String name;
   private java.lang.String alias;
   private java.lang.Long inUseCount;
   private gov.dhs.fema.ndgrants_rules.model.AdminConfigStatus status;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.FPTElement> elements;

   public FundingPlanTemplate()
   {
   }

   public java.lang.Long getFundingPlanTemplateId()
   {
      return this.fundingPlanTemplateId;
   }

   public void setFundingPlanTemplateId(java.lang.Long fundingPlanTemplateId)
   {
      this.fundingPlanTemplateId = fundingPlanTemplateId;
   }

   public java.lang.Long getOrigFundingPlanTemplateId()
   {
      return this.origFundingPlanTemplateId;
   }

   public void setOrigFundingPlanTemplateId(
         java.lang.Long origFundingPlanTemplateId)
   {
      this.origFundingPlanTemplateId = origFundingPlanTemplateId;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getAlias()
   {
      return this.alias;
   }

   public void setAlias(java.lang.String alias)
   {
      this.alias = alias;
   }

   public java.lang.Long getInUseCount()
   {
      return this.inUseCount;
   }

   public void setInUseCount(java.lang.Long inUseCount)
   {
      this.inUseCount = inUseCount;
   }

   public gov.dhs.fema.ndgrants_rules.model.AdminConfigStatus getStatus()
   {
      return this.status;
   }

   public void setStatus(
         gov.dhs.fema.ndgrants_rules.model.AdminConfigStatus status)
   {
      this.status = status;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.FPTElement> getElements()
   {
      return this.elements;
   }

   public void setElements(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.FPTElement> elements)
   {
      this.elements = elements;
   }

   public FundingPlanTemplate(
         java.lang.Long fundingPlanTemplateId,
         java.lang.Long origFundingPlanTemplateId,
         java.lang.String name,
         java.lang.String alias,
         java.lang.Long inUseCount,
         gov.dhs.fema.ndgrants_rules.model.AdminConfigStatus status,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.FPTElement> elements)
   {
      this.fundingPlanTemplateId = fundingPlanTemplateId;
      this.origFundingPlanTemplateId = origFundingPlanTemplateId;
      this.name = name;
      this.alias = alias;
      this.inUseCount = inUseCount;
      this.status = status;
      this.elements = elements;
   }

}