package gov.dhs.fema.ndgrants_rules.model;

import gov.dhs.fema.ndgrants_rules.model.EGPCodedTypeDef;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FundingInstrumentType extends EGPCodedTypeDef implements java.io.Serializable
{

   static final long serialVersionUID = 1L;
   
   public static final FundingInstrumentType GRANT = new FundingInstrumentType(1, "G");
   public static final FundingInstrumentType COOPERATIVE_AGREEMENT = new FundingInstrumentType(2, "CA");
   public static final FundingInstrumentType OTHER = new FundingInstrumentType(3, "O");


   public FundingInstrumentType()
   {
   }
   
   FundingInstrumentType(long id, String code){
       super(id, code);
   }

}