package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FundingDetailPathFundingStream implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long fundingDetailPathFSId;
   private java.lang.Long fundingStreamId;
   private java.lang.Long pathId;
   private java.lang.Long fundingOpportunityId;

   public FundingDetailPathFundingStream()
   {
   }

   public java.lang.Long getFundingDetailPathFSId()
   {
      return this.fundingDetailPathFSId;
   }

   public void setFundingDetailPathFSId(java.lang.Long fundingDetailPathFSId)
   {
      this.fundingDetailPathFSId = fundingDetailPathFSId;
   }

   public java.lang.Long getFundingStreamId()
   {
      return this.fundingStreamId;
   }

   public void setFundingStreamId(java.lang.Long fundingStreamId)
   {
      this.fundingStreamId = fundingStreamId;
   }

   public java.lang.Long getPathId()
   {
      return this.pathId;
   }

   public void setPathId(java.lang.Long pathId)
   {
      this.pathId = pathId;
   }

   public java.lang.Long getFundingOpportunityId()
   {
      return this.fundingOpportunityId;
   }

   public void setFundingOpportunityId(java.lang.Long fundingOpportunityId)
   {
      this.fundingOpportunityId = fundingOpportunityId;
   }

   public FundingDetailPathFundingStream(java.lang.Long fundingDetailPathFSId,
         java.lang.Long fundingStreamId, java.lang.Long pathId,
         java.lang.Long fundingOpportunityId)
   {
      this.fundingDetailPathFSId = fundingDetailPathFSId;
      this.fundingStreamId = fundingStreamId;
      this.pathId = pathId;
      this.fundingOpportunityId = fundingOpportunityId;
   }

}