package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class GrantsGovApplication implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long grantsGovApplicationId;
   private java.lang.String grantsGovTrackingNo;
   private java.lang.String applicationSubmissionType;
   private java.lang.String applicationType;
   private java.lang.String applicationRevision;
   private java.lang.String applicationOther;
   private java.util.Date grantsGovReceivedDate;
   private java.lang.String applicantIdentifier;
   private java.lang.String federalEntityIdentifier;
   private java.lang.String federalAwardIdentifier;
   private java.lang.String stateIdentifier;
   private java.util.Date receivedByState;
   private java.lang.String orgLegalName;
   private java.lang.String einNo;
   private java.lang.String duns;
   private java.lang.String orgStreet1;
   private java.lang.String orgStreet2;
   private java.lang.String orgCity;
   private java.lang.String orgCounty;
   private java.lang.String orgState;
   private java.lang.String orgProvince;
   private java.lang.String orgCountry;
   private java.lang.String orgZip;
   private java.lang.String orgDepartment;
   private java.lang.String orgDivision;
   private java.lang.String contactPrefix;
   private java.lang.String contactFirstName;
   private java.lang.String contactMiddleName;
   private java.lang.String contactLastName;
   private java.lang.String contactSuffix;
   private java.lang.String contactTitle;
   private java.lang.String contactOrgAffiliation;
   private java.lang.String contactPhoneNum;
   private java.lang.String contactFax;
   private java.lang.String contactEmail;
   private java.lang.String applicantType1;
   private java.lang.String applicantType2;
   private java.lang.String applicantType3;
   private java.lang.String applicantTypeOther;
   private java.lang.String federalAgency;
   private java.lang.String cfdaNo;
   private java.lang.String cfdaTitle;
   private java.lang.String fundingOpportunityNo;
   private java.lang.String fundingOpportunityTitle;
   private java.lang.String competitionIdNo;
   private java.lang.String competitionTitle;
   private java.lang.String areasAffected;
   private java.lang.String projectDescriptionTitle;
   private java.lang.String congressionalDistrictApplicant;
   private java.lang.String congressionalDistrictProject;
   private java.util.Date projectPeriodStartDate;
   private java.util.Date projectPeriodEndDate;
   private java.math.BigDecimal estimatedFundingFederal;
   private java.math.BigDecimal estimatedFundingApplicant;
   private java.math.BigDecimal estimatedFundingState;
   private java.math.BigDecimal estimatedFundingLocal;
   private java.math.BigDecimal estimatedFundingOther;
   private java.math.BigDecimal estimatedFundingProgramIncome;
   private java.math.BigDecimal estimatedFundingTotal;
   private java.lang.String eo12372Process;
   private java.util.Date eo12372ApplicationReviewDate;
   private java.lang.String delinquentApplicant;
   private java.lang.String deliquencyExplanation;
   private java.lang.String authRepPrefix;
   private java.lang.String authRepFirstName;
   private java.lang.String authRepMiddleName;
   private java.lang.String authRepLastName;
   private java.lang.String authRepSuffix;
   private java.lang.String authRepTitle;
   private java.lang.String authRepPhoneNum;
   private java.lang.String authRepFax;
   private java.lang.String authRepEmail;
   private java.util.Date downloadedDate;
   private java.lang.String certificationType;
   private java.lang.Long organizationId;
   private gov.dhs.fema.ndgrants_rules.model.Document areasAffectedDocument;
   private gov.dhs.fema.ndgrants_rules.model.Document addCongressionalDistrictProjectDocument;
   private gov.dhs.fema.ndgrants_rules.model.Document deliquencyExplanationDocument;
   private java.lang.String areasAffectedFileName;
   private java.lang.String additionalCongressionalDistrictProjectFileName;
   private java.lang.String deliquencyExplanationFileName;
   private java.lang.String signature;
   private java.util.Date signedDate;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.Document> documents;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.GrantsGovApplicationError> grantsGovApplicationErrors;

   public GrantsGovApplication()
   {
   }

   public java.lang.Long getGrantsGovApplicationId()
   {
      return this.grantsGovApplicationId;
   }

   public void setGrantsGovApplicationId(java.lang.Long grantsGovApplicationId)
   {
      this.grantsGovApplicationId = grantsGovApplicationId;
   }

   public java.lang.String getGrantsGovTrackingNo()
   {
      return this.grantsGovTrackingNo;
   }

   public void setGrantsGovTrackingNo(java.lang.String grantsGovTrackingNo)
   {
      this.grantsGovTrackingNo = grantsGovTrackingNo;
   }

   public java.lang.String getApplicationSubmissionType()
   {
      return this.applicationSubmissionType;
   }

   public void setApplicationSubmissionType(
         java.lang.String applicationSubmissionType)
   {
      this.applicationSubmissionType = applicationSubmissionType;
   }

   public java.lang.String getApplicationType()
   {
      return this.applicationType;
   }

   public void setApplicationType(java.lang.String applicationType)
   {
      this.applicationType = applicationType;
   }

   public java.lang.String getApplicationRevision()
   {
      return this.applicationRevision;
   }

   public void setApplicationRevision(java.lang.String applicationRevision)
   {
      this.applicationRevision = applicationRevision;
   }

   public java.lang.String getApplicationOther()
   {
      return this.applicationOther;
   }

   public void setApplicationOther(java.lang.String applicationOther)
   {
      this.applicationOther = applicationOther;
   }

   public java.util.Date getGrantsGovReceivedDate()
   {
      return this.grantsGovReceivedDate;
   }

   public void setGrantsGovReceivedDate(java.util.Date grantsGovReceivedDate)
   {
      this.grantsGovReceivedDate = grantsGovReceivedDate;
   }

   public java.lang.String getApplicantIdentifier()
   {
      return this.applicantIdentifier;
   }

   public void setApplicantIdentifier(java.lang.String applicantIdentifier)
   {
      this.applicantIdentifier = applicantIdentifier;
   }

   public java.lang.String getFederalEntityIdentifier()
   {
      return this.federalEntityIdentifier;
   }

   public void setFederalEntityIdentifier(
         java.lang.String federalEntityIdentifier)
   {
      this.federalEntityIdentifier = federalEntityIdentifier;
   }

   public java.lang.String getFederalAwardIdentifier()
   {
      return this.federalAwardIdentifier;
   }

   public void setFederalAwardIdentifier(
         java.lang.String federalAwardIdentifier)
   {
      this.federalAwardIdentifier = federalAwardIdentifier;
   }

   public java.lang.String getStateIdentifier()
   {
      return this.stateIdentifier;
   }

   public void setStateIdentifier(java.lang.String stateIdentifier)
   {
      this.stateIdentifier = stateIdentifier;
   }

   public java.util.Date getReceivedByState()
   {
      return this.receivedByState;
   }

   public void setReceivedByState(java.util.Date receivedByState)
   {
      this.receivedByState = receivedByState;
   }

   public java.lang.String getOrgLegalName()
   {
      return this.orgLegalName;
   }

   public void setOrgLegalName(java.lang.String orgLegalName)
   {
      this.orgLegalName = orgLegalName;
   }

   public java.lang.String getEinNo()
   {
      return this.einNo;
   }

   public void setEinNo(java.lang.String einNo)
   {
      this.einNo = einNo;
   }

   public java.lang.String getDuns()
   {
      return this.duns;
   }

   public void setDuns(java.lang.String duns)
   {
      this.duns = duns;
   }

   public java.lang.String getOrgStreet1()
   {
      return this.orgStreet1;
   }

   public void setOrgStreet1(java.lang.String orgStreet1)
   {
      this.orgStreet1 = orgStreet1;
   }

   public java.lang.String getOrgStreet2()
   {
      return this.orgStreet2;
   }

   public void setOrgStreet2(java.lang.String orgStreet2)
   {
      this.orgStreet2 = orgStreet2;
   }

   public java.lang.String getOrgCity()
   {
      return this.orgCity;
   }

   public void setOrgCity(java.lang.String orgCity)
   {
      this.orgCity = orgCity;
   }

   public java.lang.String getOrgCounty()
   {
      return this.orgCounty;
   }

   public void setOrgCounty(java.lang.String orgCounty)
   {
      this.orgCounty = orgCounty;
   }

   public java.lang.String getOrgState()
   {
      return this.orgState;
   }

   public void setOrgState(java.lang.String orgState)
   {
      this.orgState = orgState;
   }

   public java.lang.String getOrgProvince()
   {
      return this.orgProvince;
   }

   public void setOrgProvince(java.lang.String orgProvince)
   {
      this.orgProvince = orgProvince;
   }

   public java.lang.String getOrgCountry()
   {
      return this.orgCountry;
   }

   public void setOrgCountry(java.lang.String orgCountry)
   {
      this.orgCountry = orgCountry;
   }

   public java.lang.String getOrgZip()
   {
      return this.orgZip;
   }

   public void setOrgZip(java.lang.String orgZip)
   {
      this.orgZip = orgZip;
   }

   public java.lang.String getOrgDepartment()
   {
      return this.orgDepartment;
   }

   public void setOrgDepartment(java.lang.String orgDepartment)
   {
      this.orgDepartment = orgDepartment;
   }

   public java.lang.String getOrgDivision()
   {
      return this.orgDivision;
   }

   public void setOrgDivision(java.lang.String orgDivision)
   {
      this.orgDivision = orgDivision;
   }

   public java.lang.String getContactPrefix()
   {
      return this.contactPrefix;
   }

   public void setContactPrefix(java.lang.String contactPrefix)
   {
      this.contactPrefix = contactPrefix;
   }

   public java.lang.String getContactFirstName()
   {
      return this.contactFirstName;
   }

   public void setContactFirstName(java.lang.String contactFirstName)
   {
      this.contactFirstName = contactFirstName;
   }

   public java.lang.String getContactMiddleName()
   {
      return this.contactMiddleName;
   }

   public void setContactMiddleName(java.lang.String contactMiddleName)
   {
      this.contactMiddleName = contactMiddleName;
   }

   public java.lang.String getContactLastName()
   {
      return this.contactLastName;
   }

   public void setContactLastName(java.lang.String contactLastName)
   {
      this.contactLastName = contactLastName;
   }

   public java.lang.String getContactSuffix()
   {
      return this.contactSuffix;
   }

   public void setContactSuffix(java.lang.String contactSuffix)
   {
      this.contactSuffix = contactSuffix;
   }

   public java.lang.String getContactTitle()
   {
      return this.contactTitle;
   }

   public void setContactTitle(java.lang.String contactTitle)
   {
      this.contactTitle = contactTitle;
   }

   public java.lang.String getContactOrgAffiliation()
   {
      return this.contactOrgAffiliation;
   }

   public void setContactOrgAffiliation(java.lang.String contactOrgAffiliation)
   {
      this.contactOrgAffiliation = contactOrgAffiliation;
   }

   public java.lang.String getContactPhoneNum()
   {
      return this.contactPhoneNum;
   }

   public void setContactPhoneNum(java.lang.String contactPhoneNum)
   {
      this.contactPhoneNum = contactPhoneNum;
   }

   public java.lang.String getContactFax()
   {
      return this.contactFax;
   }

   public void setContactFax(java.lang.String contactFax)
   {
      this.contactFax = contactFax;
   }

   public java.lang.String getContactEmail()
   {
      return this.contactEmail;
   }

   public void setContactEmail(java.lang.String contactEmail)
   {
      this.contactEmail = contactEmail;
   }

   public java.lang.String getApplicantType1()
   {
      return this.applicantType1;
   }

   public void setApplicantType1(java.lang.String applicantType1)
   {
      this.applicantType1 = applicantType1;
   }

   public java.lang.String getApplicantType2()
   {
      return this.applicantType2;
   }

   public void setApplicantType2(java.lang.String applicantType2)
   {
      this.applicantType2 = applicantType2;
   }

   public java.lang.String getApplicantType3()
   {
      return this.applicantType3;
   }

   public void setApplicantType3(java.lang.String applicantType3)
   {
      this.applicantType3 = applicantType3;
   }

   public java.lang.String getApplicantTypeOther()
   {
      return this.applicantTypeOther;
   }

   public void setApplicantTypeOther(java.lang.String applicantTypeOther)
   {
      this.applicantTypeOther = applicantTypeOther;
   }

   public java.lang.String getFederalAgency()
   {
      return this.federalAgency;
   }

   public void setFederalAgency(java.lang.String federalAgency)
   {
      this.federalAgency = federalAgency;
   }

   public java.lang.String getCfdaNo()
   {
      return this.cfdaNo;
   }

   public void setCfdaNo(java.lang.String cfdaNo)
   {
      this.cfdaNo = cfdaNo;
   }

   public java.lang.String getCfdaTitle()
   {
      return this.cfdaTitle;
   }

   public void setCfdaTitle(java.lang.String cfdaTitle)
   {
      this.cfdaTitle = cfdaTitle;
   }

   public java.lang.String getFundingOpportunityNo()
   {
      return this.fundingOpportunityNo;
   }

   public void setFundingOpportunityNo(java.lang.String fundingOpportunityNo)
   {
      this.fundingOpportunityNo = fundingOpportunityNo;
   }

   public java.lang.String getFundingOpportunityTitle()
   {
      return this.fundingOpportunityTitle;
   }

   public void setFundingOpportunityTitle(
         java.lang.String fundingOpportunityTitle)
   {
      this.fundingOpportunityTitle = fundingOpportunityTitle;
   }

   public java.lang.String getCompetitionIdNo()
   {
      return this.competitionIdNo;
   }

   public void setCompetitionIdNo(java.lang.String competitionIdNo)
   {
      this.competitionIdNo = competitionIdNo;
   }

   public java.lang.String getCompetitionTitle()
   {
      return this.competitionTitle;
   }

   public void setCompetitionTitle(java.lang.String competitionTitle)
   {
      this.competitionTitle = competitionTitle;
   }

   public java.lang.String getAreasAffected()
   {
      return this.areasAffected;
   }

   public void setAreasAffected(java.lang.String areasAffected)
   {
      this.areasAffected = areasAffected;
   }

   public java.lang.String getProjectDescriptionTitle()
   {
      return this.projectDescriptionTitle;
   }

   public void setProjectDescriptionTitle(
         java.lang.String projectDescriptionTitle)
   {
      this.projectDescriptionTitle = projectDescriptionTitle;
   }

   public java.lang.String getCongressionalDistrictApplicant()
   {
      return this.congressionalDistrictApplicant;
   }

   public void setCongressionalDistrictApplicant(
         java.lang.String congressionalDistrictApplicant)
   {
      this.congressionalDistrictApplicant = congressionalDistrictApplicant;
   }

   public java.lang.String getCongressionalDistrictProject()
   {
      return this.congressionalDistrictProject;
   }

   public void setCongressionalDistrictProject(
         java.lang.String congressionalDistrictProject)
   {
      this.congressionalDistrictProject = congressionalDistrictProject;
   }

   public java.util.Date getProjectPeriodStartDate()
   {
      return this.projectPeriodStartDate;
   }

   public void setProjectPeriodStartDate(java.util.Date projectPeriodStartDate)
   {
      this.projectPeriodStartDate = projectPeriodStartDate;
   }

   public java.util.Date getProjectPeriodEndDate()
   {
      return this.projectPeriodEndDate;
   }

   public void setProjectPeriodEndDate(java.util.Date projectPeriodEndDate)
   {
      this.projectPeriodEndDate = projectPeriodEndDate;
   }

   public java.math.BigDecimal getEstimatedFundingFederal()
   {
      return this.estimatedFundingFederal;
   }

   public void setEstimatedFundingFederal(
         java.math.BigDecimal estimatedFundingFederal)
   {
      this.estimatedFundingFederal = estimatedFundingFederal;
   }

   public java.math.BigDecimal getEstimatedFundingApplicant()
   {
      return this.estimatedFundingApplicant;
   }

   public void setEstimatedFundingApplicant(
         java.math.BigDecimal estimatedFundingApplicant)
   {
      this.estimatedFundingApplicant = estimatedFundingApplicant;
   }

   public java.math.BigDecimal getEstimatedFundingState()
   {
      return this.estimatedFundingState;
   }

   public void setEstimatedFundingState(
         java.math.BigDecimal estimatedFundingState)
   {
      this.estimatedFundingState = estimatedFundingState;
   }

   public java.math.BigDecimal getEstimatedFundingLocal()
   {
      return this.estimatedFundingLocal;
   }

   public void setEstimatedFundingLocal(
         java.math.BigDecimal estimatedFundingLocal)
   {
      this.estimatedFundingLocal = estimatedFundingLocal;
   }

   public java.math.BigDecimal getEstimatedFundingOther()
   {
      return this.estimatedFundingOther;
   }

   public void setEstimatedFundingOther(
         java.math.BigDecimal estimatedFundingOther)
   {
      this.estimatedFundingOther = estimatedFundingOther;
   }

   public java.math.BigDecimal getEstimatedFundingProgramIncome()
   {
      return this.estimatedFundingProgramIncome;
   }

   public void setEstimatedFundingProgramIncome(
         java.math.BigDecimal estimatedFundingProgramIncome)
   {
      this.estimatedFundingProgramIncome = estimatedFundingProgramIncome;
   }

   public java.math.BigDecimal getEstimatedFundingTotal()
   {
      return this.estimatedFundingTotal;
   }

   public void setEstimatedFundingTotal(
         java.math.BigDecimal estimatedFundingTotal)
   {
      this.estimatedFundingTotal = estimatedFundingTotal;
   }

   public java.lang.String getEo12372Process()
   {
      return this.eo12372Process;
   }

   public void setEo12372Process(java.lang.String eo12372Process)
   {
      this.eo12372Process = eo12372Process;
   }

   public java.util.Date getEo12372ApplicationReviewDate()
   {
      return this.eo12372ApplicationReviewDate;
   }

   public void setEo12372ApplicationReviewDate(
         java.util.Date eo12372ApplicationReviewDate)
   {
      this.eo12372ApplicationReviewDate = eo12372ApplicationReviewDate;
   }

   public java.lang.String getDelinquentApplicant()
   {
      return this.delinquentApplicant;
   }

   public void setDelinquentApplicant(java.lang.String delinquentApplicant)
   {
      this.delinquentApplicant = delinquentApplicant;
   }

   public java.lang.String getDeliquencyExplanation()
   {
      return this.deliquencyExplanation;
   }

   public void setDeliquencyExplanation(java.lang.String deliquencyExplanation)
   {
      this.deliquencyExplanation = deliquencyExplanation;
   }

   public java.lang.String getAuthRepPrefix()
   {
      return this.authRepPrefix;
   }

   public void setAuthRepPrefix(java.lang.String authRepPrefix)
   {
      this.authRepPrefix = authRepPrefix;
   }

   public java.lang.String getAuthRepFirstName()
   {
      return this.authRepFirstName;
   }

   public void setAuthRepFirstName(java.lang.String authRepFirstName)
   {
      this.authRepFirstName = authRepFirstName;
   }

   public java.lang.String getAuthRepMiddleName()
   {
      return this.authRepMiddleName;
   }

   public void setAuthRepMiddleName(java.lang.String authRepMiddleName)
   {
      this.authRepMiddleName = authRepMiddleName;
   }

   public java.lang.String getAuthRepLastName()
   {
      return this.authRepLastName;
   }

   public void setAuthRepLastName(java.lang.String authRepLastName)
   {
      this.authRepLastName = authRepLastName;
   }

   public java.lang.String getAuthRepSuffix()
   {
      return this.authRepSuffix;
   }

   public void setAuthRepSuffix(java.lang.String authRepSuffix)
   {
      this.authRepSuffix = authRepSuffix;
   }

   public java.lang.String getAuthRepTitle()
   {
      return this.authRepTitle;
   }

   public void setAuthRepTitle(java.lang.String authRepTitle)
   {
      this.authRepTitle = authRepTitle;
   }

   public java.lang.String getAuthRepPhoneNum()
   {
      return this.authRepPhoneNum;
   }

   public void setAuthRepPhoneNum(java.lang.String authRepPhoneNum)
   {
      this.authRepPhoneNum = authRepPhoneNum;
   }

   public java.lang.String getAuthRepFax()
   {
      return this.authRepFax;
   }

   public void setAuthRepFax(java.lang.String authRepFax)
   {
      this.authRepFax = authRepFax;
   }

   public java.lang.String getAuthRepEmail()
   {
      return this.authRepEmail;
   }

   public void setAuthRepEmail(java.lang.String authRepEmail)
   {
      this.authRepEmail = authRepEmail;
   }

   public java.util.Date getDownloadedDate()
   {
      return this.downloadedDate;
   }

   public void setDownloadedDate(java.util.Date downloadedDate)
   {
      this.downloadedDate = downloadedDate;
   }

   public java.lang.String getCertificationType()
   {
      return this.certificationType;
   }

   public void setCertificationType(java.lang.String certificationType)
   {
      this.certificationType = certificationType;
   }

   public java.lang.Long getOrganizationId()
   {
      return this.organizationId;
   }

   public void setOrganizationId(java.lang.Long organizationId)
   {
      this.organizationId = organizationId;
   }

   public gov.dhs.fema.ndgrants_rules.model.Document getAreasAffectedDocument()
   {
      return this.areasAffectedDocument;
   }

   public void setAreasAffectedDocument(
         gov.dhs.fema.ndgrants_rules.model.Document areasAffectedDocument)
   {
      this.areasAffectedDocument = areasAffectedDocument;
   }

   public gov.dhs.fema.ndgrants_rules.model.Document getAddCongressionalDistrictProjectDocument()
   {
      return this.addCongressionalDistrictProjectDocument;
   }

   public void setAddCongressionalDistrictProjectDocument(
         gov.dhs.fema.ndgrants_rules.model.Document addCongressionalDistrictProjectDocument)
   {
      this.addCongressionalDistrictProjectDocument = addCongressionalDistrictProjectDocument;
   }

   public gov.dhs.fema.ndgrants_rules.model.Document getDeliquencyExplanationDocument()
   {
      return this.deliquencyExplanationDocument;
   }

   public void setDeliquencyExplanationDocument(
         gov.dhs.fema.ndgrants_rules.model.Document deliquencyExplanationDocument)
   {
      this.deliquencyExplanationDocument = deliquencyExplanationDocument;
   }

   public java.lang.String getAreasAffectedFileName()
   {
      return this.areasAffectedFileName;
   }

   public void setAreasAffectedFileName(java.lang.String areasAffectedFileName)
   {
      this.areasAffectedFileName = areasAffectedFileName;
   }

   public java.lang.String getAdditionalCongressionalDistrictProjectFileName()
   {
      return this.additionalCongressionalDistrictProjectFileName;
   }

   public void setAdditionalCongressionalDistrictProjectFileName(
         java.lang.String additionalCongressionalDistrictProjectFileName)
   {
      this.additionalCongressionalDistrictProjectFileName = additionalCongressionalDistrictProjectFileName;
   }

   public java.lang.String getDeliquencyExplanationFileName()
   {
      return this.deliquencyExplanationFileName;
   }

   public void setDeliquencyExplanationFileName(
         java.lang.String deliquencyExplanationFileName)
   {
      this.deliquencyExplanationFileName = deliquencyExplanationFileName;
   }

   public java.lang.String getSignature()
   {
      return this.signature;
   }

   public void setSignature(java.lang.String signature)
   {
      this.signature = signature;
   }

   public java.util.Date getSignedDate()
   {
      return this.signedDate;
   }

   public void setSignedDate(java.util.Date signedDate)
   {
      this.signedDate = signedDate;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.Document> getDocuments()
   {
      return this.documents;
   }

   public void setDocuments(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Document> documents)
   {
      this.documents = documents;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.GrantsGovApplicationError> getGrantsGovApplicationErrors()
   {
      return this.grantsGovApplicationErrors;
   }

   public void setGrantsGovApplicationErrors(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.GrantsGovApplicationError> grantsGovApplicationErrors)
   {
      this.grantsGovApplicationErrors = grantsGovApplicationErrors;
   }

   public GrantsGovApplication(
         java.lang.Long grantsGovApplicationId,
         java.lang.String grantsGovTrackingNo,
         java.lang.String applicationSubmissionType,
         java.lang.String applicationType,
         java.lang.String applicationRevision,
         java.lang.String applicationOther,
         java.util.Date grantsGovReceivedDate,
         java.lang.String applicantIdentifier,
         java.lang.String federalEntityIdentifier,
         java.lang.String federalAwardIdentifier,
         java.lang.String stateIdentifier,
         java.util.Date receivedByState,
         java.lang.String orgLegalName,
         java.lang.String einNo,
         java.lang.String duns,
         java.lang.String orgStreet1,
         java.lang.String orgStreet2,
         java.lang.String orgCity,
         java.lang.String orgCounty,
         java.lang.String orgState,
         java.lang.String orgProvince,
         java.lang.String orgCountry,
         java.lang.String orgZip,
         java.lang.String orgDepartment,
         java.lang.String orgDivision,
         java.lang.String contactPrefix,
         java.lang.String contactFirstName,
         java.lang.String contactMiddleName,
         java.lang.String contactLastName,
         java.lang.String contactSuffix,
         java.lang.String contactTitle,
         java.lang.String contactOrgAffiliation,
         java.lang.String contactPhoneNum,
         java.lang.String contactFax,
         java.lang.String contactEmail,
         java.lang.String applicantType1,
         java.lang.String applicantType2,
         java.lang.String applicantType3,
         java.lang.String applicantTypeOther,
         java.lang.String federalAgency,
         java.lang.String cfdaNo,
         java.lang.String cfdaTitle,
         java.lang.String fundingOpportunityNo,
         java.lang.String fundingOpportunityTitle,
         java.lang.String competitionIdNo,
         java.lang.String competitionTitle,
         java.lang.String areasAffected,
         java.lang.String projectDescriptionTitle,
         java.lang.String congressionalDistrictApplicant,
         java.lang.String congressionalDistrictProject,
         java.util.Date projectPeriodStartDate,
         java.util.Date projectPeriodEndDate,
         java.math.BigDecimal estimatedFundingFederal,
         java.math.BigDecimal estimatedFundingApplicant,
         java.math.BigDecimal estimatedFundingState,
         java.math.BigDecimal estimatedFundingLocal,
         java.math.BigDecimal estimatedFundingOther,
         java.math.BigDecimal estimatedFundingProgramIncome,
         java.math.BigDecimal estimatedFundingTotal,
         java.lang.String eo12372Process,
         java.util.Date eo12372ApplicationReviewDate,
         java.lang.String delinquentApplicant,
         java.lang.String deliquencyExplanation,
         java.lang.String authRepPrefix,
         java.lang.String authRepFirstName,
         java.lang.String authRepMiddleName,
         java.lang.String authRepLastName,
         java.lang.String authRepSuffix,
         java.lang.String authRepTitle,
         java.lang.String authRepPhoneNum,
         java.lang.String authRepFax,
         java.lang.String authRepEmail,
         java.util.Date downloadedDate,
         java.lang.String certificationType,
         java.lang.Long organizationId,
         gov.dhs.fema.ndgrants_rules.model.Document areasAffectedDocument,
         gov.dhs.fema.ndgrants_rules.model.Document addCongressionalDistrictProjectDocument,
         gov.dhs.fema.ndgrants_rules.model.Document deliquencyExplanationDocument,
         java.lang.String areasAffectedFileName,
         java.lang.String additionalCongressionalDistrictProjectFileName,
         java.lang.String deliquencyExplanationFileName,
         java.lang.String signature,
         java.util.Date signedDate,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Document> documents,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.GrantsGovApplicationError> grantsGovApplicationErrors)
   {
      this.grantsGovApplicationId = grantsGovApplicationId;
      this.grantsGovTrackingNo = grantsGovTrackingNo;
      this.applicationSubmissionType = applicationSubmissionType;
      this.applicationType = applicationType;
      this.applicationRevision = applicationRevision;
      this.applicationOther = applicationOther;
      this.grantsGovReceivedDate = grantsGovReceivedDate;
      this.applicantIdentifier = applicantIdentifier;
      this.federalEntityIdentifier = federalEntityIdentifier;
      this.federalAwardIdentifier = federalAwardIdentifier;
      this.stateIdentifier = stateIdentifier;
      this.receivedByState = receivedByState;
      this.orgLegalName = orgLegalName;
      this.einNo = einNo;
      this.duns = duns;
      this.orgStreet1 = orgStreet1;
      this.orgStreet2 = orgStreet2;
      this.orgCity = orgCity;
      this.orgCounty = orgCounty;
      this.orgState = orgState;
      this.orgProvince = orgProvince;
      this.orgCountry = orgCountry;
      this.orgZip = orgZip;
      this.orgDepartment = orgDepartment;
      this.orgDivision = orgDivision;
      this.contactPrefix = contactPrefix;
      this.contactFirstName = contactFirstName;
      this.contactMiddleName = contactMiddleName;
      this.contactLastName = contactLastName;
      this.contactSuffix = contactSuffix;
      this.contactTitle = contactTitle;
      this.contactOrgAffiliation = contactOrgAffiliation;
      this.contactPhoneNum = contactPhoneNum;
      this.contactFax = contactFax;
      this.contactEmail = contactEmail;
      this.applicantType1 = applicantType1;
      this.applicantType2 = applicantType2;
      this.applicantType3 = applicantType3;
      this.applicantTypeOther = applicantTypeOther;
      this.federalAgency = federalAgency;
      this.cfdaNo = cfdaNo;
      this.cfdaTitle = cfdaTitle;
      this.fundingOpportunityNo = fundingOpportunityNo;
      this.fundingOpportunityTitle = fundingOpportunityTitle;
      this.competitionIdNo = competitionIdNo;
      this.competitionTitle = competitionTitle;
      this.areasAffected = areasAffected;
      this.projectDescriptionTitle = projectDescriptionTitle;
      this.congressionalDistrictApplicant = congressionalDistrictApplicant;
      this.congressionalDistrictProject = congressionalDistrictProject;
      this.projectPeriodStartDate = projectPeriodStartDate;
      this.projectPeriodEndDate = projectPeriodEndDate;
      this.estimatedFundingFederal = estimatedFundingFederal;
      this.estimatedFundingApplicant = estimatedFundingApplicant;
      this.estimatedFundingState = estimatedFundingState;
      this.estimatedFundingLocal = estimatedFundingLocal;
      this.estimatedFundingOther = estimatedFundingOther;
      this.estimatedFundingProgramIncome = estimatedFundingProgramIncome;
      this.estimatedFundingTotal = estimatedFundingTotal;
      this.eo12372Process = eo12372Process;
      this.eo12372ApplicationReviewDate = eo12372ApplicationReviewDate;
      this.delinquentApplicant = delinquentApplicant;
      this.deliquencyExplanation = deliquencyExplanation;
      this.authRepPrefix = authRepPrefix;
      this.authRepFirstName = authRepFirstName;
      this.authRepMiddleName = authRepMiddleName;
      this.authRepLastName = authRepLastName;
      this.authRepSuffix = authRepSuffix;
      this.authRepTitle = authRepTitle;
      this.authRepPhoneNum = authRepPhoneNum;
      this.authRepFax = authRepFax;
      this.authRepEmail = authRepEmail;
      this.downloadedDate = downloadedDate;
      this.certificationType = certificationType;
      this.organizationId = organizationId;
      this.areasAffectedDocument = areasAffectedDocument;
      this.addCongressionalDistrictProjectDocument = addCongressionalDistrictProjectDocument;
      this.deliquencyExplanationDocument = deliquencyExplanationDocument;
      this.areasAffectedFileName = areasAffectedFileName;
      this.additionalCongressionalDistrictProjectFileName = additionalCongressionalDistrictProjectFileName;
      this.deliquencyExplanationFileName = deliquencyExplanationFileName;
      this.signature = signature;
      this.signedDate = signedDate;
      this.documents = documents;
      this.grantsGovApplicationErrors = grantsGovApplicationErrors;
   }

}