package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Grant implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long grantId;
   private java.lang.String grantNo;
   private java.lang.Long transactionSeqNumber;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424CBudget> sf424CBudgets;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.ExternalAdminContact> contacts;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> terms;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.CommitmentAmount> commitmentAmounts;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.Document> grantDocuments;
   private gov.dhs.fema.ndgrants_rules.model.BudgetAndPop budgetAndPop;
   private gov.dhs.fema.ndgrants_rules.model.Organization organization;
   private java.math.BigDecimal totalCommitments;
   private java.math.BigDecimal conditionalFederal;
   private java.math.BigDecimal conditionalNonFederal;
   private java.math.BigDecimal totalConditionalProjectCost;

   private gov.dhs.fema.ndgrants_rules.model.Vendor vendor;

   private java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424ABudget> sf424ABudgets;

   public Grant()
   {
   }

   public java.lang.Long getGrantId()
   {
      return this.grantId;
   }

   public void setGrantId(java.lang.Long grantId)
   {
      this.grantId = grantId;
   }

   public java.lang.String getGrantNo()
   {
      return this.grantNo;
   }

   public void setGrantNo(java.lang.String grantNo)
   {
      this.grantNo = grantNo;
   }

   public java.lang.Long getTransactionSeqNumber()
   {
      return this.transactionSeqNumber;
   }

   public void setTransactionSeqNumber(java.lang.Long transactionSeqNumber)
   {
      this.transactionSeqNumber = transactionSeqNumber;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424CBudget> getSf424CBudgets()
   {
      return this.sf424CBudgets;
   }

   public void setSf424CBudgets(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424CBudget> sf424CBudgets)
   {
      this.sf424CBudgets = sf424CBudgets;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.ExternalAdminContact> getContacts()
   {
      return this.contacts;
   }

   public void setContacts(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.ExternalAdminContact> contacts)
   {
      this.contacts = contacts;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> getTerms()
   {
      return this.terms;
   }

   public void setTerms(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> terms)
   {
      this.terms = terms;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.CommitmentAmount> getCommitmentAmounts()
   {
      return this.commitmentAmounts;
   }

   public void setCommitmentAmounts(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.CommitmentAmount> commitmentAmounts)
   {
      this.commitmentAmounts = commitmentAmounts;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.Document> getGrantDocuments()
   {
      return this.grantDocuments;
   }

   public void setGrantDocuments(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Document> grantDocuments)
   {
      this.grantDocuments = grantDocuments;
   }

   public gov.dhs.fema.ndgrants_rules.model.BudgetAndPop getBudgetAndPop()
   {
      return this.budgetAndPop;
   }

   public void setBudgetAndPop(
         gov.dhs.fema.ndgrants_rules.model.BudgetAndPop budgetAndPop)
   {
      this.budgetAndPop = budgetAndPop;
   }

   public gov.dhs.fema.ndgrants_rules.model.Organization getOrganization()
   {
      return this.organization;
   }

   public void setOrganization(
         gov.dhs.fema.ndgrants_rules.model.Organization organization)
   {
      this.organization = organization;
   }

   public java.math.BigDecimal getTotalCommitments()
   {
      return this.totalCommitments;
   }

   public void setTotalCommitments(java.math.BigDecimal totalCommitments)
   {
      this.totalCommitments = totalCommitments;
   }

   public java.math.BigDecimal getConditionalFederal()
   {
      return this.conditionalFederal;
   }

   public void setConditionalFederal(java.math.BigDecimal conditionalFederal)
   {
      this.conditionalFederal = conditionalFederal;
   }

   public java.math.BigDecimal getConditionalNonFederal()
   {
      return this.conditionalNonFederal;
   }

   public void setConditionalNonFederal(
         java.math.BigDecimal conditionalNonFederal)
   {
      this.conditionalNonFederal = conditionalNonFederal;
   }

   public java.math.BigDecimal getTotalConditionalProjectCost()
   {
      return this.totalConditionalProjectCost;
   }

   public void setTotalConditionalProjectCost(
         java.math.BigDecimal totalConditionalProjectCost)
   {
      this.totalConditionalProjectCost = totalConditionalProjectCost;
   }

   public gov.dhs.fema.ndgrants_rules.model.Vendor getVendor()
   {
      return this.vendor;
   }

   public void setVendor(gov.dhs.fema.ndgrants_rules.model.Vendor vendor)
   {
      this.vendor = vendor;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424ABudget> getSf424ABudgets()
   {
      return this.sf424ABudgets;
   }

   public void setSf424ABudgets(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424ABudget> sf424ABudgets)
   {
      this.sf424ABudgets = sf424ABudgets;
   }

   public Grant(
         java.lang.Long grantId,
         java.lang.String grantNo,
         java.lang.Long transactionSeqNumber,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424CBudget> sf424CBudgets,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.ExternalAdminContact> contacts,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> terms,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.CommitmentAmount> commitmentAmounts,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Document> grantDocuments,
         gov.dhs.fema.ndgrants_rules.model.BudgetAndPop budgetAndPop,
         gov.dhs.fema.ndgrants_rules.model.Organization organization,
         java.math.BigDecimal totalCommitments,
         java.math.BigDecimal conditionalFederal,
         java.math.BigDecimal conditionalNonFederal,
         java.math.BigDecimal totalConditionalProjectCost,
         gov.dhs.fema.ndgrants_rules.model.Vendor vendor,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.SF424ABudget> sf424ABudgets)
   {
      this.grantId = grantId;
      this.grantNo = grantNo;
      this.transactionSeqNumber = transactionSeqNumber;
      this.sf424CBudgets = sf424CBudgets;
      this.contacts = contacts;
      this.terms = terms;
      this.commitmentAmounts = commitmentAmounts;
      this.grantDocuments = grantDocuments;
      this.budgetAndPop = budgetAndPop;
      this.organization = organization;
      this.totalCommitments = totalCommitments;
      this.conditionalFederal = conditionalFederal;
      this.conditionalNonFederal = conditionalNonFederal;
      this.totalConditionalProjectCost = totalConditionalProjectCost;
      this.vendor = vendor;
      this.sf424ABudgets = sf424ABudgets;
   }

}