package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class GranteeOrganizationRole implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private boolean selected;
   private boolean orgAdmin;

   public GranteeOrganizationRole()
   {
   }

   public boolean isSelected()
   {
      return this.selected;
   }

   public void setSelected(boolean selected)
   {
      this.selected = selected;
   }

   public boolean isOrgAdmin()
   {
      return this.orgAdmin;
   }

   public void setOrgAdmin(boolean orgAdmin)
   {
      this.orgAdmin = orgAdmin;
   }

   public GranteeOrganizationRole(boolean selected, boolean orgAdmin)
   {
      this.selected = selected;
      this.orgAdmin = orgAdmin;
   }

}