package gov.dhs.fema.ndgrants_rules.model;

import gov.dhs.fema.ndgrants_rules.model.EGPTypeDef;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class GrantsGovPublishType extends EGPTypeDef implements java.io.Serializable
{

   static final long serialVersionUID = 1L;
   
   public static final GrantsGovPublishType CREATE_SYNOPSIS = new GrantsGovPublishType(1);
   public static final GrantsGovPublishType UPDATE_SYNOPSIS = new GrantsGovPublishType(2);
   public static final GrantsGovPublishType MANUAL_SYNOPSIS = new GrantsGovPublishType(3);

   public GrantsGovPublishType()
   {
   }
   
   GrantsGovPublishType(long id){
       super(id);
   }

}