package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class GrantorOrganization implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long grantorOrganizationId;
   private java.lang.Long originalOrgId;
   private java.lang.String legalName;
   private gov.dhs.fema.ndgrants_rules.model.Address physicalAddress;
   private gov.dhs.fema.ndgrants_rules.model.Address mailingAddress;
   private java.lang.String opportunityIdAcronym;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> grantorOrganizationContacts;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> grantorOrganizationTerms;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.Template> grantorOrganizationTemplates;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> inheritedTerms;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.Template> inheritedTemplates;
   private gov.dhs.fema.ndgrants_rules.model.Document organizationLogo;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> availableTerms;
   private gov.dhs.fema.ndgrants_rules.model.GrantorOrganization parentOrganization;
   private gov.dhs.fema.ndgrants_rules.model.AdminConfigStatus status;

   public GrantorOrganization()
   {
   }

   public java.lang.Long getGrantorOrganizationId()
   {
      return this.grantorOrganizationId;
   }

   public void setGrantorOrganizationId(java.lang.Long grantorOrganizationId)
   {
      this.grantorOrganizationId = grantorOrganizationId;
   }

   public java.lang.Long getOriginalOrgId()
   {
      return this.originalOrgId;
   }

   public void setOriginalOrgId(java.lang.Long originalOrgId)
   {
      this.originalOrgId = originalOrgId;
   }

   public java.lang.String getLegalName()
   {
      return this.legalName;
   }

   public void setLegalName(java.lang.String legalName)
   {
      this.legalName = legalName;
   }

   public gov.dhs.fema.ndgrants_rules.model.Address getPhysicalAddress()
   {
      return this.physicalAddress;
   }

   public void setPhysicalAddress(
         gov.dhs.fema.ndgrants_rules.model.Address physicalAddress)
   {
      this.physicalAddress = physicalAddress;
   }

   public gov.dhs.fema.ndgrants_rules.model.Address getMailingAddress()
   {
      return this.mailingAddress;
   }

   public void setMailingAddress(
         gov.dhs.fema.ndgrants_rules.model.Address mailingAddress)
   {
      this.mailingAddress = mailingAddress;
   }

   public java.lang.String getOpportunityIdAcronym()
   {
      return this.opportunityIdAcronym;
   }

   public void setOpportunityIdAcronym(java.lang.String opportunityIdAcronym)
   {
      this.opportunityIdAcronym = opportunityIdAcronym;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> getGrantorOrganizationContacts()
   {
      return this.grantorOrganizationContacts;
   }

   public void setGrantorOrganizationContacts(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> grantorOrganizationContacts)
   {
      this.grantorOrganizationContacts = grantorOrganizationContacts;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> getGrantorOrganizationTerms()
   {
      return this.grantorOrganizationTerms;
   }

   public void setGrantorOrganizationTerms(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> grantorOrganizationTerms)
   {
      this.grantorOrganizationTerms = grantorOrganizationTerms;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.Template> getGrantorOrganizationTemplates()
   {
      return this.grantorOrganizationTemplates;
   }

   public void setGrantorOrganizationTemplates(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Template> grantorOrganizationTemplates)
   {
      this.grantorOrganizationTemplates = grantorOrganizationTemplates;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> getInheritedTerms()
   {
      return this.inheritedTerms;
   }

   public void setInheritedTerms(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> inheritedTerms)
   {
      this.inheritedTerms = inheritedTerms;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.Template> getInheritedTemplates()
   {
      return this.inheritedTemplates;
   }

   public void setInheritedTemplates(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Template> inheritedTemplates)
   {
      this.inheritedTemplates = inheritedTemplates;
   }

   public gov.dhs.fema.ndgrants_rules.model.Document getOrganizationLogo()
   {
      return this.organizationLogo;
   }

   public void setOrganizationLogo(
         gov.dhs.fema.ndgrants_rules.model.Document organizationLogo)
   {
      this.organizationLogo = organizationLogo;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> getAvailableTerms()
   {
      return this.availableTerms;
   }

   public void setAvailableTerms(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> availableTerms)
   {
      this.availableTerms = availableTerms;
   }

   public gov.dhs.fema.ndgrants_rules.model.GrantorOrganization getParentOrganization()
   {
      return this.parentOrganization;
   }

   public void setParentOrganization(
         gov.dhs.fema.ndgrants_rules.model.GrantorOrganization parentOrganization)
   {
      this.parentOrganization = parentOrganization;
   }

   public gov.dhs.fema.ndgrants_rules.model.AdminConfigStatus getStatus()
   {
      return this.status;
   }

   public void setStatus(
         gov.dhs.fema.ndgrants_rules.model.AdminConfigStatus status)
   {
      this.status = status;
   }

   public GrantorOrganization(
         java.lang.Long grantorOrganizationId,
         java.lang.Long originalOrgId,
         java.lang.String legalName,
         gov.dhs.fema.ndgrants_rules.model.Address physicalAddress,
         gov.dhs.fema.ndgrants_rules.model.Address mailingAddress,
         java.lang.String opportunityIdAcronym,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.InternalAdminContact> grantorOrganizationContacts,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> grantorOrganizationTerms,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Template> grantorOrganizationTemplates,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> inheritedTerms,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Template> inheritedTemplates,
         gov.dhs.fema.ndgrants_rules.model.Document organizationLogo,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Term> availableTerms,
         gov.dhs.fema.ndgrants_rules.model.GrantorOrganization parentOrganization,
         gov.dhs.fema.ndgrants_rules.model.AdminConfigStatus status)
   {
      this.grantorOrganizationId = grantorOrganizationId;
      this.originalOrgId = originalOrgId;
      this.legalName = legalName;
      this.physicalAddress = physicalAddress;
      this.mailingAddress = mailingAddress;
      this.opportunityIdAcronym = opportunityIdAcronym;
      this.grantorOrganizationContacts = grantorOrganizationContacts;
      this.grantorOrganizationTerms = grantorOrganizationTerms;
      this.grantorOrganizationTemplates = grantorOrganizationTemplates;
      this.inheritedTerms = inheritedTerms;
      this.inheritedTemplates = inheritedTemplates;
      this.organizationLogo = organizationLogo;
      this.availableTerms = availableTerms;
      this.parentOrganization = parentOrganization;
      this.status = status;
   }

}