package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InputValues implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private gov.dhs.fema.ndgrants_rules.model.GrantorOrganization grantorOrganization;
   private gov.dhs.fema.ndgrants_rules.model.Program program;
   private gov.dhs.fema.ndgrants_rules.model.FundingOpportunity fundingOpportunity;
   private gov.dhs.fema.ndgrants_rules.model.Commitment commitment;
   private gov.dhs.fema.ndgrants_rules.model.Application application;
   private gov.dhs.fema.ndgrants_rules.model.Organization granteeOrganization;
   private gov.dhs.fema.ndgrants_rules.model.AwardRecommendation awardRecommendation;
   private gov.dhs.fema.ndgrants_rules.model.Award award;
   private gov.dhs.fema.ndgrants_rules.model.AmendmentRequest amendmentRequest;
   private gov.dhs.fema.ndgrants_rules.model.AmendmentRecommendation amendmentRecommendation;
   private gov.dhs.fema.ndgrants_rules.model.Amendment amendment;
   private gov.dhs.fema.ndgrants_rules.model.Grant grant;
   private gov.dhs.fema.ndgrants_rules.model.Template template;
   private gov.dhs.fema.ndgrants_rules.model.GrantsGovApplication grantsGovApplication;
   private gov.dhs.fema.ndgrants_rules.model.FundingPlanTemplate fundingPlanTemplate;
   private java.util.Map<java.lang.String, java.util.Map<java.lang.String, java.lang.Object>> customForms;
   private java.util.Map<java.lang.String, java.lang.String[]> requestParameters;

   public InputValues()
   {
   }

   public gov.dhs.fema.ndgrants_rules.model.GrantorOrganization getGrantorOrganization()
   {
      return this.grantorOrganization;
   }

   public void setGrantorOrganization(
         gov.dhs.fema.ndgrants_rules.model.GrantorOrganization grantorOrganization)
   {
      this.grantorOrganization = grantorOrganization;
   }

   public gov.dhs.fema.ndgrants_rules.model.Program getProgram()
   {
      return this.program;
   }

   public void setProgram(gov.dhs.fema.ndgrants_rules.model.Program program)
   {
      this.program = program;
   }

   public gov.dhs.fema.ndgrants_rules.model.FundingOpportunity getFundingOpportunity()
   {
      return this.fundingOpportunity;
   }

   public void setFundingOpportunity(
         gov.dhs.fema.ndgrants_rules.model.FundingOpportunity fundingOpportunity)
   {
      this.fundingOpportunity = fundingOpportunity;
   }

   public gov.dhs.fema.ndgrants_rules.model.Commitment getCommitment()
   {
      return this.commitment;
   }

   public void setCommitment(
         gov.dhs.fema.ndgrants_rules.model.Commitment commitment)
   {
      this.commitment = commitment;
   }

   public gov.dhs.fema.ndgrants_rules.model.Application getApplication()
   {
      return this.application;
   }

   public void setApplication(
         gov.dhs.fema.ndgrants_rules.model.Application application)
   {
      this.application = application;
   }

   public gov.dhs.fema.ndgrants_rules.model.Organization getGranteeOrganization()
   {
      return this.granteeOrganization;
   }

   public void setGranteeOrganization(
         gov.dhs.fema.ndgrants_rules.model.Organization granteeOrganization)
   {
      this.granteeOrganization = granteeOrganization;
   }

   public gov.dhs.fema.ndgrants_rules.model.AwardRecommendation getAwardRecommendation()
   {
      return this.awardRecommendation;
   }

   public void setAwardRecommendation(
         gov.dhs.fema.ndgrants_rules.model.AwardRecommendation awardRecommendation)
   {
      this.awardRecommendation = awardRecommendation;
   }

   public gov.dhs.fema.ndgrants_rules.model.Award getAward()
   {
      return this.award;
   }

   public void setAward(gov.dhs.fema.ndgrants_rules.model.Award award)
   {
      this.award = award;
   }

   public gov.dhs.fema.ndgrants_rules.model.AmendmentRequest getAmendmentRequest()
   {
      return this.amendmentRequest;
   }

   public void setAmendmentRequest(
         gov.dhs.fema.ndgrants_rules.model.AmendmentRequest amendmentRequest)
   {
      this.amendmentRequest = amendmentRequest;
   }

   public gov.dhs.fema.ndgrants_rules.model.AmendmentRecommendation getAmendmentRecommendation()
   {
      return this.amendmentRecommendation;
   }

   public void setAmendmentRecommendation(
         gov.dhs.fema.ndgrants_rules.model.AmendmentRecommendation amendmentRecommendation)
   {
      this.amendmentRecommendation = amendmentRecommendation;
   }

   public gov.dhs.fema.ndgrants_rules.model.Amendment getAmendment()
   {
      return this.amendment;
   }

   public void setAmendment(
         gov.dhs.fema.ndgrants_rules.model.Amendment amendment)
   {
      this.amendment = amendment;
   }

   public gov.dhs.fema.ndgrants_rules.model.Grant getGrant()
   {
      return this.grant;
   }

   public void setGrant(gov.dhs.fema.ndgrants_rules.model.Grant grant)
   {
      this.grant = grant;
   }

   public gov.dhs.fema.ndgrants_rules.model.Template getTemplate()
   {
      return this.template;
   }

   public void setTemplate(gov.dhs.fema.ndgrants_rules.model.Template template)
   {
      this.template = template;
   }

   public gov.dhs.fema.ndgrants_rules.model.GrantsGovApplication getGrantsGovApplication()
   {
      return this.grantsGovApplication;
   }

   public void setGrantsGovApplication(
         gov.dhs.fema.ndgrants_rules.model.GrantsGovApplication grantsGovApplication)
   {
      this.grantsGovApplication = grantsGovApplication;
   }

   public gov.dhs.fema.ndgrants_rules.model.FundingPlanTemplate getFundingPlanTemplate()
   {
      return this.fundingPlanTemplate;
   }

   public void setFundingPlanTemplate(
         gov.dhs.fema.ndgrants_rules.model.FundingPlanTemplate fundingPlanTemplate)
   {
      this.fundingPlanTemplate = fundingPlanTemplate;
   }
   
   public java.util.Map<java.lang.String, java.util.Map<java.lang.String, java.lang.Object>> getCustomForms()
   {
      return customForms;
   }

   public void setCustomForms(java.util.Map<java.lang.String, java.util.Map<java.lang.String, java.lang.Object>> customForms)
   {
      this.customForms = customForms;
   }
   
   public java.util.Map<java.lang.String, java.lang.String[]> getRequestParameters()
   {
      return requestParameters;
   }

   public void setRequestParameters(java.util.Map<java.lang.String, java.lang.String[]> requestParameters)
   {
      this.requestParameters = requestParameters;
   }

   public InputValues(
         gov.dhs.fema.ndgrants_rules.model.GrantorOrganization grantorOrganization,
         gov.dhs.fema.ndgrants_rules.model.Program program,
         gov.dhs.fema.ndgrants_rules.model.FundingOpportunity fundingOpportunity,
         gov.dhs.fema.ndgrants_rules.model.Commitment commitment,
         gov.dhs.fema.ndgrants_rules.model.Application application,
         gov.dhs.fema.ndgrants_rules.model.Organization granteeOrganization,
         gov.dhs.fema.ndgrants_rules.model.AwardRecommendation awardRecommendation,
         gov.dhs.fema.ndgrants_rules.model.Award award,
         gov.dhs.fema.ndgrants_rules.model.AmendmentRequest amendmentRequest,
         gov.dhs.fema.ndgrants_rules.model.AmendmentRecommendation amendmentRecommendation,
         gov.dhs.fema.ndgrants_rules.model.Amendment amendment,
         gov.dhs.fema.ndgrants_rules.model.Grant grant,
         gov.dhs.fema.ndgrants_rules.model.Template template,
         gov.dhs.fema.ndgrants_rules.model.GrantsGovApplication grantsGovApplication,
         gov.dhs.fema.ndgrants_rules.model.FundingPlanTemplate fundingPlanTemplate,
         java.util.Map<java.lang.String, java.util.Map<java.lang.String, java.lang.Object>> customForms,
         java.util.Map<java.lang.String, java.lang.String[]> requestParameters)
   {
      this.grantorOrganization = grantorOrganization;
      this.program = program;
      this.fundingOpportunity = fundingOpportunity;
      this.commitment = commitment;
      this.application = application;
      this.granteeOrganization = granteeOrganization;
      this.awardRecommendation = awardRecommendation;
      this.award = award;
      this.amendmentRequest = amendmentRequest;
      this.amendmentRecommendation = amendmentRecommendation;
      this.amendment = amendment;
      this.grant = grant;
      this.template = template;
      this.grantsGovApplication = grantsGovApplication;
      this.fundingPlanTemplate = fundingPlanTemplate;
      this.customForms = customForms;
      this.requestParameters = requestParameters;
   }
   
   public String getFormValue(java.lang.String formAlias, java.lang.String fieldAlias)
   {
      if (formAlias != null)
      {
         java.util.Map<java.lang.String, java.lang.Object> formMap = customForms.get(formAlias);
         if (formMap != null && fieldAlias != null)
         {
            java.lang.Object val = formMap.get(fieldAlias);
            if (val instanceof String)
            {
               return (String) val;
            }
         }
      }
      return null;
   }

}