package gov.dhs.fema.ndgrants_rules.model;

import gov.dhs.fema.ndgrants_rules.model.EGPTypeDef;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Module extends EGPTypeDef implements java.io.Serializable
{

   static final long serialVersionUID = 1L;
   
   public static final Module AWARD  = new Module(2);
   public static final Module AMENDMENT  = new Module(3);
   public static final Module DEOBLIGATION  = new Module(4);
   public static final Module PERFORMANCE_REPORT  = new Module(5);
   public static final Module GRANTOR_ORGANIZATION_CONFIGURATION = new Module(6);
   public static final Module PROGRAM_CONFIGURATION = new Module(7);
   public static final Module FUNDING_OPPORTUNITY_CONFIGURATION = new Module(8);
   public static final Module COMMITMENT_CONFIGURATION = new Module(9);
   public static final Module GRANTEE_ORGANIZATION_ACCESS_REQUEST = new Module(10);
   public static final Module INTERNAL_AMENDMENT = new Module(11);
   public static final Module PERFORMANCE_REPORT_TEMPLATE = new Module(12);
   public static final Module FUNDING_PLAN_TEMPLATE = new Module(13);

   public Module()
   {
   }
   
   Module(long id){
       super(id);
   }

}