package gov.dhs.fema.ndgrants_rules.model;

import gov.dhs.fema.ndgrants_rules.model.EGPTypeDef;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ObjectType extends EGPTypeDef implements java.io.Serializable
{

   static final long serialVersionUID = 1L;
   
   public static final ObjectType FUNDING_OPPORTUNITY = new ObjectType(1);
   public static final ObjectType APPLICATION = new ObjectType(2);
   public static final ObjectType AWARD = new ObjectType(3);
   public static final ObjectType AMENDMENT = new ObjectType(4);
   public static final ObjectType DEOBLIGATION = new ObjectType(5);
   public static final ObjectType PERFORMANCE_REPORT = new ObjectType(6);
   public static final ObjectType GRANTOR_ORGANIZATION = new ObjectType(7);
   public static final ObjectType PROGRAM = new ObjectType(8);
   public static final ObjectType COMMITMENT = new ObjectType(9);
   public static final ObjectType GRANTEE_ORGANIZATION = new ObjectType(10);
   public static final ObjectType GRANTS_GOV_APPLICATION = new ObjectType(11);
   public static final ObjectType AWARD_RECOMMENDATION = new ObjectType(12);
   public static final ObjectType GRANTEE_ORGANIZATION_ACCESS_REQUEST = new ObjectType(13);
   public static final ObjectType GRANT = new ObjectType(14);
   public static final ObjectType TASK_INSTANCE = new ObjectType(15);
   public static final ObjectType VENDOR = new ObjectType(16);
   public static final ObjectType OBLIGATION = new ObjectType(17);
   public static final ObjectType AMENDMENT_REQUEST = new ObjectType(18);
   public static final ObjectType AMENDMENT_RECOMMENDATION = new ObjectType(19);
   public static final ObjectType PERFORMANCE_REPORT_TEMPLATE = new ObjectType(20);
   public static final ObjectType PENDING_AMENDMENT_REQUEST = new ObjectType(21);
   public static final ObjectType FUNDING_PLAN_TEMPLATE = new ObjectType(22);

   public ObjectType()
   {
   }
   
   ObjectType(long id){
       super(id);
   }

}