package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ObligationCommitment implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long obligationCommitmentId;
   private java.lang.Long obligationId;
   private gov.dhs.fema.ndgrants_rules.model.Commitment commitment;
   private java.math.BigDecimal obligationCommitmentAmount;
   private java.util.Date dateTimeLastUpdate;
   private java.lang.Long transactionNumber;
   private gov.dhs.fema.ndgrants_rules.model.ObligationTransaction obligationTransaction;
   private gov.dhs.fema.ndgrants_rules.model.ObligationCommitment originalObligationCommitment;

   public ObligationCommitment()
   {
   }

   public java.lang.Long getObligationCommitmentId()
   {
      return this.obligationCommitmentId;
   }

   public void setObligationCommitmentId(java.lang.Long obligationCommitmentId)
   {
      this.obligationCommitmentId = obligationCommitmentId;
   }

   public java.lang.Long getObligationId()
   {
      return this.obligationId;
   }

   public void setObligationId(java.lang.Long obligationId)
   {
      this.obligationId = obligationId;
   }

   public gov.dhs.fema.ndgrants_rules.model.Commitment getCommitment()
   {
      return this.commitment;
   }

   public void setCommitment(
         gov.dhs.fema.ndgrants_rules.model.Commitment commitment)
   {
      this.commitment = commitment;
   }

   public java.math.BigDecimal getObligationCommitmentAmount()
   {
      return this.obligationCommitmentAmount;
   }

   public void setObligationCommitmentAmount(
         java.math.BigDecimal obligationCommitmentAmount)
   {
      this.obligationCommitmentAmount = obligationCommitmentAmount;
   }

   public java.util.Date getDateTimeLastUpdate()
   {
      return this.dateTimeLastUpdate;
   }

   public void setDateTimeLastUpdate(java.util.Date dateTimeLastUpdate)
   {
      this.dateTimeLastUpdate = dateTimeLastUpdate;
   }

   public java.lang.Long getTransactionNumber()
   {
      return this.transactionNumber;
   }

   public void setTransactionNumber(java.lang.Long transactionNumber)
   {
      this.transactionNumber = transactionNumber;
   }

   public gov.dhs.fema.ndgrants_rules.model.ObligationTransaction getObligationTransaction()
   {
      return this.obligationTransaction;
   }

   public void setObligationTransaction(
         gov.dhs.fema.ndgrants_rules.model.ObligationTransaction obligationTransaction)
   {
      this.obligationTransaction = obligationTransaction;
   }

   public gov.dhs.fema.ndgrants_rules.model.ObligationCommitment getOriginalObligationCommitment()
   {
      return this.originalObligationCommitment;
   }

   public void setOriginalObligationCommitment(
         gov.dhs.fema.ndgrants_rules.model.ObligationCommitment originalObligationCommitment)
   {
      this.originalObligationCommitment = originalObligationCommitment;
   }

   public ObligationCommitment(
         java.lang.Long obligationCommitmentId,
         java.lang.Long obligationId,
         gov.dhs.fema.ndgrants_rules.model.Commitment commitment,
         java.math.BigDecimal obligationCommitmentAmount,
         java.util.Date dateTimeLastUpdate,
         java.lang.Long transactionNumber,
         gov.dhs.fema.ndgrants_rules.model.ObligationTransaction obligationTransaction,
         gov.dhs.fema.ndgrants_rules.model.ObligationCommitment originalObligationCommitment)
   {
      this.obligationCommitmentId = obligationCommitmentId;
      this.obligationId = obligationId;
      this.commitment = commitment;
      this.obligationCommitmentAmount = obligationCommitmentAmount;
      this.dateTimeLastUpdate = dateTimeLastUpdate;
      this.transactionNumber = transactionNumber;
      this.obligationTransaction = obligationTransaction;
      this.originalObligationCommitment = originalObligationCommitment;
   }

}