package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Obligation implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long obligationId;
   private gov.dhs.fema.ndgrants_rules.model.ObjectType objectType;
   private java.lang.Long objectId;
   private java.lang.String obligationRefNbr;
   private java.lang.String ifmisDocumentTypeCd;
   private java.lang.String ifmisDocumentClassCd;
   private gov.dhs.fema.ndgrants_rules.model.FinancialTransactionStatus financialTransactionStatus;
   private java.util.Date obligationTransactionDate;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.ObligationCommitment> obligationCommitments;
   private java.util.Date popStartDate;
   private java.util.Date popEndDate;

   public Obligation()
   {
   }

   public java.lang.Long getObligationId()
   {
      return this.obligationId;
   }

   public void setObligationId(java.lang.Long obligationId)
   {
      this.obligationId = obligationId;
   }

   public gov.dhs.fema.ndgrants_rules.model.ObjectType getObjectType()
   {
      return this.objectType;
   }

   public void setObjectType(
         gov.dhs.fema.ndgrants_rules.model.ObjectType objectType)
   {
      this.objectType = objectType;
   }

   public java.lang.Long getObjectId()
   {
      return this.objectId;
   }

   public void setObjectId(java.lang.Long objectId)
   {
      this.objectId = objectId;
   }

   public java.lang.String getObligationRefNbr()
   {
      return this.obligationRefNbr;
   }

   public void setObligationRefNbr(java.lang.String obligationRefNbr)
   {
      this.obligationRefNbr = obligationRefNbr;
   }

   public java.lang.String getIfmisDocumentTypeCd()
   {
      return this.ifmisDocumentTypeCd;
   }

   public void setIfmisDocumentTypeCd(java.lang.String ifmisDocumentTypeCd)
   {
      this.ifmisDocumentTypeCd = ifmisDocumentTypeCd;
   }

   public java.lang.String getIfmisDocumentClassCd()
   {
      return this.ifmisDocumentClassCd;
   }

   public void setIfmisDocumentClassCd(java.lang.String ifmisDocumentClassCd)
   {
      this.ifmisDocumentClassCd = ifmisDocumentClassCd;
   }

   public gov.dhs.fema.ndgrants_rules.model.FinancialTransactionStatus getFinancialTransactionStatus()
   {
      return this.financialTransactionStatus;
   }

   public void setFinancialTransactionStatus(
         gov.dhs.fema.ndgrants_rules.model.FinancialTransactionStatus financialTransactionStatus)
   {
      this.financialTransactionStatus = financialTransactionStatus;
   }

   public java.util.Date getObligationTransactionDate()
   {
      return this.obligationTransactionDate;
   }

   public void setObligationTransactionDate(
         java.util.Date obligationTransactionDate)
   {
      this.obligationTransactionDate = obligationTransactionDate;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.ObligationCommitment> getObligationCommitments()
   {
      return this.obligationCommitments;
   }

   public void setObligationCommitments(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.ObligationCommitment> obligationCommitments)
   {
      this.obligationCommitments = obligationCommitments;
   }

   public java.util.Date getPopStartDate()
   {
      return this.popStartDate;
   }

   public void setPopStartDate(java.util.Date popStartDate)
   {
      this.popStartDate = popStartDate;
   }

   public java.util.Date getPopEndDate()
   {
      return this.popEndDate;
   }

   public void setPopEndDate(java.util.Date popEndDate)
   {
      this.popEndDate = popEndDate;
   }

   public Obligation(
         java.lang.Long obligationId,
         gov.dhs.fema.ndgrants_rules.model.ObjectType objectType,
         java.lang.Long objectId,
         java.lang.String obligationRefNbr,
         java.lang.String ifmisDocumentTypeCd,
         java.lang.String ifmisDocumentClassCd,
         gov.dhs.fema.ndgrants_rules.model.FinancialTransactionStatus financialTransactionStatus,
         java.util.Date obligationTransactionDate,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.ObligationCommitment> obligationCommitments,
         java.util.Date popStartDate, java.util.Date popEndDate)
   {
      this.obligationId = obligationId;
      this.objectType = objectType;
      this.objectId = objectId;
      this.obligationRefNbr = obligationRefNbr;
      this.ifmisDocumentTypeCd = ifmisDocumentTypeCd;
      this.ifmisDocumentClassCd = ifmisDocumentClassCd;
      this.financialTransactionStatus = financialTransactionStatus;
      this.obligationTransactionDate = obligationTransactionDate;
      this.obligationCommitments = obligationCommitments;
      this.popStartDate = popStartDate;
      this.popEndDate = popEndDate;
   }

}