package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Operation implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long operationId;
   private java.lang.String alias;
   private java.lang.String displayName;
   private boolean userDefined;
   private boolean configurable;
   private java.lang.String validateRuleset;
   private java.lang.String completeRuleset;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.Form> forms;

   public Operation()
   {
   }

   public java.lang.Long getOperationId()
   {
      return this.operationId;
   }

   public void setOperationId(java.lang.Long operationId)
   {
      this.operationId = operationId;
   }

   public java.lang.String getAlias()
   {
      return this.alias;
   }

   public void setAlias(java.lang.String alias)
   {
      this.alias = alias;
   }

   public java.lang.String getDisplayName()
   {
      return this.displayName;
   }

   public void setDisplayName(java.lang.String displayName)
   {
      this.displayName = displayName;
   }

   public boolean isUserDefined()
   {
      return this.userDefined;
   }

   public void setUserDefined(boolean userDefined)
   {
      this.userDefined = userDefined;
   }

   public boolean isConfigurable()
   {
      return this.configurable;
   }

   public void setConfigurable(boolean configurable)
   {
      this.configurable = configurable;
   }

   public java.lang.String getValidateRuleset()
   {
      return this.validateRuleset;
   }

   public void setValidateRuleset(java.lang.String validateRuleset)
   {
      this.validateRuleset = validateRuleset;
   }

   public java.lang.String getCompleteRuleset()
   {
      return this.completeRuleset;
   }

   public void setCompleteRuleset(java.lang.String completeRuleset)
   {
      this.completeRuleset = completeRuleset;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.Form> getForms()
   {
      return this.forms;
   }

   public void setForms(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Form> forms)
   {
      this.forms = forms;
   }

   public Operation(java.lang.Long operationId, java.lang.String alias,
         java.lang.String displayName, boolean userDefined,
         boolean configurable, java.lang.String validateRuleset,
         java.lang.String completeRuleset,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Form> forms)
   {
      this.operationId = operationId;
      this.alias = alias;
      this.displayName = displayName;
      this.userDefined = userDefined;
      this.configurable = configurable;
      this.validateRuleset = validateRuleset;
      this.completeRuleset = completeRuleset;
      this.forms = forms;
   }

}