package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Organization implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long organizationId;
   private java.lang.String legalName;
   private java.lang.String division;
   private java.lang.String department;
   private java.lang.String ein;
   private java.lang.String einSharedOrganizations;
   private java.lang.String duns;
   private java.lang.String duns4;
   private java.lang.Long taskInstanceId;
   private gov.dhs.fema.ndgrants_rules.model.Address physicalAddress;
   private gov.dhs.fema.ndgrants_rules.model.Address mailingAddress;
   private gov.dhs.fema.ndgrants_rules.model.EligibleApplicantType organizationType;
   private java.lang.String organizationTypeOtherExplanation;
   private gov.dhs.fema.ndgrants_rules.model.CongressionalDistrict congressionalDistrict;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.Contact> externalContacts;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.User> organizationUsers;
   private gov.dhs.fema.ndgrants_rules.model.Organization subrecipients;

   public Organization()
   {
   }

   public java.lang.Long getOrganizationId()
   {
      return this.organizationId;
   }

   public void setOrganizationId(java.lang.Long organizationId)
   {
      this.organizationId = organizationId;
   }

   public java.lang.String getLegalName()
   {
      return this.legalName;
   }

   public void setLegalName(java.lang.String legalName)
   {
      this.legalName = legalName;
   }

   public java.lang.String getDivision()
   {
      return this.division;
   }

   public void setDivision(java.lang.String division)
   {
      this.division = division;
   }

   public java.lang.String getDepartment()
   {
      return this.department;
   }

   public void setDepartment(java.lang.String department)
   {
      this.department = department;
   }

   public java.lang.String getEin()
   {
      return this.ein;
   }

   public void setEin(java.lang.String ein)
   {
      this.ein = ein;
   }

   public java.lang.String getEinSharedOrganizations()
   {
      return this.einSharedOrganizations;
   }

   public void setEinSharedOrganizations(
         java.lang.String einSharedOrganizations)
   {
      this.einSharedOrganizations = einSharedOrganizations;
   }

   public java.lang.String getDuns()
   {
      return this.duns;
   }

   public void setDuns(java.lang.String duns)
   {
      this.duns = duns;
   }

   public java.lang.String getDuns4()
   {
      return this.duns4;
   }

   public void setDuns4(java.lang.String duns4)
   {
      this.duns4 = duns4;
   }

   public java.lang.Long getTaskInstanceId()
   {
      return this.taskInstanceId;
   }

   public void setTaskInstanceId(java.lang.Long taskInstanceId)
   {
      this.taskInstanceId = taskInstanceId;
   }

   public gov.dhs.fema.ndgrants_rules.model.Address getPhysicalAddress()
   {
      return this.physicalAddress;
   }

   public void setPhysicalAddress(
         gov.dhs.fema.ndgrants_rules.model.Address physicalAddress)
   {
      this.physicalAddress = physicalAddress;
   }

   public gov.dhs.fema.ndgrants_rules.model.Address getMailingAddress()
   {
      return this.mailingAddress;
   }

   public void setMailingAddress(
         gov.dhs.fema.ndgrants_rules.model.Address mailingAddress)
   {
      this.mailingAddress = mailingAddress;
   }

   public gov.dhs.fema.ndgrants_rules.model.EligibleApplicantType getOrganizationType()
   {
      return this.organizationType;
   }

   public void setOrganizationType(
         gov.dhs.fema.ndgrants_rules.model.EligibleApplicantType organizationType)
   {
      this.organizationType = organizationType;
   }

   public java.lang.String getOrganizationTypeOtherExplanation()
   {
      return this.organizationTypeOtherExplanation;
   }

   public void setOrganizationTypeOtherExplanation(
         java.lang.String organizationTypeOtherExplanation)
   {
      this.organizationTypeOtherExplanation = organizationTypeOtherExplanation;
   }

   public gov.dhs.fema.ndgrants_rules.model.CongressionalDistrict getCongressionalDistrict()
   {
      return this.congressionalDistrict;
   }

   public void setCongressionalDistrict(
         gov.dhs.fema.ndgrants_rules.model.CongressionalDistrict congressionalDistrict)
   {
      this.congressionalDistrict = congressionalDistrict;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.Contact> getExternalContacts()
   {
      return this.externalContacts;
   }

   public void setExternalContacts(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Contact> externalContacts)
   {
      this.externalContacts = externalContacts;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.User> getOrganizationUsers()
   {
      return this.organizationUsers;
   }

   public void setOrganizationUsers(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.User> organizationUsers)
   {
      this.organizationUsers = organizationUsers;
   }

   public gov.dhs.fema.ndgrants_rules.model.Organization getSubrecipients()
   {
      return this.subrecipients;
   }

   public void setSubrecipients(
         gov.dhs.fema.ndgrants_rules.model.Organization subrecipients)
   {
      this.subrecipients = subrecipients;
   }

   public Organization(
         java.lang.Long organizationId,
         java.lang.String legalName,
         java.lang.String division,
         java.lang.String department,
         java.lang.String ein,
         java.lang.String einSharedOrganizations,
         java.lang.String duns,
         java.lang.String duns4,
         java.lang.Long taskInstanceId,
         gov.dhs.fema.ndgrants_rules.model.Address physicalAddress,
         gov.dhs.fema.ndgrants_rules.model.Address mailingAddress,
         gov.dhs.fema.ndgrants_rules.model.EligibleApplicantType organizationType,
         java.lang.String organizationTypeOtherExplanation,
         gov.dhs.fema.ndgrants_rules.model.CongressionalDistrict congressionalDistrict,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Contact> externalContacts,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.User> organizationUsers,
         gov.dhs.fema.ndgrants_rules.model.Organization subrecipients)
   {
      this.organizationId = organizationId;
      this.legalName = legalName;
      this.division = division;
      this.department = department;
      this.ein = ein;
      this.einSharedOrganizations = einSharedOrganizations;
      this.duns = duns;
      this.duns4 = duns4;
      this.taskInstanceId = taskInstanceId;
      this.physicalAddress = physicalAddress;
      this.mailingAddress = mailingAddress;
      this.organizationType = organizationType;
      this.organizationTypeOtherExplanation = organizationTypeOtherExplanation;
      this.congressionalDistrict = congressionalDistrict;
      this.externalContacts = externalContacts;
      this.organizationUsers = organizationUsers;
      this.subrecipients = subrecipients;
   }

}