package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PackageComponent implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long packageComponentId;
   private java.lang.Long objectId;
   private gov.dhs.fema.ndgrants_rules.model.ObjectType objectType;
   private gov.dhs.fema.ndgrants_rules.model.TemplateType templateType;
   private java.lang.Long documentId;
   private java.lang.String documentName;
   private java.lang.String documentDescription;
   private java.lang.Integer packageOrder;
   private byte[] content;
   private boolean isPackageDoc;

   public PackageComponent()
   {
   }

   public java.lang.Long getPackageComponentId()
   {
      return this.packageComponentId;
   }

   public void setPackageComponentId(java.lang.Long packageComponentId)
   {
      this.packageComponentId = packageComponentId;
   }

   public java.lang.Long getObjectId()
   {
      return this.objectId;
   }

   public void setObjectId(java.lang.Long objectId)
   {
      this.objectId = objectId;
   }

   public gov.dhs.fema.ndgrants_rules.model.ObjectType getObjectType()
   {
      return this.objectType;
   }

   public void setObjectType(
         gov.dhs.fema.ndgrants_rules.model.ObjectType objectType)
   {
      this.objectType = objectType;
   }

   public gov.dhs.fema.ndgrants_rules.model.TemplateType getTemplateType()
   {
      return this.templateType;
   }

   public void setTemplateType(
         gov.dhs.fema.ndgrants_rules.model.TemplateType templateType)
   {
      this.templateType = templateType;
   }

   public java.lang.Long getDocumentId()
   {
      return this.documentId;
   }

   public void setDocumentId(java.lang.Long documentId)
   {
      this.documentId = documentId;
   }

   public java.lang.String getDocumentName()
   {
      return this.documentName;
   }

   public void setDocumentName(java.lang.String documentName)
   {
      this.documentName = documentName;
   }

   public java.lang.String getDocumentDescription()
   {
      return this.documentDescription;
   }

   public void setDocumentDescription(java.lang.String documentDescription)
   {
      this.documentDescription = documentDescription;
   }

   public java.lang.Integer getPackageOrder()
   {
      return this.packageOrder;
   }

   public void setPackageOrder(java.lang.Integer packageOrder)
   {
      this.packageOrder = packageOrder;
   }

   public byte[] getContent()
   {
      return this.content;
   }

   public void setContent(byte[] content)
   {
      this.content = content;
   }

   public boolean isIsPackageDoc()
   {
      return this.isPackageDoc;
   }

   public void setIsPackageDoc(boolean isPackageDoc)
   {
      this.isPackageDoc = isPackageDoc;
   }

   public PackageComponent(java.lang.Long packageComponentId,
         java.lang.Long objectId,
         gov.dhs.fema.ndgrants_rules.model.ObjectType objectType,
         gov.dhs.fema.ndgrants_rules.model.TemplateType templateType,
         java.lang.Long documentId, java.lang.String documentName,
         java.lang.String documentDescription,
         java.lang.Integer packageOrder, byte[] content, boolean isPackageDoc)
   {
      this.packageComponentId = packageComponentId;
      this.objectId = objectId;
      this.objectType = objectType;
      this.templateType = templateType;
      this.documentId = documentId;
      this.documentName = documentName;
      this.documentDescription = documentDescription;
      this.packageOrder = packageOrder;
      this.content = content;
      this.isPackageDoc = isPackageDoc;
   }

}