package gov.dhs.fema.ndgrants_rules.model;

import gov.dhs.fema.ndgrants_rules.model.EGPTypeDef;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PaymentMethod extends EGPTypeDef implements java.io.Serializable
{

   static final long serialVersionUID = 1L;
   
   public static final PaymentMethod SMARTLINK = new PaymentMethod(1);
   public static final PaymentMethod PARS = new PaymentMethod(2);
   public static final PaymentMethod SF_270 = new PaymentMethod(3);

   public PaymentMethod()
   {
   }
   
   PaymentMethod(long id){
       super(id);
   }

}