package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PerformanceReportTemplate implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long performanceReportTemplateId;
   private java.lang.String title;
   private java.lang.String alias;
   private java.lang.Integer dueDate;
   private java.lang.Integer availabilityDate;
   private gov.dhs.fema.ndgrants_rules.model.AdminConfigStatus status;
   private java.lang.Long originalId;
   private java.util.List<java.util.Date> reportDates;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.Form> forms;

   public PerformanceReportTemplate()
   {
   }

   public java.lang.Long getPerformanceReportTemplateId()
   {
      return this.performanceReportTemplateId;
   }

   public void setPerformanceReportTemplateId(
         java.lang.Long performanceReportTemplateId)
   {
      this.performanceReportTemplateId = performanceReportTemplateId;
   }

   public java.lang.String getTitle()
   {
      return this.title;
   }

   public void setTitle(java.lang.String title)
   {
      this.title = title;
   }

   public java.lang.String getAlias()
   {
      return this.alias;
   }

   public void setAlias(java.lang.String alias)
   {
      this.alias = alias;
   }

   public java.lang.Integer getDueDate()
   {
      return this.dueDate;
   }

   public void setDueDate(java.lang.Integer dueDate)
   {
      this.dueDate = dueDate;
   }

   public java.lang.Integer getAvailabilityDate()
   {
      return this.availabilityDate;
   }

   public void setAvailabilityDate(java.lang.Integer availabilityDate)
   {
      this.availabilityDate = availabilityDate;
   }

   public gov.dhs.fema.ndgrants_rules.model.AdminConfigStatus getStatus()
   {
      return this.status;
   }

   public void setStatus(
         gov.dhs.fema.ndgrants_rules.model.AdminConfigStatus status)
   {
      this.status = status;
   }

   public java.lang.Long getOriginalId()
   {
      return this.originalId;
   }

   public void setOriginalId(java.lang.Long originalId)
   {
      this.originalId = originalId;
   }

   public java.util.List<java.util.Date> getReportDates()
   {
      return this.reportDates;
   }

   public void setReportDates(java.util.List<java.util.Date> reportDates)
   {
      this.reportDates = reportDates;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.Form> getForms()
   {
      return this.forms;
   }

   public void setForms(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Form> forms)
   {
      this.forms = forms;
   }

   public PerformanceReportTemplate(
         java.lang.Long performanceReportTemplateId, java.lang.String title,
         java.lang.String alias, java.lang.Integer dueDate,
         java.lang.Integer availabilityDate,
         gov.dhs.fema.ndgrants_rules.model.AdminConfigStatus status,
         java.lang.Long originalId,
         java.util.List<java.util.Date> reportDates,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Form> forms)
   {
      this.performanceReportTemplateId = performanceReportTemplateId;
      this.title = title;
      this.alias = alias;
      this.dueDate = dueDate;
      this.availabilityDate = availabilityDate;
      this.status = status;
      this.originalId = originalId;
      this.reportDates = reportDates;
      this.forms = forms;
   }

}