package gov.dhs.fema.ndgrants_rules.model;

import gov.dhs.fema.ndgrants_rules.model.EGPTypeDef;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Prefix extends EGPTypeDef implements java.io.Serializable
{

   static final long serialVersionUID = 1L;
   
   public static final Prefix MR = new Prefix(1);
   public static final Prefix MRS = new Prefix(2);
   public static final Prefix MISS = new Prefix(3);
   public static final Prefix MS = new Prefix(4);
   public static final Prefix DR = new Prefix(5);
   public static final Prefix REV = new Prefix(6);

   public Prefix()
   {
   }
   
   Prefix(long id){
       super(id);
   }

}