package gov.dhs.fema.ndgrants_rules.model;

import gov.dhs.fema.ndgrants_rules.model.EGPTypeDef;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ProgramIncomeType extends EGPTypeDef implements java.io.Serializable
{

   static final long serialVersionUID = 1L;
   
   public static final ProgramIncomeType DEDUCTION = new ProgramIncomeType(1);
   public static final ProgramIncomeType ADDITION = new ProgramIncomeType(2);
   public static final ProgramIncomeType COST_SHARING_MATCHING = new ProgramIncomeType(3);

   public ProgramIncomeType()
   {
       super();
   }
   
   ProgramIncomeType(long id)
   {
       super(id);
   }

}