package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ResponsibleParty implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long responsiblePartyId;
   private gov.dhs.fema.ndgrants_rules.model.User user;

   public ResponsibleParty()
   {
   }

   public java.lang.Long getResponsiblePartyId()
   {
      return this.responsiblePartyId;
   }

   public void setResponsiblePartyId(java.lang.Long responsiblePartyId)
   {
      this.responsiblePartyId = responsiblePartyId;
   }

   public gov.dhs.fema.ndgrants_rules.model.User getUser()
   {
      return this.user;
   }

   public void setUser(gov.dhs.fema.ndgrants_rules.model.User user)
   {
      this.user = user;
   }

   public ResponsibleParty(java.lang.Long responsiblePartyId,
         gov.dhs.fema.ndgrants_rules.model.User user)
   {
      this.responsiblePartyId = responsiblePartyId;
      this.user = user;
   }

}