package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

import java.util.ArrayList;

public class RuleErrors implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.util.List<java.lang.String> validationList;

   public RuleErrors()
   {
   }

   public java.util.List<java.lang.String> getValidationList()
   {
      return this.validationList;
   }

   public void setValidationList(
         java.util.List<java.lang.String> validationList)
   {
      this.validationList = validationList;
   }

   public RuleErrors(java.util.List<java.lang.String> validationList)
   {
      this.validationList = validationList;
   }
   
    public void addValidationError(String validationError)
	{
    	if(validationList == null)
    	{
    		validationList = new ArrayList<String>();
    	}
    	validationList.add(validationError);
	}

}