package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SF424CBudget implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long sf424cBudgetId;
   private java.math.BigDecimal administrativeExpenses;
   private java.math.BigDecimal landExpenses;
   private java.math.BigDecimal relocationExpenses;
   private java.math.BigDecimal architectualExpenses;
   private java.math.BigDecimal otherArchitecturalExpenses;
   private java.math.BigDecimal projectInspectionExpenses;
   private java.math.BigDecimal siteWorkExpenses;
   private java.math.BigDecimal demolitionExpenses;
   private java.math.BigDecimal constructionExpenses;
   private java.math.BigDecimal equipmentExpenses;
   private java.math.BigDecimal miscellaneousExpenses;
   private java.math.BigDecimal contingenciesTotal;
   private java.math.BigDecimal projectIncome;
   private java.math.BigDecimal nonallowableAdministrativeExpenses;
   private java.math.BigDecimal nonallowableLandExpenses;
   private java.math.BigDecimal nonallowableRelocationExpenses;
   private java.math.BigDecimal nonallowableArchitectualExpenses;
   private java.math.BigDecimal nonallowableOtherArchitecturalExpenses;
   private java.math.BigDecimal nonallowableProjectInspectionExpenses;
   private java.math.BigDecimal nonallowableSiteWorkExpenses;
   private java.math.BigDecimal nonallowableDemolitionExpenses;
   private java.math.BigDecimal nonallowableConstructionExpenses;
   private java.math.BigDecimal nonallowableEquipmentExpenses;
   private java.math.BigDecimal nonallowableMiscellaneousExpenses;
   private java.math.BigDecimal nonallowableContingenciesTotal;
   private java.math.BigDecimal nonallowableProjectIncome;
   private java.math.BigDecimal totalAllowableCost;
   private java.math.BigDecimal totalNonAllowableCost;
   private java.math.BigDecimal totalProjectCosts;
   private java.math.BigDecimal totalAllowableCostForTotalProjectCosts;
   private boolean migratedBudget;

   public SF424CBudget()
   {
   }

   public java.lang.Long getSf424cBudgetId()
   {
      return this.sf424cBudgetId;
   }

   public void setSf424cBudgetId(java.lang.Long sf424cBudgetId)
   {
      this.sf424cBudgetId = sf424cBudgetId;
   }

   public java.math.BigDecimal getAdministrativeExpenses()
   {
      return this.administrativeExpenses;
   }

   public void setAdministrativeExpenses(
         java.math.BigDecimal administrativeExpenses)
   {
      this.administrativeExpenses = administrativeExpenses;
   }

   public java.math.BigDecimal getLandExpenses()
   {
      return this.landExpenses;
   }

   public void setLandExpenses(java.math.BigDecimal landExpenses)
   {
      this.landExpenses = landExpenses;
   }

   public java.math.BigDecimal getRelocationExpenses()
   {
      return this.relocationExpenses;
   }

   public void setRelocationExpenses(java.math.BigDecimal relocationExpenses)
   {
      this.relocationExpenses = relocationExpenses;
   }

   public java.math.BigDecimal getArchitectualExpenses()
   {
      return this.architectualExpenses;
   }

   public void setArchitectualExpenses(
         java.math.BigDecimal architectualExpenses)
   {
      this.architectualExpenses = architectualExpenses;
   }

   public java.math.BigDecimal getOtherArchitecturalExpenses()
   {
      return this.otherArchitecturalExpenses;
   }

   public void setOtherArchitecturalExpenses(
         java.math.BigDecimal otherArchitecturalExpenses)
   {
      this.otherArchitecturalExpenses = otherArchitecturalExpenses;
   }

   public java.math.BigDecimal getProjectInspectionExpenses()
   {
      return this.projectInspectionExpenses;
   }

   public void setProjectInspectionExpenses(
         java.math.BigDecimal projectInspectionExpenses)
   {
      this.projectInspectionExpenses = projectInspectionExpenses;
   }

   public java.math.BigDecimal getSiteWorkExpenses()
   {
      return this.siteWorkExpenses;
   }

   public void setSiteWorkExpenses(java.math.BigDecimal siteWorkExpenses)
   {
      this.siteWorkExpenses = siteWorkExpenses;
   }

   public java.math.BigDecimal getDemolitionExpenses()
   {
      return this.demolitionExpenses;
   }

   public void setDemolitionExpenses(java.math.BigDecimal demolitionExpenses)
   {
      this.demolitionExpenses = demolitionExpenses;
   }

   public java.math.BigDecimal getConstructionExpenses()
   {
      return this.constructionExpenses;
   }

   public void setConstructionExpenses(
         java.math.BigDecimal constructionExpenses)
   {
      this.constructionExpenses = constructionExpenses;
   }

   public java.math.BigDecimal getEquipmentExpenses()
   {
      return this.equipmentExpenses;
   }

   public void setEquipmentExpenses(java.math.BigDecimal equipmentExpenses)
   {
      this.equipmentExpenses = equipmentExpenses;
   }

   public java.math.BigDecimal getMiscellaneousExpenses()
   {
      return this.miscellaneousExpenses;
   }

   public void setMiscellaneousExpenses(
         java.math.BigDecimal miscellaneousExpenses)
   {
      this.miscellaneousExpenses = miscellaneousExpenses;
   }

   public java.math.BigDecimal getContingenciesTotal()
   {
      return this.contingenciesTotal;
   }

   public void setContingenciesTotal(java.math.BigDecimal contingenciesTotal)
   {
      this.contingenciesTotal = contingenciesTotal;
   }

   public java.math.BigDecimal getProjectIncome()
   {
      return this.projectIncome;
   }

   public void setProjectIncome(java.math.BigDecimal projectIncome)
   {
      this.projectIncome = projectIncome;
   }

   public java.math.BigDecimal getNonallowableAdministrativeExpenses()
   {
      return this.nonallowableAdministrativeExpenses;
   }

   public void setNonallowableAdministrativeExpenses(
         java.math.BigDecimal nonallowableAdministrativeExpenses)
   {
      this.nonallowableAdministrativeExpenses = nonallowableAdministrativeExpenses;
   }

   public java.math.BigDecimal getNonallowableLandExpenses()
   {
      return this.nonallowableLandExpenses;
   }

   public void setNonallowableLandExpenses(
         java.math.BigDecimal nonallowableLandExpenses)
   {
      this.nonallowableLandExpenses = nonallowableLandExpenses;
   }

   public java.math.BigDecimal getNonallowableRelocationExpenses()
   {
      return this.nonallowableRelocationExpenses;
   }

   public void setNonallowableRelocationExpenses(
         java.math.BigDecimal nonallowableRelocationExpenses)
   {
      this.nonallowableRelocationExpenses = nonallowableRelocationExpenses;
   }

   public java.math.BigDecimal getNonallowableArchitectualExpenses()
   {
      return this.nonallowableArchitectualExpenses;
   }

   public void setNonallowableArchitectualExpenses(
         java.math.BigDecimal nonallowableArchitectualExpenses)
   {
      this.nonallowableArchitectualExpenses = nonallowableArchitectualExpenses;
   }

   public java.math.BigDecimal getNonallowableOtherArchitecturalExpenses()
   {
      return this.nonallowableOtherArchitecturalExpenses;
   }

   public void setNonallowableOtherArchitecturalExpenses(
         java.math.BigDecimal nonallowableOtherArchitecturalExpenses)
   {
      this.nonallowableOtherArchitecturalExpenses = nonallowableOtherArchitecturalExpenses;
   }

   public java.math.BigDecimal getNonallowableProjectInspectionExpenses()
   {
      return this.nonallowableProjectInspectionExpenses;
   }

   public void setNonallowableProjectInspectionExpenses(
         java.math.BigDecimal nonallowableProjectInspectionExpenses)
   {
      this.nonallowableProjectInspectionExpenses = nonallowableProjectInspectionExpenses;
   }

   public java.math.BigDecimal getNonallowableSiteWorkExpenses()
   {
      return this.nonallowableSiteWorkExpenses;
   }

   public void setNonallowableSiteWorkExpenses(
         java.math.BigDecimal nonallowableSiteWorkExpenses)
   {
      this.nonallowableSiteWorkExpenses = nonallowableSiteWorkExpenses;
   }

   public java.math.BigDecimal getNonallowableDemolitionExpenses()
   {
      return this.nonallowableDemolitionExpenses;
   }

   public void setNonallowableDemolitionExpenses(
         java.math.BigDecimal nonallowableDemolitionExpenses)
   {
      this.nonallowableDemolitionExpenses = nonallowableDemolitionExpenses;
   }

   public java.math.BigDecimal getNonallowableConstructionExpenses()
   {
      return this.nonallowableConstructionExpenses;
   }

   public void setNonallowableConstructionExpenses(
         java.math.BigDecimal nonallowableConstructionExpenses)
   {
      this.nonallowableConstructionExpenses = nonallowableConstructionExpenses;
   }

   public java.math.BigDecimal getNonallowableEquipmentExpenses()
   {
      return this.nonallowableEquipmentExpenses;
   }

   public void setNonallowableEquipmentExpenses(
         java.math.BigDecimal nonallowableEquipmentExpenses)
   {
      this.nonallowableEquipmentExpenses = nonallowableEquipmentExpenses;
   }

   public java.math.BigDecimal getNonallowableMiscellaneousExpenses()
   {
      return this.nonallowableMiscellaneousExpenses;
   }

   public void setNonallowableMiscellaneousExpenses(
         java.math.BigDecimal nonallowableMiscellaneousExpenses)
   {
      this.nonallowableMiscellaneousExpenses = nonallowableMiscellaneousExpenses;
   }

   public java.math.BigDecimal getNonallowableContingenciesTotal()
   {
      return this.nonallowableContingenciesTotal;
   }

   public void setNonallowableContingenciesTotal(
         java.math.BigDecimal nonallowableContingenciesTotal)
   {
      this.nonallowableContingenciesTotal = nonallowableContingenciesTotal;
   }

   public java.math.BigDecimal getNonallowableProjectIncome()
   {
      return this.nonallowableProjectIncome;
   }

   public void setNonallowableProjectIncome(
         java.math.BigDecimal nonallowableProjectIncome)
   {
      this.nonallowableProjectIncome = nonallowableProjectIncome;
   }

   public java.math.BigDecimal getTotalAllowableCost()
   {
      return this.totalAllowableCost;
   }

   public void setTotalAllowableCost(java.math.BigDecimal totalAllowableCost)
   {
      this.totalAllowableCost = totalAllowableCost;
   }

   public java.math.BigDecimal getTotalNonAllowableCost()
   {
      return this.totalNonAllowableCost;
   }

   public void setTotalNonAllowableCost(
         java.math.BigDecimal totalNonAllowableCost)
   {
      this.totalNonAllowableCost = totalNonAllowableCost;
   }

   public java.math.BigDecimal getTotalProjectCosts()
   {
      return this.totalProjectCosts;
   }

   public void setTotalProjectCosts(java.math.BigDecimal totalProjectCosts)
   {
      this.totalProjectCosts = totalProjectCosts;
   }

   public java.math.BigDecimal getTotalAllowableCostForTotalProjectCosts()
   {
      return this.totalAllowableCostForTotalProjectCosts;
   }

   public void setTotalAllowableCostForTotalProjectCosts(
         java.math.BigDecimal totalAllowableCostForTotalProjectCosts)
   {
      this.totalAllowableCostForTotalProjectCosts = totalAllowableCostForTotalProjectCosts;
   }

   public boolean isMigratedBudget()
   {
      return this.migratedBudget;
   }

   public void setMigratedBudget(boolean migratedBudget)
   {
      this.migratedBudget = migratedBudget;
   }

   public SF424CBudget(java.lang.Long sf424cBudgetId,
         java.math.BigDecimal administrativeExpenses,
         java.math.BigDecimal landExpenses,
         java.math.BigDecimal relocationExpenses,
         java.math.BigDecimal architectualExpenses,
         java.math.BigDecimal otherArchitecturalExpenses,
         java.math.BigDecimal projectInspectionExpenses,
         java.math.BigDecimal siteWorkExpenses,
         java.math.BigDecimal demolitionExpenses,
         java.math.BigDecimal constructionExpenses,
         java.math.BigDecimal equipmentExpenses,
         java.math.BigDecimal miscellaneousExpenses,
         java.math.BigDecimal contingenciesTotal,
         java.math.BigDecimal projectIncome,
         java.math.BigDecimal nonallowableAdministrativeExpenses,
         java.math.BigDecimal nonallowableLandExpenses,
         java.math.BigDecimal nonallowableRelocationExpenses,
         java.math.BigDecimal nonallowableArchitectualExpenses,
         java.math.BigDecimal nonallowableOtherArchitecturalExpenses,
         java.math.BigDecimal nonallowableProjectInspectionExpenses,
         java.math.BigDecimal nonallowableSiteWorkExpenses,
         java.math.BigDecimal nonallowableDemolitionExpenses,
         java.math.BigDecimal nonallowableConstructionExpenses,
         java.math.BigDecimal nonallowableEquipmentExpenses,
         java.math.BigDecimal nonallowableMiscellaneousExpenses,
         java.math.BigDecimal nonallowableContingenciesTotal,
         java.math.BigDecimal nonallowableProjectIncome,
         java.math.BigDecimal totalAllowableCost,
         java.math.BigDecimal totalNonAllowableCost,
         java.math.BigDecimal totalProjectCosts,
         java.math.BigDecimal totalAllowableCostForTotalProjectCosts,
         boolean migratedBudget)
   {
      this.sf424cBudgetId = sf424cBudgetId;
      this.administrativeExpenses = administrativeExpenses;
      this.landExpenses = landExpenses;
      this.relocationExpenses = relocationExpenses;
      this.architectualExpenses = architectualExpenses;
      this.otherArchitecturalExpenses = otherArchitecturalExpenses;
      this.projectInspectionExpenses = projectInspectionExpenses;
      this.siteWorkExpenses = siteWorkExpenses;
      this.demolitionExpenses = demolitionExpenses;
      this.constructionExpenses = constructionExpenses;
      this.equipmentExpenses = equipmentExpenses;
      this.miscellaneousExpenses = miscellaneousExpenses;
      this.contingenciesTotal = contingenciesTotal;
      this.projectIncome = projectIncome;
      this.nonallowableAdministrativeExpenses = nonallowableAdministrativeExpenses;
      this.nonallowableLandExpenses = nonallowableLandExpenses;
      this.nonallowableRelocationExpenses = nonallowableRelocationExpenses;
      this.nonallowableArchitectualExpenses = nonallowableArchitectualExpenses;
      this.nonallowableOtherArchitecturalExpenses = nonallowableOtherArchitecturalExpenses;
      this.nonallowableProjectInspectionExpenses = nonallowableProjectInspectionExpenses;
      this.nonallowableSiteWorkExpenses = nonallowableSiteWorkExpenses;
      this.nonallowableDemolitionExpenses = nonallowableDemolitionExpenses;
      this.nonallowableConstructionExpenses = nonallowableConstructionExpenses;
      this.nonallowableEquipmentExpenses = nonallowableEquipmentExpenses;
      this.nonallowableMiscellaneousExpenses = nonallowableMiscellaneousExpenses;
      this.nonallowableContingenciesTotal = nonallowableContingenciesTotal;
      this.nonallowableProjectIncome = nonallowableProjectIncome;
      this.totalAllowableCost = totalAllowableCost;
      this.totalNonAllowableCost = totalNonAllowableCost;
      this.totalProjectCosts = totalProjectCosts;
      this.totalAllowableCostForTotalProjectCosts = totalAllowableCostForTotalProjectCosts;
      this.migratedBudget = migratedBudget;
   }

}