package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SF424ABudget implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long sf424aBudgetId;
   private java.math.BigDecimal personnel;
   private java.math.BigDecimal fringeBenefits;
   private java.math.BigDecimal travel;
   private java.math.BigDecimal equipment;
   private java.math.BigDecimal supplies;
   private java.math.BigDecimal contractual;
   private java.math.BigDecimal construction;
   private java.math.BigDecimal other;
   private java.math.BigDecimal indirectCharges;
   private java.math.BigDecimal programIncome;
   private gov.dhs.fema.ndgrants_rules.model.ProgramIncomeType programIncomeType;
   private java.math.BigDecimal applicant;
   private java.math.BigDecimal state;
   private java.math.BigDecimal otherSources;
   private java.math.BigDecimal totalFederal;

   public SF424ABudget()
   {
   }

   public java.lang.Long getSf424aBudgetId()
   {
      return this.sf424aBudgetId;
   }

   public void setSf424aBudgetId(java.lang.Long sf424aBudgetId)
   {
      this.sf424aBudgetId = sf424aBudgetId;
   }

   public java.math.BigDecimal getPersonnel()
   {
      return this.personnel;
   }

   public void setPersonnel(java.math.BigDecimal personnel)
   {
      this.personnel = personnel;
   }

   public java.math.BigDecimal getFringeBenefits()
   {
      return this.fringeBenefits;
   }

   public void setFringeBenefits(java.math.BigDecimal fringeBenefits)
   {
      this.fringeBenefits = fringeBenefits;
   }

   public java.math.BigDecimal getTravel()
   {
      return this.travel;
   }

   public void setTravel(java.math.BigDecimal travel)
   {
      this.travel = travel;
   }

   public java.math.BigDecimal getEquipment()
   {
      return this.equipment;
   }

   public void setEquipment(java.math.BigDecimal equipment)
   {
      this.equipment = equipment;
   }

   public java.math.BigDecimal getSupplies()
   {
      return this.supplies;
   }

   public void setSupplies(java.math.BigDecimal supplies)
   {
      this.supplies = supplies;
   }

   public java.math.BigDecimal getContractual()
   {
      return this.contractual;
   }

   public void setContractual(java.math.BigDecimal contractual)
   {
      this.contractual = contractual;
   }

   public java.math.BigDecimal getConstruction()
   {
      return this.construction;
   }

   public void setConstruction(java.math.BigDecimal construction)
   {
      this.construction = construction;
   }

   public java.math.BigDecimal getOther()
   {
      return this.other;
   }

   public void setOther(java.math.BigDecimal other)
   {
      this.other = other;
   }

   public java.math.BigDecimal getIndirectCharges()
   {
      return this.indirectCharges;
   }

   public void setIndirectCharges(java.math.BigDecimal indirectCharges)
   {
      this.indirectCharges = indirectCharges;
   }

   public java.math.BigDecimal getProgramIncome()
   {
      return this.programIncome;
   }

   public void setProgramIncome(java.math.BigDecimal programIncome)
   {
      this.programIncome = programIncome;
   }

   public gov.dhs.fema.ndgrants_rules.model.ProgramIncomeType getProgramIncomeType()
   {
      return this.programIncomeType;
   }

   public void setProgramIncomeType(
         gov.dhs.fema.ndgrants_rules.model.ProgramIncomeType programIncomeType)
   {
      this.programIncomeType = programIncomeType;
   }

   public java.math.BigDecimal getApplicant()
   {
      return this.applicant;
   }

   public void setApplicant(java.math.BigDecimal applicant)
   {
      this.applicant = applicant;
   }

   public java.math.BigDecimal getState()
   {
      return this.state;
   }

   public void setState(java.math.BigDecimal state)
   {
      this.state = state;
   }

   public java.math.BigDecimal getOtherSources()
   {
      return this.otherSources;
   }

   public void setOtherSources(java.math.BigDecimal otherSources)
   {
      this.otherSources = otherSources;
   }

   public java.math.BigDecimal getTotalFederal()
   {
      return this.totalFederal;
   }

   public void setTotalFederal(java.math.BigDecimal totalFederal)
   {
      this.totalFederal = totalFederal;
   }

   public SF424ABudget(
         java.lang.Long sf424aBudgetId,
         java.math.BigDecimal personnel,
         java.math.BigDecimal fringeBenefits,
         java.math.BigDecimal travel,
         java.math.BigDecimal equipment,
         java.math.BigDecimal supplies,
         java.math.BigDecimal contractual,
         java.math.BigDecimal construction,
         java.math.BigDecimal other,
         java.math.BigDecimal indirectCharges,
         java.math.BigDecimal programIncome,
         gov.dhs.fema.ndgrants_rules.model.ProgramIncomeType programIncomeType,
         java.math.BigDecimal applicant, java.math.BigDecimal state,
         java.math.BigDecimal otherSources, java.math.BigDecimal totalFederal)
   {
      this.sf424aBudgetId = sf424aBudgetId;
      this.personnel = personnel;
      this.fringeBenefits = fringeBenefits;
      this.travel = travel;
      this.equipment = equipment;
      this.supplies = supplies;
      this.contractual = contractual;
      this.construction = construction;
      this.other = other;
      this.indirectCharges = indirectCharges;
      this.programIncome = programIncome;
      this.programIncomeType = programIncomeType;
      this.applicant = applicant;
      this.state = state;
      this.otherSources = otherSources;
      this.totalFederal = totalFederal;
   }

}