package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SF424Information implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long sf424InformationId;
   private java.lang.Long applicationId;
   private java.lang.String projectTitle;
   private java.lang.String affectedAreas;
   private java.util.Date proposedStartDate;
   private java.util.Date proposedEndDate;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.CongressionalDistrict> projectCongressionalDistricts;
   private java.math.BigDecimal federalFunding;
   private java.math.BigDecimal applicantFunding;
   private java.math.BigDecimal stateFunding;
   private java.math.BigDecimal localFunding;
   private java.math.BigDecimal otherFunding;
   private java.math.BigDecimal programIncomeFunding;
   private java.lang.Boolean delinquentOnFederalDebt;
   private java.lang.String delinquentComment;
   private java.util.Date eo12372ReviewDate;

   public SF424Information()
   {
   }

   public java.lang.Long getSf424InformationId()
   {
      return this.sf424InformationId;
   }

   public void setSf424InformationId(java.lang.Long sf424InformationId)
   {
      this.sf424InformationId = sf424InformationId;
   }

   public java.lang.Long getApplicationId()
   {
      return this.applicationId;
   }

   public void setApplicationId(java.lang.Long applicationId)
   {
      this.applicationId = applicationId;
   }

   public java.lang.String getProjectTitle()
   {
      return this.projectTitle;
   }

   public void setProjectTitle(java.lang.String projectTitle)
   {
      this.projectTitle = projectTitle;
   }

   public java.lang.String getAffectedAreas()
   {
      return this.affectedAreas;
   }

   public void setAffectedAreas(java.lang.String affectedAreas)
   {
      this.affectedAreas = affectedAreas;
   }

   public java.util.Date getProposedStartDate()
   {
      return this.proposedStartDate;
   }

   public void setProposedStartDate(java.util.Date proposedStartDate)
   {
      this.proposedStartDate = proposedStartDate;
   }

   public java.util.Date getProposedEndDate()
   {
      return this.proposedEndDate;
   }

   public void setProposedEndDate(java.util.Date proposedEndDate)
   {
      this.proposedEndDate = proposedEndDate;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.CongressionalDistrict> getProjectCongressionalDistricts()
   {
      return this.projectCongressionalDistricts;
   }

   public void setProjectCongressionalDistricts(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.CongressionalDistrict> projectCongressionalDistricts)
   {
      this.projectCongressionalDistricts = projectCongressionalDistricts;
   }

   public java.math.BigDecimal getFederalFunding()
   {
      return this.federalFunding;
   }

   public void setFederalFunding(java.math.BigDecimal federalFunding)
   {
      this.federalFunding = federalFunding;
   }

   public java.math.BigDecimal getApplicantFunding()
   {
      return this.applicantFunding;
   }

   public void setApplicantFunding(java.math.BigDecimal applicantFunding)
   {
      this.applicantFunding = applicantFunding;
   }

   public java.math.BigDecimal getStateFunding()
   {
      return this.stateFunding;
   }

   public void setStateFunding(java.math.BigDecimal stateFunding)
   {
      this.stateFunding = stateFunding;
   }

   public java.math.BigDecimal getLocalFunding()
   {
      return this.localFunding;
   }

   public void setLocalFunding(java.math.BigDecimal localFunding)
   {
      this.localFunding = localFunding;
   }

   public java.math.BigDecimal getOtherFunding()
   {
      return this.otherFunding;
   }

   public void setOtherFunding(java.math.BigDecimal otherFunding)
   {
      this.otherFunding = otherFunding;
   }

   public java.math.BigDecimal getProgramIncomeFunding()
   {
      return this.programIncomeFunding;
   }

   public void setProgramIncomeFunding(
         java.math.BigDecimal programIncomeFunding)
   {
      this.programIncomeFunding = programIncomeFunding;
   }

   public java.lang.Boolean getDelinquentOnFederalDebt()
   {
      return this.delinquentOnFederalDebt;
   }

   public void setDelinquentOnFederalDebt(
         java.lang.Boolean delinquentOnFederalDebt)
   {
      this.delinquentOnFederalDebt = delinquentOnFederalDebt;
   }

   public java.lang.String getDelinquentComment()
   {
      return this.delinquentComment;
   }

   public void setDelinquentComment(java.lang.String delinquentComment)
   {
      this.delinquentComment = delinquentComment;
   }

   public java.util.Date getEo12372ReviewDate()
   {
      return this.eo12372ReviewDate;
   }

   public void setEo12372ReviewDate(java.util.Date eo12372ReviewDate)
   {
      this.eo12372ReviewDate = eo12372ReviewDate;
   }

   public SF424Information(
         java.lang.Long sf424InformationId,
         java.lang.Long applicationId,
         java.lang.String projectTitle,
         java.lang.String affectedAreas,
         java.util.Date proposedStartDate,
         java.util.Date proposedEndDate,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.CongressionalDistrict> projectCongressionalDistricts,
         java.math.BigDecimal federalFunding,
         java.math.BigDecimal applicantFunding,
         java.math.BigDecimal stateFunding,
         java.math.BigDecimal localFunding,
         java.math.BigDecimal otherFunding,
         java.math.BigDecimal programIncomeFunding,
         java.lang.Boolean delinquentOnFederalDebt,
         java.lang.String delinquentComment, java.util.Date eo12372ReviewDate)
   {
      this.sf424InformationId = sf424InformationId;
      this.applicationId = applicationId;
      this.projectTitle = projectTitle;
      this.affectedAreas = affectedAreas;
      this.proposedStartDate = proposedStartDate;
      this.proposedEndDate = proposedEndDate;
      this.projectCongressionalDistricts = projectCongressionalDistricts;
      this.federalFunding = federalFunding;
      this.applicantFunding = applicantFunding;
      this.stateFunding = stateFunding;
      this.localFunding = localFunding;
      this.otherFunding = otherFunding;
      this.programIncomeFunding = programIncomeFunding;
      this.delinquentOnFederalDebt = delinquentOnFederalDebt;
      this.delinquentComment = delinquentComment;
      this.eo12372ReviewDate = eo12372ReviewDate;
   }

}