package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SF424Information implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public SF424Information() {
    }

}