package gov.dhs.fema.ndgrants_rules.model;

import gov.dhs.fema.ndgrants_rules.model.EGPTypeDef;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SignatureType extends EGPTypeDef implements java.io.Serializable
{

   static final long serialVersionUID = 1L;
   
   public static final SignatureType ASSISTANCE_OFFICER_SIGNATURE = new SignatureType(1);
   public static final SignatureType GRANTOR_SIGNATORY_AUTHORITY_SIGNATURE = new SignatureType(2);
   public static final SignatureType GRANTEE_SIGNATORY_AUTHORITY_SIGNATURE = new SignatureType(3);
   public static final SignatureType NOT_REQUIRED = new SignatureType(4);
   public static final SignatureType GRANTEE_SIGNATORY_AUTHORITY_DECLINE = new SignatureType(5);

   public SignatureType()
   {
       super();
   }
   
   SignatureType(long id) 
   {
       super(id);
   }

}