package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Signature implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long signatureId;
   private gov.dhs.fema.ndgrants_rules.model.SignatureType signatureType;
   private gov.dhs.fema.ndgrants_rules.model.User signedBy;
   private java.util.Date signatureTime;
   private gov.dhs.fema.ndgrants_rules.model.ObjectType objectType;
   private java.lang.Long objectId;

   public Signature()
   {
   }

   public java.lang.Long getSignatureId()
   {
      return this.signatureId;
   }

   public void setSignatureId(java.lang.Long signatureId)
   {
      this.signatureId = signatureId;
   }

   public gov.dhs.fema.ndgrants_rules.model.SignatureType getSignatureType()
   {
      return this.signatureType;
   }

   public void setSignatureType(
         gov.dhs.fema.ndgrants_rules.model.SignatureType signatureType)
   {
      this.signatureType = signatureType;
   }

   public gov.dhs.fema.ndgrants_rules.model.User getSignedBy()
   {
      return this.signedBy;
   }

   public void setSignedBy(gov.dhs.fema.ndgrants_rules.model.User signedBy)
   {
      this.signedBy = signedBy;
   }

   public java.util.Date getSignatureTime()
   {
      return this.signatureTime;
   }

   public void setSignatureTime(java.util.Date signatureTime)
   {
      this.signatureTime = signatureTime;
   }

   public gov.dhs.fema.ndgrants_rules.model.ObjectType getObjectType()
   {
      return this.objectType;
   }

   public void setObjectType(
         gov.dhs.fema.ndgrants_rules.model.ObjectType objectType)
   {
      this.objectType = objectType;
   }

   public java.lang.Long getObjectId()
   {
      return this.objectId;
   }

   public void setObjectId(java.lang.Long objectId)
   {
      this.objectId = objectId;
   }

   public Signature(java.lang.Long signatureId,
         gov.dhs.fema.ndgrants_rules.model.SignatureType signatureType,
         gov.dhs.fema.ndgrants_rules.model.User signedBy,
         java.util.Date signatureTime,
         gov.dhs.fema.ndgrants_rules.model.ObjectType objectType,
         java.lang.Long objectId)
   {
      this.signatureId = signatureId;
      this.signatureType = signatureType;
      this.signedBy = signedBy;
      this.signatureTime = signatureTime;
      this.objectType = objectType;
      this.objectId = objectId;
   }

}