package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Source implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long objectId;
   private java.lang.String name;
   private gov.dhs.fema.ndgrants_rules.model.ObjectType objectType;

   public Source()
   {
   }

   public java.lang.Long getObjectId()
   {
      return this.objectId;
   }

   public void setObjectId(java.lang.Long objectId)
   {
      this.objectId = objectId;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public gov.dhs.fema.ndgrants_rules.model.ObjectType getObjectType()
   {
      return this.objectType;
   }

   public void setObjectType(
         gov.dhs.fema.ndgrants_rules.model.ObjectType objectType)
   {
      this.objectType = objectType;
   }

   public Source(java.lang.Long objectId, java.lang.String name,
         gov.dhs.fema.ndgrants_rules.model.ObjectType objectType)
   {
      this.objectId = objectId;
      this.name = name;
      this.objectType = objectType;
   }

}