package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class StatutoryAuthority implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long statutoryAuthorityId;
   private java.lang.String shortTitle;
   private java.lang.Integer congressionalIdentifier;
   private java.lang.Long sequenceNo;
   private gov.dhs.fema.ndgrants_rules.model.Source source;

   public StatutoryAuthority()
   {
   }

   public java.lang.Long getStatutoryAuthorityId()
   {
      return this.statutoryAuthorityId;
   }

   public void setStatutoryAuthorityId(java.lang.Long statutoryAuthorityId)
   {
      this.statutoryAuthorityId = statutoryAuthorityId;
   }

   public java.lang.String getShortTitle()
   {
      return this.shortTitle;
   }

   public void setShortTitle(java.lang.String shortTitle)
   {
      this.shortTitle = shortTitle;
   }

   public java.lang.Integer getCongressionalIdentifier()
   {
      return this.congressionalIdentifier;
   }

   public void setCongressionalIdentifier(
         java.lang.Integer congressionalIdentifier)
   {
      this.congressionalIdentifier = congressionalIdentifier;
   }

   public java.lang.Long getSequenceNo()
   {
      return this.sequenceNo;
   }

   public void setSequenceNo(java.lang.Long sequenceNo)
   {
      this.sequenceNo = sequenceNo;
   }

   public gov.dhs.fema.ndgrants_rules.model.Source getSource()
   {
      return this.source;
   }

   public void setSource(gov.dhs.fema.ndgrants_rules.model.Source source)
   {
      this.source = source;
   }

   public StatutoryAuthority(java.lang.Long statutoryAuthorityId,
         java.lang.String shortTitle,
         java.lang.Integer congressionalIdentifier,
         java.lang.Long sequenceNo,
         gov.dhs.fema.ndgrants_rules.model.Source source)
   {
      this.statutoryAuthorityId = statutoryAuthorityId;
      this.shortTitle = shortTitle;
      this.congressionalIdentifier = congressionalIdentifier;
      this.sequenceNo = sequenceNo;
      this.source = source;
   }

}