package gov.dhs.fema.ndgrants_rules.model;

import gov.dhs.fema.ndgrants_rules.model.EGPCodedTypeDef;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class State extends EGPCodedTypeDef implements java.io.Serializable
{

   static final long serialVersionUID = 1L;
   
   public static final State PENNSYLVANIA = new State(1, "PA");
   public static final State CANADA = new State(2, "CN");
   public static final State COLORADO = new State(3, "CO");
   public static final State WASHINGTON = new State(4, "WA");
   public static final State GUAM = new State(5, "GU");
   public static final State LOUISIANA = new State(6, "LA");
   public static final State OREGON = new State(7, "OR");
   public static final State KANSAS = new State(8, "KS");
   public static final State KENTUCKY = new State(9, "KY");
   public static final State WISCONSIN = new State(10, "WI");
   public static final State DISTRICT_OF_COLUMBIA = new State(11, "DC");
   public static final State DEFAULT_OTHER_STATES = new State(12, "OT");
   public static final State WEST_VIRGINIA = new State(13, "WV");
   public static final State CONNECTICUT = new State(14, "CT");
   public static final State KINGMAN_REEF = new State(15, "KQ");
   public static final State WAKE_ISLAND = new State(16, "WQ");
   public static final State SOUTH_CAROLINA = new State(17, "SC");
   public static final State SOUTH_DAKOTA = new State(18, "SD");
   public static final State FLORIDA = new State(19, "FL");
   public static final State NAVASSA_ISLAND = new State(20, "BQ");
   public static final State FEDERATED_STATES_OF_MICRONESIA = new State(21, "FM");
   public static final State WYOMING = new State(22, "WY");
   public static final State OHIO = new State(23, "OH");
   public static final State BAKER_ISLAND = new State(24, "FQ");
   public static final State OKLAHOMA = new State(25, "OK");
   public static final State CALIFORNIA = new State(26, "CA");
   public static final State TENNESSEE = new State(27, "TN");
   public static final State NEVADA = new State(28, "NV");
   public static final State GEORGIA = new State(29, "GA");
   public static final State NEW_YORK = new State(30, "NY");
   public static final State JOHNSTON_ATOLL = new State(31, "JQ");
   public static final State NEBRASKA = new State(32,"NE");
   public static final State NORTH_DAKOTA = new State(33, "ND");
   public static final State NORTH_CAROLINA = new State(34, "NC");
   public static final State APO_FPO_KOREA_JAPAN_PHILIPPINES_OTHER_PACIFIC = new State(35, "AP");
   public static final State TRUST_TERRITORY_OF_PACIFIC = new State(36, "TT");
   public static final State TEXAS = new State(37, "TX");
   public static final State ALABAMA = new State(38, "AL");
   public static final State ALASKA = new State(39, "AK");
   public static final State NEW_MEXICO = new State(40, "NM");
   public static final State PUERTO_RICO = new State(41, "PR");
   public static final State APO_FPO_EUROPE_MIDDLE_EAST_AND_AFRICA = new State(42, "AE");
   public static final State NEW_JERSEY = new State(43,"NJ");
   public static final State PALAU = new State(44, "PW");
   public static final State NEW_HAMPSHIRE = new State(45, "NH");
   public static final State APO_FPO_CENTRAL_AND_SOUTH_AMERICA = new State(46, "AA");
   public static final State MISSISSIPPI = new State(47, "MS");
   public static final State MONTANA = new State(48, "MT");
   public static final State MIDWAY_ISLANDS = new State(49, "MQ");
   public static final State MISSOURI = new State(50, "MO");
   public static final State ARIZONA = new State(51, "AZ");
   public static final State NORTHERN_MARIANA_ISLANDS = new State(52, "MP");
   public static final State EUROPE = new State(53, "EU");
   public static final State MINNESOTA = new State(54, "MN");
   public static final State INDIANA = new State(55, "IN");
   public static final State U__S__MINOR_OUTLYING_ISLAND = new State(56, "UM");
   public static final State UTAH = new State(57, "UT");
   public static final State ILLINOIS = new State(58, "IL");
   public static final State ARKANSAS = new State(59, "AR");
   public static final State AMERICAN_SAMOA = new State(60, "AS");
   public static final State MASSACHUSETTS = new State(61, "MA");
   public static final State MARYLAND = new State(62, "MD");
   public static final State IOWA = new State(63, "IA");
   public static final State DELAWARE = new State(64, "DE");
   public static final State IDAHO = new State(65, "ID");
   public static final State MICHIGAN = new State(66, "MI");
   public static final State VIRGINIA = new State(67, "VA");
   public static final State MAINE = new State(68, "ME");
   public static final State MARSHALL_ISLANDS = new State(69, "MH");
   public static final State PALMYRA_ATOLL = new State(70,"LQ");
   public static final State VIRGIN_ISLANDS = new State(71, "VI");
   public static final State HOWLARD_ISLAND = new State(72, "HQ");
   public static final State HAWAII = new State(73, "HI");
   public static final State VERMONT = new State(74, "VT");
   public static final State RHODE_ISLAND = new State(75, "RI");

   public State()
   {
   }
   
   State(long id, String code){
       super(id, code);
   }

}