package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SubApplicant implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long subApplicantId;
   private gov.dhs.fema.ndgrants_rules.model.Organization organization;
   private java.lang.Long orgId;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.ResponsibleParty> responsibleParties;

   public SubApplicant()
   {
   }

   public java.lang.Long getSubApplicantId()
   {
      return this.subApplicantId;
   }

   public void setSubApplicantId(java.lang.Long subApplicantId)
   {
      this.subApplicantId = subApplicantId;
   }

   public gov.dhs.fema.ndgrants_rules.model.Organization getOrganization()
   {
      return this.organization;
   }

   public void setOrganization(
         gov.dhs.fema.ndgrants_rules.model.Organization organization)
   {
      this.organization = organization;
   }

   public java.lang.Long getOrgId()
   {
      return this.orgId;
   }

   public void setOrgId(java.lang.Long orgId)
   {
      this.orgId = orgId;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.ResponsibleParty> getResponsibleParties()
   {
      return this.responsibleParties;
   }

   public void setResponsibleParties(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.ResponsibleParty> responsibleParties)
   {
      this.responsibleParties = responsibleParties;
   }

   public SubApplicant(
         java.lang.Long subApplicantId,
         gov.dhs.fema.ndgrants_rules.model.Organization organization,
         java.lang.Long orgId,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.ResponsibleParty> responsibleParties)
   {
      this.subApplicantId = subApplicantId;
      this.organization = organization;
      this.orgId = orgId;
      this.responsibleParties = responsibleParties;
   }

}