package gov.dhs.fema.ndgrants_rules.model;

import gov.dhs.fema.ndgrants_rules.model.EGPTypeDef;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Suffix extends EGPTypeDef implements java.io.Serializable
{

   static final long serialVersionUID = 1L;
   
   public static final Suffix JR = new Suffix(1);
   public static final Suffix SR = new Suffix(2);
   public static final Suffix MD = new Suffix(3);
   public static final Suffix PHD = new Suffix(4);

   public Suffix()
   {
   }
   
   Suffix(long id){
       super(id);
   }

}