package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Template implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long templateId;
   private gov.dhs.fema.ndgrants_rules.model.TemplateType templateType;
   private java.lang.String name;
   private java.lang.String systemName;
   private java.lang.String templateBody;
   private java.lang.String templateBodyNoHTML;
   private java.lang.Integer inUseNum;
   private java.lang.Long originalTemplateId;
   private boolean selected;

   public Template()
   {
   }

   public java.lang.Long getTemplateId()
   {
      return this.templateId;
   }

   public void setTemplateId(java.lang.Long templateId)
   {
      this.templateId = templateId;
   }

   public gov.dhs.fema.ndgrants_rules.model.TemplateType getTemplateType()
   {
      return this.templateType;
   }

   public void setTemplateType(
         gov.dhs.fema.ndgrants_rules.model.TemplateType templateType)
   {
      this.templateType = templateType;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getSystemName()
   {
      return this.systemName;
   }

   public void setSystemName(java.lang.String systemName)
   {
      this.systemName = systemName;
   }

   public java.lang.String getTemplateBody()
   {
      return this.templateBody;
   }

   public void setTemplateBody(java.lang.String templateBody)
   {
      this.templateBody = templateBody;
   }

   public java.lang.String getTemplateBodyNoHTML()
   {
      return this.templateBodyNoHTML;
   }

   public void setTemplateBodyNoHTML(java.lang.String templateBodyNoHTML)
   {
      this.templateBodyNoHTML = templateBodyNoHTML;
   }

   public java.lang.Integer getInUseNum()
   {
      return this.inUseNum;
   }

   public void setInUseNum(java.lang.Integer inUseNum)
   {
      this.inUseNum = inUseNum;
   }

   public java.lang.Long getOriginalTemplateId()
   {
      return this.originalTemplateId;
   }

   public void setOriginalTemplateId(java.lang.Long originalTemplateId)
   {
      this.originalTemplateId = originalTemplateId;
   }

   public boolean isSelected()
   {
      return this.selected;
   }

   public void setSelected(boolean selected)
   {
      this.selected = selected;
   }

   public Template(java.lang.Long templateId,
         gov.dhs.fema.ndgrants_rules.model.TemplateType templateType,
         java.lang.String name, java.lang.String systemName,
         java.lang.String templateBody, java.lang.String templateBodyNoHTML,
         java.lang.Integer inUseNum, java.lang.Long originalTemplateId,
         boolean selected)
   {
      this.templateId = templateId;
      this.templateType = templateType;
      this.name = name;
      this.systemName = systemName;
      this.templateBody = templateBody;
      this.templateBodyNoHTML = templateBodyNoHTML;
      this.inUseNum = inUseNum;
      this.originalTemplateId = originalTemplateId;
      this.selected = selected;
   }

}