package gov.dhs.fema.ndgrants_rules.model;

import gov.dhs.fema.ndgrants_rules.model.EGPTypeDef;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TermFinancialAction extends EGPTypeDef implements java.io.Serializable
{

   static final long serialVersionUID = 1L;
   
   public static final TermFinancialAction HOLD_PAYMENTS = new TermFinancialAction(1);
   public static final TermFinancialAction RELEASE_FUNDS = new TermFinancialAction(2);
   public static final TermFinancialAction COOPERATIVE_AGREEMENT = new TermFinancialAction(3);
   public static final TermFinancialAction NO_FINANCIAL_ACTION = new TermFinancialAction(4);


   public TermFinancialAction()
   {
   }
   
   public TermFinancialAction(long id){
       super(id);
   }

}