package gov.dhs.fema.ndgrants_rules.model;

import gov.dhs.fema.ndgrants_rules.model.EGPTypeDef;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TermCategory extends EGPTypeDef implements java.io.Serializable
{

   static final long serialVersionUID = 1L;
   
   public static final TermCategory REQUIRED = new TermCategory(1);
   public static final TermCategory PROGRAMMATIC = new TermCategory(2);
   public static final TermCategory FINANCIAL = new TermCategory(3);

   public TermCategory()
   {
       super();
   }
   
   public TermCategory(long id){
       super(id);
   }

}