package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Term implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long termId;
   private java.lang.Long year;
   private java.lang.String name;
   private gov.dhs.fema.ndgrants_rules.model.TermCategory category;
   private gov.dhs.fema.ndgrants_rules.model.TermFinancialAction financialAction;
   private java.lang.String termBody;
   private java.lang.Integer inUseNum;
   private java.lang.Integer sortOrder;
   private java.lang.Long originalTermId;
   private java.lang.Boolean isFo;
   private java.lang.Boolean isRequestedRemoval;
   private java.lang.Boolean isRecommendedRemoval;
   private java.lang.Boolean isRecommendedAddition;
   private java.lang.Boolean isRemovedFromGrant;
   private java.lang.String title;

   public Term()
   {
   }

   public java.lang.Long getTermId()
   {
      return this.termId;
   }

   public void setTermId(java.lang.Long termId)
   {
      this.termId = termId;
   }

   public java.lang.Long getYear()
   {
      return this.year;
   }

   public void setYear(java.lang.Long year)
   {
      this.year = year;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public gov.dhs.fema.ndgrants_rules.model.TermCategory getCategory()
   {
      return this.category;
   }

   public void setCategory(
         gov.dhs.fema.ndgrants_rules.model.TermCategory category)
   {
      this.category = category;
   }

   public gov.dhs.fema.ndgrants_rules.model.TermFinancialAction getFinancialAction()
   {
      return this.financialAction;
   }

   public void setFinancialAction(
         gov.dhs.fema.ndgrants_rules.model.TermFinancialAction financialAction)
   {
      this.financialAction = financialAction;
   }

   public java.lang.String getTermBody()
   {
      return this.termBody;
   }

   public void setTermBody(java.lang.String termBody)
   {
      this.termBody = termBody;
   }

   public java.lang.Integer getInUseNum()
   {
      return this.inUseNum;
   }

   public void setInUseNum(java.lang.Integer inUseNum)
   {
      this.inUseNum = inUseNum;
   }

   public java.lang.Integer getSortOrder()
   {
      return this.sortOrder;
   }

   public void setSortOrder(java.lang.Integer sortOrder)
   {
      this.sortOrder = sortOrder;
   }

   public java.lang.Long getOriginalTermId()
   {
      return this.originalTermId;
   }

   public void setOriginalTermId(java.lang.Long originalTermId)
   {
      this.originalTermId = originalTermId;
   }

   public java.lang.Boolean getIsFo()
   {
      return this.isFo;
   }

   public void setIsFo(java.lang.Boolean isFo)
   {
      this.isFo = isFo;
   }

   public java.lang.Boolean getIsRequestedRemoval()
   {
      return this.isRequestedRemoval;
   }

   public void setIsRequestedRemoval(java.lang.Boolean isRequestedRemoval)
   {
      this.isRequestedRemoval = isRequestedRemoval;
   }

   public java.lang.Boolean getIsRecommendedRemoval()
   {
      return this.isRecommendedRemoval;
   }

   public void setIsRecommendedRemoval(java.lang.Boolean isRecommendedRemoval)
   {
      this.isRecommendedRemoval = isRecommendedRemoval;
   }

   public java.lang.Boolean getIsRecommendedAddition()
   {
      return this.isRecommendedAddition;
   }

   public void setIsRecommendedAddition(java.lang.Boolean isRecommendedAddition)
   {
      this.isRecommendedAddition = isRecommendedAddition;
   }

   public java.lang.Boolean getIsRemovedFromGrant()
   {
      return this.isRemovedFromGrant;
   }

   public void setIsRemovedFromGrant(java.lang.Boolean isRemovedFromGrant)
   {
      this.isRemovedFromGrant = isRemovedFromGrant;
   }

   public java.lang.String getTitle()
   {
      return this.title;
   }

   public void setTitle(java.lang.String title)
   {
      this.title = title;
   }

   public Term(
         java.lang.Long termId,
         java.lang.Long year,
         java.lang.String name,
         gov.dhs.fema.ndgrants_rules.model.TermCategory category,
         gov.dhs.fema.ndgrants_rules.model.TermFinancialAction financialAction,
         java.lang.String termBody, java.lang.Integer inUseNum,
         java.lang.Integer sortOrder, java.lang.Long originalTermId,
         java.lang.Boolean isFo, java.lang.Boolean isRequestedRemoval,
         java.lang.Boolean isRecommendedRemoval,
         java.lang.Boolean isRecommendedAddition,
         java.lang.Boolean isRemovedFromGrant, java.lang.String title)
   {
      this.termId = termId;
      this.year = year;
      this.name = name;
      this.category = category;
      this.financialAction = financialAction;
      this.termBody = termBody;
      this.inUseNum = inUseNum;
      this.sortOrder = sortOrder;
      this.originalTermId = originalTermId;
      this.isFo = isFo;
      this.isRequestedRemoval = isRequestedRemoval;
      this.isRecommendedRemoval = isRecommendedRemoval;
      this.isRecommendedAddition = isRecommendedAddition;
      this.isRemovedFromGrant = isRemovedFromGrant;
      this.title = title;
   }

}