package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class UserRole implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long roleId;
   private java.lang.String alias;
   private java.lang.String displayName;
   private java.lang.String isaacAlias;

   public UserRole()
   {
   }

   public java.lang.Long getRoleId()
   {
      return this.roleId;
   }

   public void setRoleId(java.lang.Long roleId)
   {
      this.roleId = roleId;
   }

   public java.lang.String getAlias()
   {
      return this.alias;
   }

   public void setAlias(java.lang.String alias)
   {
      this.alias = alias;
   }

   public java.lang.String getDisplayName()
   {
      return this.displayName;
   }

   public void setDisplayName(java.lang.String displayName)
   {
      this.displayName = displayName;
   }

   public java.lang.String getIsaacAlias()
   {
      return this.isaacAlias;
   }

   public void setIsaacAlias(java.lang.String isaacAlias)
   {
      this.isaacAlias = isaacAlias;
   }

   public UserRole(java.lang.Long roleId, java.lang.String alias,
         java.lang.String displayName, java.lang.String isaacAlias)
   {
      this.roleId = roleId;
      this.alias = alias;
      this.displayName = displayName;
      this.isaacAlias = isaacAlias;
   }

}