package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class User implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String sessionId;
   private java.lang.Long userId;
   private java.lang.String loginName;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.UserRole> userRoles;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.GranteeOrganizationRole> granteeOrganizationRoles;
   private boolean consortiumLead;
   private boolean isInternalUser;
   private boolean active;
   private java.util.Date deactivatedFrom;
   private java.util.Date deactivatedUntil;
   private java.lang.Long delegateUserId;
   private gov.dhs.fema.ndgrants_rules.model.Document document;
   private gov.dhs.fema.ndgrants_rules.model.Contact contact;
   private java.util.Map<Long, java.util.List<gov.dhs.fema.ndgrants_rules.model.GranteeOrganizationRole>> granteeOrganizationRoleMap;

   public User()
   {
   }

   public java.lang.String getSessionId()
   {
      return this.sessionId;
   }

   public void setSessionId(java.lang.String sessionId)
   {
      this.sessionId = sessionId;
   }

   public java.lang.Long getUserId()
   {
      return this.userId;
   }

   public void setUserId(java.lang.Long userId)
   {
      this.userId = userId;
   }

   public java.lang.String getLoginName()
   {
      return this.loginName;
   }

   public void setLoginName(java.lang.String loginName)
   {
      this.loginName = loginName;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.UserRole> getUserRoles()
   {
      return this.userRoles;
   }

   public void setUserRoles(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.UserRole> userRoles)
   {
      this.userRoles = userRoles;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.GranteeOrganizationRole> getGranteeOrganizationRoles()
   {
      return this.granteeOrganizationRoles;
   }

   public void setGranteeOrganizationRoles(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.GranteeOrganizationRole> granteeOrganizationRoles)
   {
      this.granteeOrganizationRoles = granteeOrganizationRoles;
   }

   public boolean isConsortiumLead()
   {
      return this.consortiumLead;
   }

   public void setConsortiumLead(boolean consortiumLead)
   {
      this.consortiumLead = consortiumLead;
   }

   public boolean isIsInternalUser()
   {
      return this.isInternalUser;
   }

   public void setIsInternalUser(boolean isInternalUser)
   {
      this.isInternalUser = isInternalUser;
   }

   public boolean isActive()
   {
      return this.active;
   }

   public void setActive(boolean active)
   {
      this.active = active;
   }

   public java.util.Date getDeactivatedFrom()
   {
      return this.deactivatedFrom;
   }

   public void setDeactivatedFrom(java.util.Date deactivatedFrom)
   {
      this.deactivatedFrom = deactivatedFrom;
   }

   public java.util.Date getDeactivatedUntil()
   {
      return this.deactivatedUntil;
   }

   public void setDeactivatedUntil(java.util.Date deactivatedUntil)
   {
      this.deactivatedUntil = deactivatedUntil;
   }

   public java.lang.Long getDelegateUserId()
   {
      return this.delegateUserId;
   }

   public void setDelegateUserId(java.lang.Long delegateUserId)
   {
      this.delegateUserId = delegateUserId;
   }

   public gov.dhs.fema.ndgrants_rules.model.Document getDocument()
   {
      return this.document;
   }

   public void setDocument(gov.dhs.fema.ndgrants_rules.model.Document document)
   {
      this.document = document;
   }

   public gov.dhs.fema.ndgrants_rules.model.Contact getContact()
   {
      return this.contact;
   }

   public void setContact(gov.dhs.fema.ndgrants_rules.model.Contact contact)
   {
      this.contact = contact;
   }
   
   public java.util.Map<Long, java.util.List<gov.dhs.fema.ndgrants_rules.model.GranteeOrganizationRole>> getGranteeOrganizationRoleMap() {
		return granteeOrganizationRoleMap;
   }

	public void setGranteeOrganizationRoleMap(
			java.util.Map<Long, java.util.List<gov.dhs.fema.ndgrants_rules.model.GranteeOrganizationRole>> granteeOrganizationRoleMap) {
		this.granteeOrganizationRoleMap = granteeOrganizationRoleMap;
	}

   public User(
         java.lang.String sessionId,
         java.lang.Long userId,
         java.lang.String loginName,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.UserRole> userRoles,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.GranteeOrganizationRole> granteeOrganizationRoles,
         boolean consortiumLead, boolean isInternalUser, boolean active,
         java.util.Date deactivatedFrom, java.util.Date deactivatedUntil,
         java.lang.Long delegateUserId,
         gov.dhs.fema.ndgrants_rules.model.Document document,
         gov.dhs.fema.ndgrants_rules.model.Contact contact,
         java.util.Map<Long, java.util.List<gov.dhs.fema.ndgrants_rules.model.GranteeOrganizationRole>> granteeOrganizationRoleMap)
   {
      this.sessionId = sessionId;
      this.userId = userId;
      this.loginName = loginName;
      this.userRoles = userRoles;
      this.granteeOrganizationRoles = granteeOrganizationRoles;
      this.consortiumLead = consortiumLead;
      this.isInternalUser = isInternalUser;
      this.active = active;
      this.deactivatedFrom = deactivatedFrom;
      this.deactivatedUntil = deactivatedUntil;
      this.delegateUserId = delegateUserId;
      this.document = document;
      this.contact = contact;
      this.granteeOrganizationRoleMap = granteeOrganizationRoleMap;
   }

}