package gov.dhs.fema.ndgrants_rules.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Vendor implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long vendorId;
   private java.lang.String name;
   private java.lang.String vendorNo;
   private java.lang.String duns;
   private java.lang.String duns4;
   private java.util.List<gov.dhs.fema.ndgrants_rules.model.Organization> granteeOrganizations;
   private gov.dhs.fema.ndgrants_rules.model.Address address;
   private java.lang.String dunsFromIFMIS;
   private boolean associatedWithAnAward;
   private boolean newVendor;
   private java.lang.Long granteeOrganizationId;
   private gov.dhs.fema.ndgrants_rules.model.FinancialSystem financialSystem;

   public Vendor()
   {
   }

   public java.lang.Long getVendorId()
   {
      return this.vendorId;
   }

   public void setVendorId(java.lang.Long vendorId)
   {
      this.vendorId = vendorId;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getVendorNo()
   {
      return this.vendorNo;
   }

   public void setVendorNo(java.lang.String vendorNo)
   {
      this.vendorNo = vendorNo;
   }

   public java.lang.String getDuns()
   {
      return this.duns;
   }

   public void setDuns(java.lang.String duns)
   {
      this.duns = duns;
   }

   public java.lang.String getDuns4()
   {
      return this.duns4;
   }

   public void setDuns4(java.lang.String duns4)
   {
      this.duns4 = duns4;
   }

   public java.util.List<gov.dhs.fema.ndgrants_rules.model.Organization> getGranteeOrganizations()
   {
      return this.granteeOrganizations;
   }

   public void setGranteeOrganizations(
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Organization> granteeOrganizations)
   {
      this.granteeOrganizations = granteeOrganizations;
   }

   public gov.dhs.fema.ndgrants_rules.model.Address getAddress()
   {
      return this.address;
   }

   public void setAddress(gov.dhs.fema.ndgrants_rules.model.Address address)
   {
      this.address = address;
   }

   public java.lang.String getDunsFromIFMIS()
   {
      return this.dunsFromIFMIS;
   }

   public void setDunsFromIFMIS(java.lang.String dunsFromIFMIS)
   {
      this.dunsFromIFMIS = dunsFromIFMIS;
   }

   public boolean isAssociatedWithAnAward()
   {
      return this.associatedWithAnAward;
   }

   public void setAssociatedWithAnAward(boolean associatedWithAnAward)
   {
      this.associatedWithAnAward = associatedWithAnAward;
   }

   public boolean isNewVendor()
   {
      return this.newVendor;
   }

   public void setNewVendor(boolean newVendor)
   {
      this.newVendor = newVendor;
   }

   public java.lang.Long getGranteeOrganizationId()
   {
      return this.granteeOrganizationId;
   }

   public void setGranteeOrganizationId(java.lang.Long granteeOrganizationId)
   {
      this.granteeOrganizationId = granteeOrganizationId;
   }

   public gov.dhs.fema.ndgrants_rules.model.FinancialSystem getFinancialSystem()
   {
      return this.financialSystem;
   }

   public void setFinancialSystem(
         gov.dhs.fema.ndgrants_rules.model.FinancialSystem financialSystem)
   {
      this.financialSystem = financialSystem;
   }

   public Vendor(
         java.lang.Long vendorId,
         java.lang.String name,
         java.lang.String vendorNo,
         java.lang.String duns,
         java.lang.String duns4,
         java.util.List<gov.dhs.fema.ndgrants_rules.model.Organization> granteeOrganizations,
         gov.dhs.fema.ndgrants_rules.model.Address address,
         java.lang.String dunsFromIFMIS, boolean associatedWithAnAward,
         boolean newVendor, java.lang.Long granteeOrganizationId,
         gov.dhs.fema.ndgrants_rules.model.FinancialSystem financialSystem)
   {
      this.vendorId = vendorId;
      this.name = name;
      this.vendorNo = vendorNo;
      this.duns = duns;
      this.duns4 = duns4;
      this.granteeOrganizations = granteeOrganizations;
      this.address = address;
      this.dunsFromIFMIS = dunsFromIFMIS;
      this.associatedWithAnAward = associatedWithAnAward;
      this.newVendor = newVendor;
      this.granteeOrganizationId = granteeOrganizationId;
      this.financialSystem = financialSystem;
   }

}